### ISSUE TITLE
Improve Accordion/readme.md

### ISSUE THREAD

**Issue by nik132-eng** [Clueless-Community/seamless-ui#1005]
Need to improve this component on `\<Component name>\src\<File Name.html>`

## Improvements required :
add components with images

## Any reference image?
![image](https://user-images.githubusercontent.com/77881638/208254049-affd6a45-fb64-48e9-ae3e-bd5889f32cab.png)
  
## Any external reference?
  
You can checkout [this]() one for better understanding.

**Comment by Rajdip019** [comment]
The image and should be proper size and aspect ratio. @nik132-eng
