### ISSUE TITLE
Improve Form/Readme.md

### ISSUE THREAD

**Issue by nik132-eng** [Clueless-Community/seamless-ui#1009]
Need to improve this component on `\<Component name>\src\<File Name.html>`

## Improvements required :
make it in table formate

## Any reference image?
  
![image](https://user-images.githubusercontent.com/77881638/208254355-7782bdd0-3750-4094-8a06-3a02bde44a54.png)

## Any external reference?
  
You can checkout [this]() one for better understanding.

**Comment by Rajdip019** [comment]
The image size and aspect ratio should be consistent unlike this one. @nik132-eng
