### ISSUE TITLE
Improve Apple Store Buttons

### ISSUE THREAD

**Issue by itz-deepak** [Clueless-Community/seamless-ui#1028]
Need to improve this component on `\Store Buttons\src\<apple-store-button.html>`

## Improvements required :
Make  deign a given in figma

## Any reference image?

![image](https://user-images.githubusercontent.com/83635276/208284585-a6847164-e86a-46ff-8b61-b3bb32780bfe.png)

**Comment by Dibyendu303** [comment]
@itz-deepak Recently updated.

**Comment by Rajdip019** [comment]
This one is done. So no need of this.
