### ISSUE TITLE
Create a Readme for Navbar

### ISSUE THREAD

**Issue by RavindraP04** [Clueless-Community/seamless-ui#1031]
## How to create a Readme for [Navbar](https://github.com/Clueless-Community/seamless-ui/tree/main/Navbar) ?
1) Copy each component code and paste it in [Tailwind Playground](https://play.tailwindcss.com/)
2) Take a screenshot of that. (Make sure to have a proper aspect ratio. 16:9 will be good) and add it to the readme in the table format
2) Make sure to enclose the screenshot under anchor tag so that one can just choose the navbar and after clicking that image will be redirected to the code of that navbar. 
NOTE:- Make sure each component screenshot is of equal size so that it fits in the layout 

For Reference you can see [Button Readme](https://github.com/Clueless-Community/seamless-ui/blob/main/Buttons/README.md)

**Comment by Dibyendu303** [comment]
Please assign me @Rajdip019
