### ISSUE TITLE
Create a Readme for Avatar 

### ISSUE THREAD

**Issue by RavindraP04** [Clueless-Community/seamless-ui#1033]
## How to create a Readme for [Avatar](https://github.com/Clueless-Community/seamless-ui/tree/main/Avatar) ?
1) You need to copy paste the buttons code in  [Tailwind Playground](https://play.tailwindcss.com/)
2) Wrap all of them in a div and then add a class='flex justify-center items-center h-screen '  you can use flex-col too as per component size.
3) Take a screenshot of that and add it to the readme in the table format
4) Make sure to enclose the screenshot under anchor tag so that one can just choose the Avatar and after clicking that image will be redirected to the code of that Avatar. 
NOTE:- Make sure each component screenshot is of equal size so that it fits in the layout 

For Reference you can see [Button Readme](https://github.com/Clueless-Community/seamless-ui/blob/main/Buttons/README.md)

**Comment by Dibyendu303** [comment]
@RavindraP04 are you working on it ?

**Comment by RavindraP04** [comment]
No, @Dibyendu303 If you want you can work on it.

**Comment by Dibyendu303** [comment]
Please assign me @Rajdip019
