### ISSUE TITLE
Create Readme for Badges

### ISSUE THREAD

**Issue by RavindraP04** [Clueless-Community/seamless-ui#1035]
## How to create a Readme for [Badges](https://github.com/Clueless-Community/seamless-ui/tree/main/Badges)?
1) You need to copy paste the buttons code in  [Tailwind Playground](https://play.tailwindcss.com/)
2) Wrap all of them in a div and then add a class='flex justify-center items-center h-screen '  you can use flex-col too as per component size.
3) Take a screenshot of that and add it to the readme in the table format
4) Add the badges according to these categories:-
Types of Badges 🔽
    Default badge
    Badges with icon
    Notification badge
    Button with badge
    Badge with icon only

5) Make sure to enclose the screenshot under anchor tag so that one can just choose the Avatar and after clicking that image will be redirected to the code of that Avatar. 
NOTE:- Make sure each component screenshot is of equal size so that it fits in the layout 

For Reference you can see [Button Readme](https://github.com/Clueless-Community/seamless-ui/blob/main/Buttons/README.md)

**Comment by Dibyendu303** [comment]
Please assign me @Rajdip019
