### ISSUE TITLE
Create mobile-filter-range

### ISSUE THREAD

**Issue by Dibyendu303** [Clueless-Community/seamless-ui#1042]
Create mobile-filter-range using `html` and `tailwind-css`.

## Any reference image?
![Screenshot (2137)](https://user-images.githubusercontent.com/66685553/208297253-c930ccfb-7456-424c-b362-7c61b8d2b903.png)

**Comment by Dibyendu303** [comment]
Please assign me @Rajdip019

**Comment by RavindraP04** [comment]
This thing is also already available, I just need to move it to mobile folder from desktop folder, https://github.com/Clueless-Community/seamless-ui/blob/main/Filters/src/desktop/marketplace_desktop_filter_range.html

**Comment by Rajdip019** [comment]
Same here.

**Comment by Dibyendu303** [comment]
@RavindraP04 is it possible without Javascript ?
