### ISSUE TITLE
Create mobile-filter-component

### ISSUE THREAD

**Issue by Dibyendu303** [Clueless-Community/seamless-ui#1043]
Create a mobile-filter-component using `html` and `tailwind-css`.

## Any reference image?
![Screenshot (2136)](https://user-images.githubusercontent.com/66685553/208297330-e95d7f7e-02b3-4a90-bf90-48d9358261e7.png)

**Comment by Dibyendu303** [comment]
Please assign me @Rajdip019

**Comment by RavindraP04** [comment]
This component is also already built, I just need to move it to mobile folder from desktop folder, https://github.com/Clueless-Community/seamless-ui/blob/main/Filters/src/desktop/marketplace_desktop_filter_5.html

**Comment by Rajdip019** [comment]
This is already built. @Dibyendu303
