### ISSUE TITLE
Create a file-upload.html

### ISSUE THREAD

**Issue by nik132-eng** [Clueless-Community/seamless-ui#1058]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
![image](https://user-images.githubusercontent.com/77881638/208320572-a8b9455d-ca4f-424a-b0ec-8b846db743e7.png)
After building the component please raise a PR with a screenshot of the component and add the component in `Form/src/file-upload.html`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by Rajdip019** [comment]
This is already there I guess can you confirm? @nik132-eng

**Comment by Dibyendu303** [comment]
Yes this is present

**Comment by nik132-eng** [comment]
![image](https://user-images.githubusercontent.com/77881638/208506812-fd32002c-7c8a-4d44-aa3b-7b095f00cbf3.png)

It is present in this format

**Comment by Rajdip019** [comment]
This present looks good I guess. @nik132-eng
