### ISSUE TITLE
Create a dropzone.html

### ISSUE THREAD

**Issue by nik132-eng** [Clueless-Community/seamless-ui#1059]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
![image](https://user-images.githubusercontent.com/77881638/208320675-6dce53c3-e9d5-4dab-98cb-856afea7256f.png)

After building the component please raise a PR with a screenshot of the component and add the component in `Form/src/dropzone.html`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by Rajdip019** [comment]
You need to make functionality, Not drip but click to upload. The marking this as a hard issue.
