### ISSUE TITLE
Create a checkbox-color.html

### ISSUE THREAD

**Issue by nik132-eng** [Clueless-Community/seamless-ui#1061]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
![image](https://user-images.githubusercontent.com/77881638/208320857-2f3918ed-f292-4e0b-9494-39e3e5bc042e.png)

After building the component please raise a PR with a screenshot of the component and add the component in `Form/src/checkbox-color.html`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by Tushar98644** [comment]
assign me @Rajdip019

**Comment by Rajdip019** [comment]
This one is a great thing to add. @nik132-eng
