### ISSUE TITLE
Create Readme for Breadcrumb

### ISSUE THREAD

**Issue by RavindraP04** [Clueless-Community/seamless-ui#1071]
## How to create a Readme for [Breadcrumb](https://github.com/Clueless-Community/seamless-ui/tree/main/Breadcrumb)?
1) You need to copy paste the buttons code in  [Tailwind Playground](https://play.tailwindcss.com/)
2) Wrap all of them in a div and then add a class='flex flex-col justify-center h-screen items-center w-screen' 
3) Take a screenshot of that and add it to the readme in the table format
4) Make sure to enclose the screenshot under anchor tag so that one can just choose the breadcrumb and after clicking that image will be redirected to the code of that breadcrumb. 
**_NOTE:- Make sure each component screenshot is of equal size so that it fits well in the layout._**

For Reference you can see [Button Readme](https://github.com/Clueless-Community/seamless-ui/blob/main/Buttons/README.md)

**Comment by Dibyendu303** [comment]
Please assign me @Rajdip019

**Comment by RavindraP04** [comment]
Done @Rajdip019
