### ISSUE TITLE
Notification panel

### ISSUE THREAD

**Issue by Tushar98644** [Clueless-Community/seamless-ui#1089]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
<img width="847" alt="Screenshot 2022-12-19 at 11 46 39 PM" src="https://user-images.githubusercontent.com/107763774/208493771-40c42045-5e87-436c-b490-9e6ebfa5da91.png">

After building the component please raise a PR with a screenshot of the component and add the component in `path of the file`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by Tushar98644** [comment]
assign me @Rajdip019

**Comment by Rajdip019** [comment]
Don't need new component. @Tushar98644
