### ISSUE TITLE
Assigned to feature

### ISSUE THREAD

**Issue by Tushar98644** [Clueless-Community/seamless-ui#1091]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 

<img width="342" alt="Screenshot 2022-12-19 at 11 54 24 PM" src="https://user-images.githubusercontent.com/107763774/208494178-52c3a178-8ae4-457e-a47a-d2c09f89ec0d.png">

After building the component please raise a PR with a screenshot of the component and add the component in `path of the file`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by Tushar98644** [comment]
assign me @Rajdip019

**Comment by Rajdip019** [comment]
This looks cool add this to other's folder. @Tushar98644
