### ISSUE TITLE
account options dropdown

### ISSUE THREAD

**Issue by Tushar98644** [Clueless-Community/seamless-ui#1093]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 

<img width="235" alt="Screenshot 2022-12-20 at 12 00 15 AM" src="https://user-images.githubusercontent.com/107763774/208495181-1181c129-dc48-43df-9db4-3040cdf17c5d.png">

After building the component please raise a PR with a screenshot of the component and add the component in `path of the file`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by Tushar98644** [comment]
assign me @Rajdip019

**Comment by Rajdip019** [comment]
We don't need this. @Tushar98644
