### ISSUE TITLE
Card footer with page button

### ISSUE THREAD

**Issue by Tushar98644** [Clueless-Community/seamless-ui#1094]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 

<img width="1222" alt="Screenshot 2022-12-20 at 12 02 17 AM" src="https://user-images.githubusercontent.com/107763774/208495512-408e4ea1-cc83-42dc-8419-6a6831564eda.png">

After building the component please raise a PR with a screenshot of the component and add the component in `path of the file`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by Rajdip019** [comment]
Add this to Other folder. @Tushar98644
