### ISSUE TITLE
Create a form component as per Figma file

### ISSUE THREAD

**Issue by Dibyendu303** [Clueless-Community/seamless-ui#1095]
Create this form component containing different types of selection button using `html` and `tailwind-css`.

## Any reference image?
![Screenshot (2169)](https://user-images.githubusercontent.com/66685553/208495327-984900c5-a943-4c22-9a53-0e92d2dcf156.png)

**Comment by Dibyendu303** [comment]
Please assign me @Rajdip019

**Comment by rupsha014** [comment]
@Dibyendu303 go ahead
