### ISSUE TITLE
Form as given in figma file

### ISSUE THREAD

**Issue by Tushar98644** [Clueless-Community/seamless-ui#1098]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
<img width="601" alt="Screenshot 2022-12-20 at 12 10 18 AM" src="https://user-images.githubusercontent.com/107763774/208496990-0f9fd1df-9023-4d91-a272-09379e1140c9.png">

After building the component please raise a PR with a screenshot of the component and add the component in `path of the file`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by Tushar98644** [comment]
> Already present under Tables

sigh....which parts are not already made ?

**Comment by Dibyendu303** [comment]
@Tushar98644 I think almost all the components are already made. Some components just need to be updated.

**Comment by Tushar98644** [comment]
> @Tushar98644 I think almost all the components are already made. Some components just need to be updated.

we can add new components which are not present in figma file?

**Comment by Dibyendu303** [comment]
> we can add new components which are not present in figma file?

Yes but for that you have to first ask for permission

**Comment by Tushar98644** [comment]
> > we can add new components which are not present in figma file?
> 
> Yes but for that you have to first ask for permission

permission as in the sense a new feature request , ryt?
