### ISSUE TITLE
Create a Header Banner 

### ISSUE THREAD

**Issue by Tushar98644** [Clueless-Community/seamless-ui#1101]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 

<img width="1306" alt="Screenshot 2022-12-20 at 12 17 41 AM" src="https://user-images.githubusercontent.com/107763774/208498044-98dbfcd4-3bc1-4f3a-b9f7-e60815696f3e.png">

After building the component please raise a PR with a screenshot of the component and add the component in `path of the file`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by Rajdip019** [comment]
The styling needs to follow the SeamLess UI design system. And you can add this Other's folder for now.
