### ISSUE TITLE
Create a Dashboard Navigation component

### ISSUE THREAD

**Issue by Tushar98644** [Clueless-Community/seamless-ui#1102]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 

<img width="854" alt="Screenshot 2022-12-20 at 12 27 33 AM" src="https://user-images.githubusercontent.com/107763774/208499652-eba535d3-c191-4cbe-9d4a-74cee0bb468c.png">

After building the component please raise a PR with a screenshot of the component and add the component in `path of the file`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by Tushar98644** [comment]
assign me @Rajdip019

**Comment by Rajdip019** [comment]
We don't need a new component right now. @Tushar98644
