### ISSUE TITLE
Create a automatic carousel slider

### ISSUE THREAD

**Issue by Tushar98644** [Clueless-Community/seamless-ui#1115]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 

<img width="811" alt="Screenshot 2022-12-20 at 10 05 08 AM" src="https://user-images.githubusercontent.com/107763774/208584742-2df6f2ef-4a47-4d93-a38c-dd07a05c55e6.png">

After building the component please raise a PR with a screenshot of the component and add the component in `path of the file`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by Rajdip019** [comment]
Will it be purely with HTML and Tailwind CSS? @Tushar98644

**Comment by Rajdip019** [comment]
Yeah make it. Add it to Others folder as well. As of now. @Tushar98644
