### ISSUE TITLE
Create avatar_chips for better customization

### ISSUE THREAD

**Issue by Tushar98644** [Clueless-Community/seamless-ui#1116]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component.

<img width="696" alt="Screenshot 2022-12-20 at 10 07 26 AM" src="https://user-images.githubusercontent.com/107763774/208584912-35d55c3c-acb3-4fb6-a5d1-1672b30bebda.png">

i think with the addition of chips, the ui can be enhanced 

After building the component please raise a PR with a screenshot of the component and add the component in `path of the file`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by Rajdip019** [comment]
Make this and add this to avatar, maintaining the sequence.
