### ISSUE TITLE
Create text_chips

### ISSUE THREAD

**Issue by Tushar98644** [Clueless-Community/seamless-ui#1117]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 

<img width="802" alt="Screenshot 2022-12-20 at 10 09 06 AM" src="https://user-images.githubusercontent.com/107763774/208585105-d5290bfc-4bbb-4242-a1f6-413f31da151d.png">

After building the component please raise a PR with a screenshot of the component and add the component in `path of the file`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by Rajdip019** [comment]
This is there no need of this right now. @Tushar98644
