### ISSUE TITLE
Create a collapser

### ISSUE THREAD

**Issue by Tushar98644** [Clueless-Community/seamless-ui#1118]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 

<img width="522" alt="Screenshot 2022-12-20 at 10 10 50 AM" src="https://user-images.githubusercontent.com/107763774/208585326-d2412ea8-4597-4d94-8820-85f8120a2766.png">
<img width="342" alt="Screenshot 2022-12-20 at 10 10 25 AM" src="https://user-images.githubusercontent.com/107763774/208585328-9cc6ee5c-f66b-42fc-8ad5-da25efcaeeea.png">

After building the component please raise a PR with a screenshot of the component and add the component in `path of the file`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by Tushar98644** [comment]
every modern website needs a toggle collapser....

**Comment by Rajdip019** [comment]
Make this and add this to others folder. @Tushar98644
