### ISSUE TITLE
Create a Avatar image input 

### ISSUE THREAD

**Issue by Tushar98644** [Clueless-Community/seamless-ui#1121]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 

<img width="1440" alt="Screenshot 2022-12-20 at 12 26 23 PM" src="https://user-images.githubusercontent.com/107763774/208602869-ef3136b0-a074-47db-ace8-876157a7e18e.png">
<img width="1396" alt="Screenshot 2022-12-20 at 12 27 58 PM" src="https://user-images.githubusercontent.com/107763774/208603086-69e6ea6d-10db-45b8-aa18-93924355a257.png">

After building the component please raise a PR with a screenshot of the component and add the component in `path of the file`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by Rajdip019** [comment]
Image on the left will change after choosing new image?  @Tushar98644

**Comment by Tushar98644** [comment]
> Image on the left will change after choosing new image? @Tushar98644

currently it's only for uploading images but it would be a good feature to add ....can implement it and would require js

**Comment by Rajdip019** [comment]
Can we do it only using CSS ti upload the image.

**Comment by Tushar98644** [comment]
> Can we do it only using CSS ti upload the image.

the image upload part is only css but displaying it on the avatar section would require js
