### ISSUE TITLE
Create a Processing animated button

### ISSUE THREAD

**Issue by Tushar98644** [Clueless-Community/seamless-ui#1122]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
<img width="255" alt="Screenshot 2022-12-20 at 12 29 25 PM" src="https://user-images.githubusercontent.com/107763774/208603383-03b1b33e-fa9b-48a3-bd6b-4df06ce6a70b.png">

After building the component please raise a PR with a screenshot of the component and add the component in `path of the file`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by Rajdip019** [comment]
This is already there. @Tushar98644
