### ISSUE TITLE
Create a feedback review

### ISSUE THREAD

**Issue by G0V1NDK** [Clueless-Community/seamless-ui#1140]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
![image](https://user-images.githubusercontent.com/83280091/208700731-10d96c26-7be8-4985-8ab3-8a5efe7a0e89.png)

After building the component please raise a PR with a screenshot of the component and add the component in `seamless-ui/Feedback Form/src`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

@Rajdip019 Adding more new components to feedback will allow diverse section in feedback.

**Comment by Rajdip019** [comment]
Review is already there. @G0V1NDK
