### ISSUE TITLE
Create a Graph section (graph-01.html

### ISSUE THREAD

**Issue by G0V1NDK** [Clueless-Community/seamless-ui#1141]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
![image](https://user-images.githubusercontent.com/83280091/208701651-74671bae-4a8f-4825-aeee-10b77ede7c18.png)

After building the component please raise a PR with a screenshot of the component and add the component in `seamless-ui/Graph/src/`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

The graph section UI will help user to visualize the data more clearly.
@Rajdip019

**Comment by Rajdip019** [comment]
Add it to others section. @G0V1NDK

**Comment by G0V1NDK** [comment]
Okay. I will do the same.
