### ISSUE TITLE
Create a Coming soon page

### ISSUE THREAD

**Issue by G0V1NDK** [Clueless-Community/seamless-ui#1145]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
![image](https://user-images.githubusercontent.com/83280091/208720704-414c2801-a2ac-4108-8f7b-b92254aec41f.png)

After building the component please raise a PR with a screenshot of the component and add the component in `others`. 

@Rajdip019

**Comment by Rajdip019** [comment]
We are not looking for new components as well as pages right now.
