### ISSUE TITLE
Create a breadcrumb with icons 

### ISSUE THREAD

**Issue by Tushar98644** [Clueless-Community/seamless-ui#1146]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
<img width="714" alt="Screenshot 2022-12-20 at 11 06 00 PM" src="https://user-images.githubusercontent.com/107763774/208730831-f6e4d272-e4b3-4d83-a17a-ab97ad9bb207.png">

After building the component please raise a PR with a screenshot of the component and add the component in `path of the file`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by Rajdip019** [comment]
Make this and add it to the breadcrumb section. @Tushar98644
