### ISSUE TITLE
Create a features section with video 

### ISSUE THREAD

**Issue by Tushar98644** [Clueless-Community/seamless-ui#1153]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
<img width="1057" alt="Screenshot 2022-12-20 at 11 19 45 PM" src="https://user-images.githubusercontent.com/107763774/208733044-1d68cbec-033e-43a2-9ff3-1026a3888b98.png">

After building the component please raise a PR with a screenshot of the component and add the component in `path of the file`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by Rajdip019** [comment]
We are not looking for these type of new components. So closing all of these.
