### ISSUE TITLE
Improve Movie Card component

### ISSUE THREAD

**Issue by RavindraP04** [Clueless-Community/seamless-ui#1167]
Need to improve this component on `Movie Card/src/movie-card-2.html`

## Improvements required :
Background image is not loading in the component.

## Any reference image?
  
![Screenshot_20221221_162732](https://user-images.githubusercontent.com/98400348/208889903-d2a04b3b-ea81-46d4-b094-513055401f1a.png)

[movie-card-2.html](https://github.com/Clueless-Community/seamless-ui/blob/main/Movie%20Card/src/movie-card-2.html)

**Comment by RavindraP04** [comment]
@Rajdip019 Please assign this to me .

**Comment by Dibyendu303** [comment]
@RavindraP04 It is loading fine.. please check again

**Comment by RavindraP04** [comment]
> @RavindraP04 It is loading fine.. please check again

![image](https://user-images.githubusercontent.com/98400348/208909394-1286ae9c-c859-4e87-b857-0bc190dba73a.png)
No it is not loading in mine, would be better to upload the bg-image to ibb or any other website and then just use that link.
What do you say @Rajdip019 ? Is it working fine in yours too ?

**Comment by Rajdip019** [comment]
Yeah do that. @RavindraP04
