### ISSUE TITLE
Improve danger alert 

### ISSUE THREAD

**Issue by Tushar98644** [Clueless-Community/seamless-ui#1199]
Right now the danger alert does not close on the click of the close button...make it functional

Here is a reference to the component. 
<img width="708" alt="Screenshot 2022-12-23 at 12 35 24 AM" src="https://user-images.githubusercontent.com/107763774/209208567-e6432754-f34c-4624-a71e-9b4ba4f1434b.png">

**Comment by Tushar98644** [comment]
assign me @Rajdip019

**Comment by Rajdip019** [comment]
You will need JS to do this  guess.

**Comment by Tushar98644** [comment]
> You will need JS to do this guess.

yes ....are we not allowed to use js?

**Comment by Rajdip019** [comment]
No we are not allowed to use JS in this.
