### ISSUE TITLE
improve widget 1

### ISSUE THREAD

**Issue by Tushar98644** [Clueless-Community/seamless-ui#1201]
Here is a reference to the component. 
<img width="1440" alt="Screenshot 2022-12-23 at 1 04 30 AM" src="https://user-images.githubusercontent.com/107763774/209212660-72a4f7f7-f2ff-48bd-a3ca-814c3264dd1e.png">

figma file:
<img width="260" alt="Screenshot 2022-12-23 at 1 05 11 AM" src="https://user-images.githubusercontent.com/107763774/209212794-7d4eb3ce-7bed-473d-962c-48f7f61a943d.png">

**Comment by Tushar98644** [comment]
assign me @Rajdip019

**Comment by Rajdip019** [comment]
This is already good @Tushar98644
