### ISSUE TITLE
Create a readme for Timeline

### ISSUE THREAD

**Issue by Tushar98644** [Clueless-Community/seamless-ui#1207]
<h1>How to create a Readme for Timeline?</h1>

 1.Copy each component code and paste it in [Tailwind Playground](https://play.tailwindcss.com/)
 2.Take a screenshot of that. (Make sure to have a proper aspect ratio. 16:9 will be good) and add it to the readme in the table format
 3.Make sure to enclose the screenshot under anchor tag so that one can just choose the stats and after clicking that image will be redirected to the code of that component.
NOTE:- Make sure each component screenshot is of equal size so that it fits in the layout.
For Reference you can see [Button Readme](https://github.com/Clueless-Community/seamless-ui/blob/main/Buttons/README.md)

**Comment by Dibyendu303** [comment]
It is present already

**Comment by Tushar98644** [comment]
> It is present already

i don't see a readme file in the timeline section

**Comment by Dibyendu303** [comment]
No no, I was saying about Alerts readme

**Comment by Tushar98644** [comment]
> No no, I was saying about Alerts readme
ya actually i mistakenly wrote alert instead of timeline first....after all readme files are created , how do we create new issues ?....we can't even add new components now...

**Comment by Dibyendu303** [comment]
> ya actually i mistakenly wrote alert instead of timeline first....after all readme files are created , how do we create new issues ?....we can't even add new components now...

You can update the "design systems", for example [Breadcrumb design system](https://github.com/Clueless-Community/seamless-ui/blob/main/Breadcrumb/breadcrum.design-system.mdx) or else you can update an existing component if you can make it better

**Comment by Tushar98644** [comment]
assign me @rupsha014 @Rajdip019
