### ISSUE TITLE
Improve Mobile Filter

### ISSUE THREAD

**Issue by RavindraP04** [Clueless-Community/seamless-ui#1227]
Need to improve this component on `Filters/src/mobile/marketplace-2.html`

## Improvements required :
1) Make dropdown clickable and selectable, currently it just shows options on hovering 
2) remove gray bg from the 4 boxes and give sone padding to the dropdown icon from right and make as per figma design
#### [marketplace-2.html](https://github.com/Clueless-Community/seamless-ui/blob/main/Filters/src/mobile/marketplace-2.html)
![Screenshot (49)](https://user-images.githubusercontent.com/98400348/209406737-8f54cdb5-f3b3-485b-954d-6541ef2af957.png)
#### Figma Design
![Screenshot_20221224_025249](https://user-images.githubusercontent.com/98400348/209406630-557af789-fb42-4d2c-a2e8-f2da77a4e888.png)

**Comment by rupsha014** [comment]
@RavindraP04 go ahead
