### ISSUE TITLE
Improve Mobile Filter Range

### ISSUE THREAD

**Issue by RavindraP04** [Clueless-Community/seamless-ui#1230]
Need to improve this component on `Filters/src/mobile/range_filter.html`

## Improvements required :
1) Replace Teal Color with Blue color as per figma design
2) Make design as per figma design
### [range_filter.html](https://github.com/Clueless-Community/seamless-ui/blob/main/Filters/src/mobile/range_filter.html)
![image](https://user-images.githubusercontent.com/98400348/209408736-0d75144a-dbc0-4722-9759-59384a77c04e.png)
### Figma design
![image](https://user-images.githubusercontent.com/98400348/209409010-fde71ee7-acaf-49bc-a4b4-378a000793dd.png)

**Comment by rupsha014** [comment]
@RavindraP04 go ahead
