### ISSUE TITLE
Update Range Filter in Mobile Filter marketplace 3

### ISSUE THREAD

**Issue by RavindraP04** [Clueless-Community/seamless-ui#1232]
Need to improve this component on `Filters/src/mobile/marketplace-3.html`

## Improvements required :
Update the Range filter in this component as per figms design

## Want to Updated From this 
![image](https://user-images.githubusercontent.com/98400348/209411140-9ad2a302-11d9-4bde-8a44-613ab2aa9699.png)
## to This 
![image](https://user-images.githubusercontent.com/98400348/209411213-bec31fc8-4635-4aa4-9647-58e6957018ee.png)

**Comment by rupsha014** [comment]
@RavindraP04 go ahead
