### ISSUE TITLE
Improve Filter Desktop Marketplace Products

### ISSUE THREAD

**Issue by RavindraP04** [Clueless-Community/seamless-ui#1234]
Need to improve this component on `Filters/src/Desktop/marketplace-products.html`

## Improvements required :
Category and Products box are input box with placeholder so change it to dropdown category feature

## Any reference image?

![Screenshot (50)](https://user-images.githubusercontent.com/98400348/209413959-ffbb5caf-7cf3-4979-8c89-5c73aeb49db2.png)

**Comment by rupsha014** [comment]
@RavindraP04 go ahead
