### ISSUE TITLE
Update with Selectable Dropdown

### ISSUE THREAD

**Issue by RavindraP04** [Clueless-Community/seamless-ui#1236]
Need to improve this component on `Filters/src/Desktop/desktop_filter_style_2.html`

## Improvements required :
Replace Hoverable + non selectable dropdown with clickable and selectable dropdown 

## Any reference image?
[desktop_filter_style_2.htm](https://github.com/Clueless-Community/seamless-ui/blob/main/Filters/src/desktop/desktop_filter_style_2.html)
![image](https://user-images.githubusercontent.com/98400348/209418372-1fa539f2-2c3e-43ac-9767-947e094bbb7d.png)

**Comment by rupsha014** [comment]
@RavindraP04 go ahead
