### ISSUE TITLE
Improve Filter Desktop 

### ISSUE THREAD

**Issue by RavindraP04** [Clueless-Community/seamless-ui#1237]
Need to improve this component on `Filters/src/desktop/marketplace-4.html`

## Improvements required :
1) Update Range component as per figma file 
2) Make properly responsive for all screen sizes

## Any reference image?

https://user-images.githubusercontent.com/98400348/209420024-82dff269-56c9-4071-9cec-2b5c0c547092.mp4

**Comment by rupsha014** [comment]
@RavindraP04 go ahead
