### ISSUE TITLE
Improve Content Cards/readme.md

### ISSUE THREAD

**Issue by nik132-eng** [Clueless-Community/seamless-ui#1240]
Need to improve this component on `Content Cards/readme.md`

## Any reference image?
  
![image](https://user-images.githubusercontent.com/77881638/209422385-7055ffe2-9520-4829-84fd-8824ad86b806.png)

## Any external reference?
  
![image](https://user-images.githubusercontent.com/77881638/209422393-cb375f3b-3bd5-48e8-a310-b5825f437733.png)

You can checkout [this]() one for better understanding.

**Comment by rupsha014** [comment]
@nik132-eng go ahead
