### ISSUE TITLE
Improve Feedback Form/src/feedback-1.html

### ISSUE THREAD

**Issue by nik132-eng** [Clueless-Community/seamless-ui#1243]
Need to improve this component on `Feedback Form/src/feedback-1.html`

## Improvements required :
-> make it same
-> add hover in both / make one green and one red
## Any reference image?
  
![image](https://user-images.githubusercontent.com/77881638/209422819-e7972a18-468d-4895-ae7f-621d3bde4a3e.png)

## Any external reference?
  
You can checkout [this]() one for better understanding.

**Comment by Abhijeet-2003** [comment]
Please assign this to me. @nik132-eng .

**Comment by nik132-eng** [comment]
> Please assign this to me. @nik132-eng .

There are many things to improve you can check it out. @Abhijeet-2003

**Comment by rupsha014** [comment]
@nik132-eng go ahead
