### ISSUE TITLE
Improve Movie card/readme.md

### ISSUE THREAD

**Issue by nik132-eng** [Clueless-Community/seamless-ui#1244]
Need to improve this component on `Movie card/readme.md`

## Improvements required :
![image](https://user-images.githubusercontent.com/77881638/209422881-9277e6fa-d0f0-4343-ab06-8d05fd8af2c4.png)

## Any reference image?
![image](https://user-images.githubusercontent.com/77881638/209422883-2eee67c0-7af7-477a-9dc6-96af6c2c1494.png)
  
## Any external reference?
  
You can checkout [this]() one for better understanding.

**Comment by rupsha014** [comment]
@nik132-eng go ahead
