### ISSUE TITLE
Improve Movie Card/src/movie-card-2.html

### ISSUE THREAD

**Issue by nik132-eng** [Clueless-Community/seamless-ui#1245]
We need to improve this component on `Movie Card/src/movie-card-2.html`

## Improvements required :
make It blue when hovering on button

## Any reference image?
![image](https://user-images.githubusercontent.com/77881638/209423018-967f6d58-1c80-4d84-a56d-f837bfb72a64.png)
  
## Any external reference?
![image](https://user-images.githubusercontent.com/77881638/209423023-4d0d8dfe-b23f-4411-9dd2-3af9fba63c80.png)
This is for color only
  
You can checkout [this]() one for better understanding.

**Comment by Abhijeet-2003** [comment]
Please assign this to me . @nik132-eng

**Comment by nik132-eng** [comment]
> Please assign this to me . @nik132-eng

There are many things to improve you can check it out. @Abhijeet-2003

**Comment by Abhijeet-2003** [comment]
can i start working on this then ?

**Comment by nik132-eng** [comment]
No, you can generate new issue of your

**Comment by Abhijeet-2003** [comment]
okay.

**Comment by Abhijeet-2003** [comment]
Sorry, I didn't know you're a participant.

**Comment by rupsha014** [comment]
@nik132-eng go ahead
