### ISSUE TITLE
Improve Movie Card/src/movie-card-3.html

### ISSUE THREAD

**Issue by nik132-eng** [Clueless-Community/seamless-ui#1246]
Need to improve this component on `Movie Card/src/movie-card-3.html`

## Improvements required :
Add more information while clicking on this button

## Any reference image?
![image](https://user-images.githubusercontent.com/77881638/209423056-8202e0f2-789f-417a-8670-12592e54d60f.png)
  
## Any external reference?
![image](https://user-images.githubusercontent.com/77881638/209423076-7ad05e08-f0df-4a45-a3fe-a2f7a3f85002.png)
  
You can checkout [this]() one for better understanding.

**Comment by rupsha014** [comment]
@nik132-eng go ahead
