### ISSUE TITLE
Improve Stats/readme.md

### ISSUE THREAD

**Issue by nik132-eng** [Clueless-Community/seamless-ui#1247]
Need to improve this component on `Stats/readme.md`

## Any reference image?
  
![image](https://user-images.githubusercontent.com/77881638/209423136-11693c14-7bf6-4460-8c3e-a7a65ffa70b5.png)

## Any external reference?
![image](https://user-images.githubusercontent.com/77881638/209423144-a6551a45-b373-4162-aa18-e7c7e2abc2e5.png)
  
You can checkout [this]() one for better understanding.

**Comment by Dibyendu303** [comment]
I have already updated it yesterday. PR is not merged yet.
