### ISSUE TITLE
Improve Footer 17 Blue

### ISSUE THREAD

**Issue by RavindraP04** [Clueless-Community/seamless-ui#1258]
Need to improve this component on `Footer/src/footer-blue-17.html`

## Improvements required :
Add logo on the top as per figma design
## Any reference image?
![image](https://user-images.githubusercontent.com/98400348/209437025-ad989f61-f9f1-4cb5-b2a6-475a6c8ed649.png)
## Figma design
![image](https://user-images.githubusercontent.com/98400348/209437074-6b3c456c-4e87-46f8-9bd2-5a1c26c59adf.png)

**Comment by RavindraP04** [comment]
@Rajdip019 @rupsha014  Please assign this to me

**Comment by rupsha014** [comment]
@RavindraP04 go ahead

**Comment by RavindraP04** [comment]
Done
