### ISSUE TITLE
Improve folder structure

### ISSUE THREAD

**Issue by nik132-eng** [Clueless-Community/seamless-ui#1297]
Need to improve this component on ``

## Improvements required :
proper folder structure for feedback form

## Any reference image?
  
![image](https://user-images.githubusercontent.com/77881638/209474257-9dbc19da-0d50-47ee-ab0e-fc154c74fa90.png)

## Any external reference?
  
You can checkout [this]() one for better understanding.

**Comment by rupsha014** [comment]
@nik132-eng go ahead
