### ISSUE TITLE
delete this file readme.md  files which are created outside of folder not proper linked with code

### ISSUE THREAD

**Issue by nik132-eng** [Clueless-Community/seamless-ui#1302]
## Current behavior

This is extra component created. For maintaining proper structure we have to remove file.

## Expected behavior

![image](https://user-images.githubusercontent.com/77881638/209476028-aad75cbe-cdb2-4e09-809d-3acad00e8866.png)

![image](https://user-images.githubusercontent.com/77881638/209476039-96b1c68e-a8fe-4f72-bfb4-f816af7c7638.png)

![image](https://user-images.githubusercontent.com/77881638/209476044-5558e266-27f7-45ab-9cc6-64feb53fa638.png)

![image](https://user-images.githubusercontent.com/77881638/209476053-1634e8f8-ede0-49de-a16b-2611f5d37a9e.png)

## Can you handle fixing this bug by yourself?

- [x] YES
- [ ] NO

## Environment details

- Browser: 
- OS: 
- Code Version:

**Comment by Rajdip019** [comment]
Do this on first priority @nik132-eng

**Comment by nik132-eng** [comment]
![image](https://user-images.githubusercontent.com/77881638/209476388-60979e76-7069-43f3-84d8-28316e64cf17.png)

![image](https://user-images.githubusercontent.com/77881638/209476396-f0ff0164-9b22-448d-a451-9d0845f0ea9f.png)

![image](https://user-images.githubusercontent.com/77881638/209476406-b82f578b-130c-44d0-8be4-a6b9b4514191.png)

can you give me this issue for improving three readme files after deleting this
