### ISSUE TITLE
Improve Store Buttons/src/store-button-amazon-lightmode.html

### ISSUE THREAD

**Issue by nik132-eng** [Clueless-Community/seamless-ui#1303]
Need to improve this component on `Store Buttons/src/store-button-amazon-lightmode.html`

## Improvements required :
add different size

## Any reference image?
  
![image](https://user-images.githubusercontent.com/77881638/209476163-c5786ffd-32e3-40ec-b9f0-2e03aa057884.png)

## Any external reference?

![image](https://user-images.githubusercontent.com/77881638/209476172-61a275cb-3ca6-483a-bfab-bcda15dbb7c3.png)

  
You can checkout [this]() one for better understanding.

**Comment by rupsha014** [comment]
@nik132-eng go ahead
