### ISSUE TITLE
Improve Store Buttons/src/store-button-google-play-lightmode.html

### ISSUE THREAD

**Issue by nik132-eng** [Clueless-Community/seamless-ui#1304]
Need to improve this component on `Store Buttons/src/store-button-google-play-lightmode.html`

## Improvements required :
remove border and make in three different size

## Any reference image?
  
![image](https://user-images.githubusercontent.com/77881638/209476214-05a876ea-6473-4e78-86c4-25d575b27e0f.png)

## Any external reference?
![image](https://user-images.githubusercontent.com/77881638/209476229-ba2e61c9-6d01-4811-bfb9-b7bb7329fa26.png)
  
You can checkout [this]() one for better understanding.

**Comment by rupsha014** [comment]
@nik132-eng  go ahead
