### ISSUE TITLE
Improve Store Buttons/src/store-button-apple-darkmode.html

### ISSUE THREAD

**Issue by nik132-eng** [Clueless-Community/seamless-ui#1305]
Need to improve this component on `Store Buttons/src/store-button-apple-darkmode.html`

## Improvements required :
make it in three different size

## Any reference image?
  
![image](https://user-images.githubusercontent.com/77881638/209476315-c0674bfb-655f-4c1a-a5ce-a11cd3c80b9d.png)

## Any external reference?
  
![image](https://user-images.githubusercontent.com/77881638/209476320-8cd1ce83-2a60-4574-93b5-28732a1aa5d5.png)

You can checkout [this]() one for better understanding.

**Comment by rupsha014** [comment]
@nik132-eng  go ahead
