### ISSUE TITLE
Improve Store Buttons/src/store-button-apple-darkmode.html

### ISSUE THREAD

**Issue by nik132-eng** [Clueless-Community/seamless-ui#1310]
Need to improve this component on `Store Buttons/src/store-button-apple-darkmode.html`

## Improvements required :
add different size of buttons

## Any reference image?
![image](https://user-images.githubusercontent.com/77881638/209477306-6bd01838-b924-4b02-83d6-8c9bf10b04dd.png)
  
## Any external reference?
  
You can checkout [this]() one for better understanding.

**Comment by rupsha014** [comment]
@nik132-eng  go ahead
