### ISSUE TITLE
Improve timeline folder

### ISSUE THREAD

**Issue by nik132-eng** [Clueless-Community/seamless-ui#1311]
Need to improve this component on `\<Component name>\src\<File Name.html>`

## Improvements required :
-> readme file in src folder , It should be out side of folder
-> readme file headline (bug)
-> need proper ratio of image (try to do it)

## Any reference image?
  
![image](https://user-images.githubusercontent.com/77881638/209477469-a6efc19c-0d6e-46bd-a93b-6f7af492e39a.png)

## Any external reference?
  
You can checkout [this]() one for better understanding.

**Comment by rupsha014** [comment]
@nik132-eng  go ahead
