### ISSUE TITLE
Improve Buttons/src/processing_button.html

### ISSUE THREAD

**Issue by nik132-eng** [Clueless-Community/seamless-ui#1312]
Need to improve this component on `Buttons/src/processing_button.html`

## Improvements required :
make it in three different size and blue 

## Any reference image?
![image](https://user-images.githubusercontent.com/77881638/209477874-3b4af4fc-2bbe-428a-abe9-2bc5e21bad49.png)
  
## Any external reference?
  
You can checkout [this]() one for better understanding.

**Comment by rupsha014** [comment]
@nik132-eng  go ahead
