### ISSUE TITLE
update readme for Movie card 

### ISSUE THREAD

**Issue by Tushar98644** [Clueless-Community/seamless-ui#1330]
refer to pr #1299

**Comment by nik132-eng** [comment]
I think this is not needed because. This is hover effect and our moto to show in read me is to show component

**Comment by Tushar98644** [comment]
> I think this is not needed because. This is hover effect and our moto to show in read me is to show component

ya....but i think we can create a separate field for the hover view as in the case in dark mode?

**Comment by rupsha014** [comment]
@Tushar98644 go ahead
