### ISSUE TITLE
update readme for feedback 

### ISSUE THREAD

**Issue by Tushar98644** [Clueless-Community/seamless-ui#1331]
refer to pr #1298

**Comment by RavindraP04** [comment]
@Tushar98644 I would just request you to close the issue which are completed 
![image](https://user-images.githubusercontent.com/98400348/209521103-7d5f7ce6-977e-41e2-baa6-20c8492c11d3.png)

**Comment by Tushar98644** [comment]
> @Tushar98644 I would just request you to close the issue which are completed ![image](https://user-images.githubusercontent.com/98400348/209521103-7d5f7ce6-977e-41e2-baa6-20c8492c11d3.png)

yes sure ....i thought the mentors would close it that's why i didn't....

**Comment by RavindraP04** [comment]
While Making PR just write **Resolved #(id of that issue )**  or **closes #(id for which that PR is )** 
Likewise you can use any one keyword (close, closes, closed, fix, fixes, fixed, resolve, resolves, resolved) and mention the id of that PR, The issue will automatically close after it has been merged

**Comment by Tushar98644** [comment]
> While Making PR just write **Resolved #(id of that issue )** or **closes #(id for which that PR is )** Likewise you can use any one keyword **(close, closes, closed, fix, fixes, fixed, resolve, resolves, resolved)** and mention the id of that PR, The issue will automatically close after it has been merged

ok got it...will do that from now on....

**Comment by rupsha014** [comment]
@Tushar98644 go ahead
