### ISSUE TITLE
Remove duplicate readme folder for feedback_forms

### ISSUE THREAD

**Issue by Tushar98644** [Clueless-Community/seamless-ui#1333]
#Reference:
<img width="889" alt="Screenshot 2022-12-26 at 12 59 44 PM" src="https://user-images.githubusercontent.com/107763774/209518465-c1c6416c-2e65-4a1d-b629-57ba01c026b9.png">

remove duplicate files to maintain the folder structure

**Comment by RavindraP04** [comment]
This issue is already assigned to @nik132-eng #1302
