### ISSUE TITLE
Incorrect folder structure 

### ISSUE THREAD

**Issue by Tushar98644** [Clueless-Community/seamless-ui#1334]
reference:
<img width="888" alt="Screenshot 2022-12-26 at 1 02 20 PM" src="https://user-images.githubusercontent.com/107763774/209518727-de76043d-9fcb-4792-85ae-7fc8f942b245.png">

the readme for store buttons was created in a seperate folder ....remove this and place it in the correct folder to maintain the folder structure

**Comment by RavindraP04** [comment]
This issue is already assigned to @nik132-eng
