### ISSUE TITLE
Replicate of readme for movie_card

### ISSUE THREAD

**Issue by Tushar98644** [Clueless-Community/seamless-ui#1335]
reference :

<img width="887" alt="Screenshot 2022-12-26 at 1 02 01 PM" src="https://user-images.githubusercontent.com/107763774/209518995-e6b9f946-9ead-4a61-8d55-f119e5b739a4.png">

remove this and correct the folder structure

**Comment by Tushar98644** [comment]
assign me @Rajdip019 @rupsha014

**Comment by RavindraP04** [comment]
This issue is already assigned to @nik132-eng
