### ISSUE TITLE
Improve Footer Blue 

### ISSUE THREAD

**Issue by RavindraP04** [Clueless-Community/seamless-ui#1350]
### Updates Required in footer Blue are:-
1) `footer-blue-1` 
    a) fix back to top button alignment
    b) Make proper & consistent footer bottom 
![Screenshot_20221226_104807](https://user-images.githubusercontent.com/98400348/209505396-b825af2f-18a4-4185-8d43-ede2d716b872.png)
![Screenshot_20221226_104821](https://user-images.githubusercontent.com/98400348/209505405-9c962c6b-8c05-4ded-aba1-e10794e5e3f3.png)
![Screenshot_20221226_104839](https://user-images.githubusercontent.com/98400348/209505407-4073ae9b-aede-4502-9589-dcac952b00e8.png)
---
2) `footer-blue-2` Fix the text color as per figma design
#### Existing footer text color
![image](https://user-images.githubusercontent.com/98400348/209506218-cca3b80c-4056-4d9f-b699-7d66182afcbe.png)
#### Figma Design text color
![image](https://user-images.githubusercontent.com/98400348/209506399-497a9b42-b04e-4d21-9ef4-c7951ad80193.png)
---
3) `footer-blue-3.html` 
    a) resize logo as per figma design
    b) Change bg color as per figma design from bg-blue-600 to #1855CB to maintain footer consistency
#### Existing Footer
![Screenshot_20221226_111757](https://user-images.githubusercontent.com/98400348/209508366-2bf5988d-5afb-401c-962a-2bf0cd9f0b04.png)
#### Figma Footer 
![image](https://user-images.githubusercontent.com/98400348/209508410-a4c4b6a8-b41d-4bb8-98d8-8d9e22b30bc4.png)
---
4) `footer-blue-4.html` 
   a)  Change bg color as per figma design from bg-blue-600 to #1855CB to maintain footer consistency
   b) Fix Subtext color and shade of `hr` color
#### Existing Footer 
![image](https://user-images.githubusercontent.com/98400348/209508645-d08c422d-74c1-4913-b8a2-306a59c8a932.png)
#### Figma Footer
![image](https://user-images.githubusercontent.com/98400348/209508670-6fb185ee-2443-484b-a84a-59e027544df2.png)
---
5) `footer-blue-5` **Re make this footer as per figma design because this footer is clone of footer blue 6**
#### Existing Footer
![image](https://user-images.githubusercontent.com/98400348/209508821-99cce734-c22f-4b62-b9ac-414713a8f454.png)
#### Figma Footer
![image](https://user-images.githubusercontent.com/98400348/209508860-b3e55bc8-2e65-4d29-ad58-82a40eaa263f.png)
---
6) `footer-blue-6`
   a) Add Back to top button as per figma design
   b) give some gapping between number and email as shown in figma design
#### Existing footer
![image](https://user-images.githubusercontent.com/98400348/209509026-fc936428-5be5-47b4-8245-a0416a9092e7.png)
#### Figma Footer
![image](https://user-images.githubusercontent.com/98400348/209509435-b00dba42-7145-4c74-ad6c-9adc801e33e7.png)
---
7) `footer-blue-9`
   a) Change bg color as per figma design from bg-blue-600 to #1855CB to maintain footer consistency
   b) Change text color as per figma design
#### Existing Footer
![image](https://user-images.githubusercontent.com/98400348/209509591-d9a6e0a0-0b22-484e-a787-3c00091941fb.png)
#### Figma Footer
![image](https://user-images.githubusercontent.com/98400348/209509623-3aa7f8b4-7158-45ff-83cb-8602a5acd975.png)
---
8) `footer-blue-10` 
   a) Change bg color as per figma design from bg-blue-600 to #1855CB to maintain footer consistency
   b) Remove container tag so that footer does not shrinks
   c) Make proper responsive at 360px screen
   d) Fix `hr` color shade as per figma design
#### Existing Footer
![image](https://user-images.githubusercontent.com/98400348/209509959-0860801c-3f0a-4626-8144-d2cc57cfe4e4.png)
#### Figma Footer
![image](https://user-images.githubusercontent.com/98400348/209509990-deb963aa-f6fc-47d3-b1ec-1c4df2010b3a.png)
---
9) `footer-blue-11`  Change bg color as per figma design from bg-blue-600 to #1855CB to maintain footer consistency
#### Existing Footer
![image](https://user-images.githubusercontent.com/98400348/209510396-5013e33e-3677-4a53-bb45-206890afdd75.png)
#### Figma footer
![image](https://user-images.githubusercontent.com/98400348/209510424-0fe5c4fa-d752-46aa-a76c-f420723a0e8f.png)
---
10) `footer-blue-12` Change bg color as per figma design from bg-blue-600 to #1855CB to maintain footer consistency
#### Existing Footer
![image](https://user-images.githubusercontent.com/98400348/209510509-63dc38bb-ed5e-4af3-b82d-dd80f2a17ac2.png)
#### Figma footer
![image](https://user-images.githubusercontent.com/98400348/209510542-1ec93a69-ed8e-4b77-b92d-5f2825b7bce9.png)
---
11) `footer-blue-13`
   a) Change bg color as per figma design from bg-blue-600 to #1855CB to maintain footer consistency
   b) Give some padding y as per figma design
   c) Changes Linkedin button, existing one has square around it
#### Existing footer
![image](https://user-images.githubusercontent.com/98400348/209510739-ec5993a5-7fab-4d5b-8d51-aac9e7eef4b5.png)
![image](https://user-images.githubusercontent.com/98400348/209510803-35013644-07e0-4300-8b8a-6f2b2d0754e0.png)
#### Figma Footer
![image](https://user-images.githubusercontent.com/98400348/209510776-a71911b7-9b9c-40ae-b039-ee191ddebca1.png)
---
12) `footer-blue-14` Remake whole footer as per figma design
#### Existing Footer 
![image](https://user-images.githubusercontent.com/98400348/209510903-585892cb-2ff4-48c8-b73f-3391b93b2cc8.png)
#### Figma Footer
![image](https://user-images.githubusercontent.com/98400348/209510929-e73293b9-5811-4374-b03a-c9003b64359a.png)
---
13) `footer-blue-15`
   a) Change bg color as per figma design from bg-blue-600 to #1855CB to maintain footer consistency
   b) reduce opacity of border of Email input box
   c) Give padding bottom as per figma design
#### Existing footer
![image](https://user-images.githubusercontent.com/98400348/209511150-990617c2-c2af-4222-a1e7-c3064eaabac0.png)
#### figma Footer
![image](https://user-images.githubusercontent.com/98400348/209511229-402df032-77d5-4866-a2ac-df232faa0895.png)
---
14) `footer-blue-16`
   a)  Change bg color as per figma design from bg-blue-600 to #1855CB to maintain footer consistency
   b) Make all the text justify-start and for smaller screen justify-center
#### Existing Footer
![image](https://user-images.githubusercontent.com/98400348/209511519-7aaa8b5c-5dc4-44f1-aeef-33b816612d25.png)
#### Figma footer
![image](https://user-images.githubusercontent.com/98400348/209511617-e15720bb-3e12-4131-81a7-4bd9d5ab44e6.png)

**Comment by RavindraP04** [comment]
@Rajdip019 @rupsha014 Please assign this to me

**Comment by rupsha014** [comment]
@RavindraP04  go ahead
