### ISSUE TITLE
Improve Foote Dark 6

### ISSUE THREAD

**Issue by RavindraP04** [Clueless-Community/seamless-ui#1356]
`footer-dark-6`
Back to top button is missing 
Give gap between Number and Email as shown in figma design
#### Existing Footer
![image](https://user-images.githubusercontent.com/98400348/209527169-5b63aed5-d0df-4c45-8c1b-8123331093d6.png)
#### Figma Design
![image](https://user-images.githubusercontent.com/98400348/209527204-4390104e-e0a9-48a1-8c6e-2a0e098d882d.png)

**Comment by RavindraP04** [comment]
@Rajdip019 @rupsha014 Please assign this to me

**Comment by rupsha014** [comment]
@RavindraP04  go ahead
