### ISSUE TITLE
Improve Footer dark 10

### ISSUE THREAD

**Issue by RavindraP04** [Clueless-Community/seamless-ui#1358]
`footer-dark-10.html`
a) Fix bg color as per figma design
b) Remove container tag
c) make responsive at 360 px mobile screen
#### Existing footer
![image](https://user-images.githubusercontent.com/98400348/209527854-3da5538b-eedc-4454-af86-226240c067ba.png)
![image](https://user-images.githubusercontent.com/98400348/209527997-6fc6ce49-df73-4bbc-91a2-0ec21e392c3b.png)

#### Figma Footer
![image](https://user-images.githubusercontent.com/98400348/209527914-c1754ea2-c9a7-43a4-b402-cf3bd9002fa2.png)

**Comment by RavindraP04** [comment]
@Rajdip019 @rupsha014 Please assign this to me

**Comment by rupsha014** [comment]
@RavindraP04  go ahead
