### ISSUE TITLE
Improve Store Buttons/src/store-button-windows-darkmode.html

### ISSUE THREAD

**Issue by nik132-eng** [Clueless-Community/seamless-ui#1364]
Need to improve this component on `Store Buttons/src/store-button-windows-darkmode.html`

## Improvements required :
add more sizes

## Any reference image?
  
![image](https://user-images.githubusercontent.com/77881638/209529716-ee8d9e05-cf78-4739-aad3-b74b3e70b232.png)

## Any external reference?

![image](https://user-images.githubusercontent.com/77881638/209529752-5623f0be-3734-4d6e-a7e6-8a8f07e78c13.png)
  
You can checkout [this]() one for better understanding.

**Comment by rupsha014** [comment]
@nik132-eng go ahead

**Comment by nik132-eng** [comment]
@rupsha014 can i work on this?

**Comment by rupsha014** [comment]
@nik132-eng go ahead
