### ISSUE TITLE
Improve Store Buttons/src/store-button-windows-lightmode.html

### ISSUE THREAD

**Issue by nik132-eng** [Clueless-Community/seamless-ui#1366]
Need to improve this component on `Store Buttons/src/store-button-windows-lightmode.htm`

## Improvements required :
add different sizes

## Any reference image?
![image](https://user-images.githubusercontent.com/77881638/209530018-b4ea26b0-f1e6-41f9-b029-b5053d000237.png)
  
## Any external reference?
![image](https://user-images.githubusercontent.com/77881638/209530026-660d452b-04fb-4dfa-8371-92e24ed55b3e.png)
  
You can checkout [this]() one for better understanding.

**Comment by rupsha014** [comment]
@nik132-eng go ahead
