### ISSUE TITLE
Improve  Store Buttons/src/store-button-apple-lightmode.html

### ISSUE THREAD

**Issue by nik132-eng** [Clueless-Community/seamless-ui#1367]
Need to improve this component on `Store Buttons/src/store-button-apple-lightmode.html`
add more sizes

## Improvements required :
![image](https://user-images.githubusercontent.com/77881638/209530369-7a493fb3-dd09-43f2-9ccf-5cfeb59c2645.png)

## Any reference image?
![image](https://user-images.githubusercontent.com/77881638/209530304-066df8e8-856f-4503-aa22-e3d5d150826f.png)
  
## Any external reference?
  
You can checkout [this]() one for better understanding.

**Comment by rupsha014** [comment]
@nik132-eng go ahead
