### ISSUE TITLE
Improve Store Buttons/src/store-button-google-play-darkmode.html

### ISSUE THREAD

**Issue by nik132-eng** [Clueless-Community/seamless-ui#1368]
Need to improve this component on `Store Buttons/src/store-button-google-play-darkmode.html`
add more sizes

## Improvements required :
![image](https://user-images.githubusercontent.com/77881638/209530600-2543d9ef-c2fb-4339-be94-4b7f8e17a40c.png)

## Any reference image?
![image](https://user-images.githubusercontent.com/77881638/209530615-d43514ff-0b7c-49ff-b873-87d068c30baa.png)
  
## Any external reference?
  
You can checkout [this]() one for better understanding.

**Comment by RavindraP04** [comment]
@nik132-eng I would request you to please close the older issues raised by you which are merged

**Comment by rupsha014** [comment]
@nik132-eng go ahead
