### ISSUE TITLE
readme.md of store button is not properly linked 

### ISSUE THREAD

**Issue by nik132-eng** [Clueless-Community/seamless-ui#1369]
## Current behavior

readme.md of store button is not properly linked and it is outside of folder so delete it.

## Expected behavior

![image](https://user-images.githubusercontent.com/77881638/209530949-bddc4c77-1d36-455e-8513-16adc5f7d2eb.png)

This files are not properly linked
![image](https://user-images.githubusercontent.com/77881638/209530956-0f8990ce-24dc-4143-a3aa-c1184b5c944b.png)

## Can you handle fixing this bug by yourself?

- [x] YES
- [ ] NO

## Environment details

- Browser: 
- OS: 
- Code Version:

**Comment by RavindraP04** [comment]
You already raised this issue #1302 
First complete that one on priority as @Rajdip019  said

**Comment by Rajdip019** [comment]
That is done I guess @nik132-eng ?

**Comment by nik132-eng** [comment]
yaa deleted files.

**Comment by nik132-eng** [comment]
This issue for not linked files has to change

**Comment by rupsha014** [comment]
@nik132-eng go ahead
