### ISSUE TITLE
Improve Store button/readme.md

### ISSUE THREAD

**Issue by nik132-eng** [Clueless-Community/seamless-ui#1370]
Need to improve this component on `Store button/readme.md`

## Improvements required :
update file after updating all buttons in three sizes

## Any reference image?
![image](https://user-images.githubusercontent.com/77881638/209531141-ab4e6f31-5f4e-453b-b77b-9132b7474195.png)
  
## Any external reference?
  
You can checkout [this]() one for better understanding.

**Comment by rupsha014** [comment]
@nik132-eng go ahead
