### ISSUE TITLE
Improve button dark mode - icon text rounded setting button

### ISSUE THREAD

**Issue by nik132-eng** [Clueless-Community/seamless-ui#1380]
Need to improve this component on `Buttons/src/Primary/icon-text-setting-rounded-button.html`

## Any reference image?
  
![image](https://user-images.githubusercontent.com/77881638/209534980-9b1ca036-c849-484c-9f9b-e0575533a4a2.png)
## Any external reference?
  
![image](https://user-images.githubusercontent.com/77881638/209533972-df0a53a9-b86d-4d71-bd4b-6ae75a5f48ad.png)

You can checkout [this]() one for better understanding.

**Comment by RavindraP04** [comment]
for Dark mode use #0A142F as bg

**Comment by nik132-eng** [comment]
ok sure

**Comment by nik132-eng** [comment]
After assign to me working on all buttons. @rupsha014  @Rajdip019 please assign it to me so I can start my work

**Comment by Rajdip019** [comment]
Start working you will get assigned 🙌

**Comment by Rajdip019** [comment]
> for Dark mode use #0A142F as bg

Is there any nearby tailwind pre-made class we can use? Then we should use that.

**Comment by nik132-eng** [comment]
> > for Dark mode use #0A142F as bg
> 
> Is there any nearby tailwind pre-made class we can use? Then we should use that.

Should I use bg-gray-500? @Rajdip019

**Comment by RavindraP04** [comment]
> > for Dark mode use #0A142F as bg
> 
> Is there any nearby tailwind pre-made class we can use? Then we should use that.

There are many but in all the dark footer we have used #0A142F, that is why I suggested to use this only for dark mode 

> > > for Dark mode use #0A142F as bg
> > 
> > 
> > Is there any nearby tailwind pre-made class we can use? Then we should use that.
> 
> Should I use bg-gray-500? @Rajdip019

But go the color you have used till now for dark mode, It would look consistent.
