### ISSUE TITLE
Improve designsytem of Widgets

### ISSUE THREAD

**Issue by rupsha014** [Clueless-Community/seamless-ui#1450]
Need to improve this component on `\<Widgets><Widgets.designsystem.mdx>`

## Any external reference?
  
You can checkout [this]() one for better understanding.

**Comment by Kumar-Ankit56** [comment]
@Rajdip019 assign me

**Comment by MaYaNkKashyap681** [comment]
Assign this to me, please.

**Comment by MaYaNkKashyap681** [comment]
Can I use Tailwind CSS for styling, and do I need to install it or should I use the CDN link?

**Comment by Kumar-Ankit56** [comment]
Bro you can tailwind play site. There you don't need to tailwind or even cdn as well

**Comment by MaYaNkKashyap681** [comment]
And the task is to modify the widget by changing some styles, am I right?

**Comment by Kumar-Ankit56** [comment]
Not the widget but need to improve the design system. Mdx

**Comment by MaYaNkKashyap681** [comment]
> Not the widget but need to improve the design system. Mdx

Ok
