### ISSUE TITLE
CREATE DESIGN SYSTEM FOR PRICING COMPONENTS

### ISSUE THREAD

**Issue by Tushar98644** [Clueless-Community/seamless-ui#1461]
Need to improve this component on `\<Component name>\src\<File Name.html>`

## Any external reference?
  
You can checkout [this]() one for better understanding.

**Comment by Tushar98644** [comment]
assign me @Rajdip019 @rupsha014

**Comment by rupsha014** [comment]
@Tushar98644 go ahead
