### ISSUE TITLE
Improve designsystem of filters

### ISSUE THREAD

**Issue by rupsha014** [Clueless-Community/seamless-ui#1462]
Need to improve this component on `\<filters>\src\<filters.designsystem.mdx>`

## Any external reference?
  
You can checkout [this]() one for better understanding.

**Comment by Kumar-Ankit56** [comment]
@Rajdip019 please allow me to look after it

**Comment by Kumar-Ankit56** [comment]
@Rajdip019 I message first. Please once check it. 🙂

**Comment by Rajdip019** [comment]
yeah I saw but I have assigned you to some other issues just giving others a fair chance. 😉
