### ISSUE TITLE
Improve Widget 5

### ISSUE THREAD

**Issue by RavindraP04** [Clueless-Community/seamless-ui#1495]
### [Widget-5](https://github.com/Clueless-Community/seamless-ui/blob/main/Widgets/src/widget-5.html)
After Clicking, the heading shows again with border-l, text-blue but it should not duplicate, it should be like I have shown with green Tick

![Screenshot_20230104_182509](https://user-images.githubusercontent.com/98400348/210559991-962f2982-394b-40f6-9673-8da3f8643007.png)

**Comment by rupsha014** [comment]
@RavindraP04 go ahead
