### ISSUE TITLE
Improve Widget 3

### ISSUE THREAD

**Issue by RavindraP04** [Clueless-Community/seamless-ui#1496]
#### Existing widget 3
![Screenshot_20230104_183757](https://user-images.githubusercontent.com/98400348/210562200-1daf4c39-704f-4d02-9aee-eff2f9e6cde9.png)
#### Figma Widget 3
![Screenshot_20230104_183713](https://user-images.githubusercontent.com/98400348/210562227-36065406-e6fb-47ad-871b-5093eceb4e19.png)

**Comment by RavindraP04** [comment]
@Rajdip019 @rupsha014 Please assign this to me

**Comment by rupsha014** [comment]
@RavindraP04 go ahead
