### ISSUE TITLE
Adding Login Page

### ISSUE THREAD

**Issue by AnkitMajee** [Clueless-Community/seamless-ui#1503]
## What is the motivation for adding/enhancing this feature?

New fully Responsive  Login Page 

## What are the acceptance criteria?

Fully Responsive Frontend login page
- [ ] ...

## Can you complete this feature request by yourself?

-YES

## Additional information

![image](https://user-images.githubusercontent.com/76817118/210613707-9e1855d7-f6b4-4885-af5d-198fe47a0a8f.png)

**Comment by Rajdip019** [comment]
This doesn't going with the design system.
