### ISSUE TITLE
Improve the content-card-7

### ISSUE THREAD

**Issue by Kumar-Ankit56** [Clueless-Community/seamless-ui#1512]
## Improvement area of image:
Top-Left border-radius is not visible it's getting into the left corner. 
![Screenshot (107)](https://user-images.githubusercontent.com/73521123/210739442-f209972a-f9bf-46f6-945c-5a541ee9482f.png)

  
Please checkout this is final design of this specific component 
https://play.tailwindcss.com/DNcAeohyYU?size=864x1948

**Comment by Kumar-Ankit56** [comment]
@Rajdip019 and @rupsha014 please review and assign me.

**Comment by Rajdip019** [comment]
Don't need this particular right now. @Kumar-Ankit56
