### ISSUE TITLE
Improved design system of Avatar Component

### ISSUE THREAD

**Issue by Kumar-Ankit56** [Clueless-Community/seamless-ui#1522]
Need to improve this component on `\<Avatar>\src\<alert.design-system.mdx>`

## Any external reference?
  
You can checkout [this]() one for better understanding.

**Comment by Kumar-Ankit56** [comment]
@Rajdip019 Please allow me to look after it.

**Comment by Rajdip019** [comment]
This issue is already raised and assigned.
