### ISSUE TITLE
Update design system of Contact component

### ISSUE THREAD

**Issue by Kumar-Ankit56** [Clueless-Community/seamless-ui#1529]
Need to improve this component on `\<Contact>\src\<contact.design-system.mdx>`

## Improvements done as :
1. A brief intro about component.
2. Adding 1 or 2 more images to make it more clear to user with different design for same component.
3. Updating background and text color.
4. Adding other properties with value that is left in current design-system.mdx like border-radius what value is in componet etc.

@Rajdip019 These are the most changes in all created issues. 
I'm trying to shape the design system something like this. This was the first design system created by me.

https://github.com/Clueless-Community/seamless-ui/blob/main/Breadcrumb/breadcrum.design-system.mdx
  
You can checkout [this]() one for better understanding.

**Comment by Kumar-Ankit56** [comment]
@Rajdip019 @rupsha014 please assign me

**Comment by Rajdip019** [comment]
In all of those please mention what improvement you are going to do.

**Comment by Kumar-Ankit56** [comment]
> In all of those please mention what improvement you are going to do.

Yeah Sure, I'm just updating.
Btw in all design system only few information is giving. So I'm just adding some more information.
But let me mention there as well.

**Comment by Kumar-Ankit56** [comment]
@Rajdip019 I have updated all created issues as per your guidance and if you have any disagreement in mention changes then please once review the current design system of component and design system attached link above. I believe you will agree with this fact mention changes should be there.

Only 2 hr left. Please allow me to do the further process as I'm also ready with changes just waiting for assign role. I will create the Prs in same moment as soon as I get assigned.

**Comment by Rajdip019** [comment]
Work on these man.

**Comment by Rajdip019** [comment]
Yeah assigned you make your PR's as well fast.
