### ISSUE TITLE
Ideas for Winter of Code ( WOC ) 2023

### ISSUE THREAD

**Issue by Rajdip019** [Clueless-Community/seamless-ui#1581]
1. Make the Docs website for SeamLess UI : We will be using `nextra` theme and Tailwind CSS to make the website. You have to make react components and write `.mdx` file where you will be writing docs and rendering your made react components.

2. Update the whole design - We will be updating the whole design of the components to more modern UI. You need to know HTML and tailwind CSS for this and need to be a perfectionist.  Knowledge of anything else will be an plus 1.

3. Make the UI ready for react as well - Knowledge of React will be must and ideation and thinking skills are most important thing.

You can make proposals for this following ideas.

**Comment by poorvadiwan** [comment]
Hey @Rajdip019 I am new to web development and I know **HTML** and **tailwind CSS** but not react, I have done **documentation** before as well. I would like to contribute to this project, can you kindly share some more details? Thanks.

**Comment by Rajdip019** [comment]
Will share more details soon. @poorvadiwan
