### ISSUE TITLE
Improve Avatar Readme

### ISSUE THREAD

**Issue by RavindraP04** [Clueless-Community/seamless-ui#1583]
Need to improve this component on `\Avatar\Readme.md`

## Improvements required :
Update the images in the images in readme of Avatar

## Any reference image?
Currently its not displaying image of any component
To fix it just copy paste the code of each component in https://play.tailwindcss.com/ and take screenshot of proper aspect ration, host the image on any free image hosting websites update the link
  
![image](https://user-images.githubusercontent.com/98400348/215822335-c3858855-45c2-44cb-913d-1402fefd0078.png)

## Any external reference?
  
You can checkout [this](https://github.com/Clueless-Community/seamless-ui/tree/main/Avatar) one for better understanding.

**Comment by Tapo41** [comment]
I want to contribute, please assign it to me

**Comment by RavindraP04** [comment]
> I want to contribute, please assign it to me

Go Ahead

**Comment by Shantanu-Meta** [comment]
I want to contribute..

**Comment by Tapo41** [comment]
@RavindraP04  I updated it , now it is working properly ,I checked it on  https://play.tailwindcss.com/ .You can now merge it to main branch after rechecking from your end . I did it under diversion 2k23.
