### ISSUE TITLE
Feature: Adding a New Button with hover effect 

### ISSUE THREAD

**Issue by SurajPratap10** [Clueless-Community/seamless-ui#1608]
## What is the motivation for adding/enhancing this feature?
I want to add a New Button component inside the Buttons folder in which when the user hovers, it automatically transforms a bit and changes its color.
Need to add the component here  `/seamless-ui/tree/main/Buttons/src` in the Others section precisely.
## Can you complete this feature request by yourself?
- Yes

## Additional information

https://user-images.githubusercontent.com/92919173/216624646-beae481c-64d1-4529-99dd-74a5ee03519a.mp4

![a1](https://user-images.githubusercontent.com/92919173/216626318-d14e4653-58a9-4b40-be8b-5739a5b6e719.png)

**Comment by RavindraP04** [comment]
@SurajPratap10 I appreciate you for suggesting this new component but we are following a proper design system, you can check out the design system of each component in their respective folder also you can check the figma design in the main readme of SeamLess UI

**Comment by SurajPratap10** [comment]
> @SurajPratap10 I appreciate you for suggesting this new component but we are following a proper design system, you can check out the design system of each component in their respective folder also you can check the figma design in the main readme of SeamLess UI

Okay, I'm new to this project as I have been contributing to other projects so I was not aware. So, when I saw the buttons folder there are 8 templates given for say primary button and they are all already built so what to do extra on those already built buttons then if not adding?
