### ISSUE TITLE
Improve Feature Card 18 Black

### ISSUE THREAD

**Issue by kushalnl7** [Clueless-Community/seamless-ui#1772]
Need to improve this component on `\Feature cards\src\feature-card-18-black.html`

## Any reference image?
Before: 
<img width="228" alt="Screenshot 2023-02-11 at 12 04 05 PM" src="https://user-images.githubusercontent.com/64639902/218244412-a1508b00-4814-4fb6-bdd2-b868b18e6768.png">

After: 
<img width="224" alt="Screenshot 2023-02-11 at 12 04 22 PM" src="https://user-images.githubusercontent.com/64639902/218244415-51ce6f24-8f8f-43f2-bfea-82f1c24e0b72.png">

What do you think @RavindraP04?

**Comment by kushalnl7** [comment]
If the change is required, then I will like to move forward with it. Thanks!

**Comment by kushalnl7** [comment]
I have raised a PR for this. Please review it. Thanks!

**Comment by Rajdip019** [comment]
Great job @kushalnl7

**Comment by kushalnl7** [comment]
Thanks @Rajdip019
