### ISSUE TITLE
Improve Feature Card 18 Blue

### ISSUE THREAD

**Issue by kushalnl7** [Clueless-Community/seamless-ui#1773]
Need to improve this component on `\Feature cards\src\feature-card-18-blue.html`

## Any reference image?
Before: 
<img width="221" alt="Screenshot 2023-02-11 at 12 08 05 PM" src="https://user-images.githubusercontent.com/64639902/218244572-35f3cf08-0cd7-41c3-8879-5786af8c5029.png">

After: 
<img width="221" alt="Screenshot 2023-02-11 at 12 08 22 PM" src="https://user-images.githubusercontent.com/64639902/218244575-70cf7073-00c0-4f16-8f0d-7ed46b6b7ca6.png">

What do you think @RavindraP04?

**Comment by kushalnl7** [comment]
If the change is required, then I will like to move forward with it. Thanks!

**Comment by Rajdip019** [comment]
Make the changes for both.

**Comment by kushalnl7** [comment]
Hi @Rajdip019. I have made changes for both and raised PRs. Please review them. Thanks!

**Comment by Rajdip019** [comment]
You can also raise a issue of your own and work on that. @kushalnl7 

<h1 align=center> For the contributors 🫂 </h1>

### Haven't made your first-contribution yet? 😢
Do check our [First Contribution](https://github.com/Clueless-Community/first-contribution) repository, where we have provided the guidelines to set up Git and how to make a pull request !

---
# How to contribute? ( You must use tailwind CSS )
## Using Tailwind playground.

One can easily make a contribution to this repository without setting this up locally. If you are building a new UI component then follow the steps written below.

### Step 1:

&nbsp; Go to [Tailwind Playground](https://play.tailwindcss.com/).

### Step 2:

&nbsp; Build the UI componet using `HTML` and `Tailwind CSS`.

### Setup 3:

&nbsp; Add your code to the mentioned path and make a new PR.

### PR guide:

&nbsp; You need to make a PR with the template mentioned below.

```
Here is the component I have built. 

Here is a screenshot of that.

### Add a screenshot here
```

If you are solving any other issue, make your own PR. don't need to follow this template.

--- 

# Raise an issue and build a component you want to build.

- Navigate to the SeamLess UI repository on GitHub.
- Click on the "Issues" tab.
- Click on the "New issue" button. ![New Issue Badge](https://img.shields.io/badge/-New%20Issue-brightgreen)
- Then create an issue using the `New Component` issue template.
- Provide a descriptive title for the issue.
- Take a screenshot of the component you want to build from the [figma file](https://www.figma.com/file/qzwugAfEB1GL4FgWXw9R3Z/SeamLess-UI-Dev?node-id=0%3A1&t=qRahoepdI3B98cVA-1) and paste it in the issue description. Make sure the component is not already built.
-  Get assigned and build it.

This is super easy. 👍 
---
# FAQ

| Question | Answer |
| :--- | :--- |
| 1. What to do for local images? | You can upload the image online like [this](https://imgbb.com/) and use the image link. |
| 2. Does tailwind playground is enough to build any component ? | Yes, absolutely. |
| 3. How to test responsiveness in tailwind playground? | Tailwind play ground have a responsive mode where you can test it. You can find that option on the top right corner |
| 4. What are the pre-requisite to contribute? | Basic HTML and Tailwind CSS knowledge will be enough for contribution and making the components. |
---

# Project setup in local
## Fork and clone the repository
```bash
git clone https://github.com/Clueless-Community/web-ui-kit.git
```

## Change the directory
```bash
cd web-ui-kit

```

Once you are done with the changes, follow the steps to make the pull request.
## Create and checkout to the new branch.
```powershell
git checkout -b <branch_name>
```
## Add the changes
```
git add .
```

## Commit your change with a proper messagge
```
git commit -m "Enter your message here"
```

## Make the Pull Request
```
git push origin <branch_name>
```

**Comment by kushalnl7** [comment]
Thanks @Rajdip019
