### ISSUE TITLE
Update Readme of Button

### ISSUE THREAD

**Issue by RavindraP04** [Clueless-Community/seamless-ui#1790]
Need to improve this component on `Button/readme.md`

## Improvements required :
Update the Button readme as per newly designed Button components

**Comment by Tapo41** [comment]
@RavindraP04 I want to contribute

**Comment by Sarita-021** [comment]
Hi @RavindraP04  I would like to work on the issue under Jwoc . 
Can you assign it to me.

**Comment by Sarita-021** [comment]
No

**Comment by Priyamakeshwari** [comment]
I would like to work on this issue

**Comment by sarkartanmay393** [comment]
@RavindraP04 Is this issue still open?

**Comment by sarkartanmay393** [comment]
> Yes @sarkartanmay393, Do you want to work on it ?

Assign it to me 🎆

**Comment by sarkartanmay393** [comment]
@RavindraP04 How should I update readme ? Kindly tell in detail

**Comment by sarkartanmay393** [comment]
> We have fully re-made whole Button components as per our new design system, But the Button/readme.md are still of old design system, so now you have to copy paste the code of each component on play.tailwindcss.com and take screenshot of it, add that screenshot of the component in readme so that when someone clicks on that image, they will be redirected to the code of that particular component, All the images should be of equal aspect ratio like 16:9

 Okay, then I'm taking code from `main` branch as updated components.

**Comment by RavindraP04** [comment]
> > We have fully re-made whole Button components as per our new design system, But the Button/readme.md are still of old design system, so now you have to copy paste the code of each component on play.tailwindcss.com and take screenshot of it, add that screenshot of the component in readme so that when someone clicks on that image, they will be redirected to the code of that particular component, All the images should be of equal aspect ratio like 16:9
> 
> Okay, then I'm taking code from `main` branch as updated components.

Sure
