### ISSUE TITLE
Create Testimonial 6 Black

### ISSUE THREAD

**Issue by RavindraP04** [Clueless-Community/seamless-ui#1846]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component.  
![image](https://user-images.githubusercontent.com/98400348/219143967-944bcab5-ad94-48c7-8153-5e342e44001c.png)

Follow [figma design](https://www.figma.com/file/qzwugAfEB1GL4FgWXw9R3Z/SeamLess-UI-Dev?node-id=0%3A1&t=qRahoepdI3B98cVA-1) 

After building the component please raise a PR with a screenshot of the component and add the component in `Testimonials/src/testimonial-6.html` by replacing the existing code with yours and also rename the file to `testimonial-6-black.html` 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by Kumar-Ankit56** [comment]
@RavindraP04 assign me under JWOC

**Comment by Zubair-05** [comment]
@RavindraP04 I want to work on this issue can u please assign it to me

**Comment by Zubair-05** [comment]
Yeah I want to work on it. Can u please assign it to me??

**Comment by RavindraP04** [comment]
Assigning @Zubair-05

**Comment by Zubair-05** [comment]
I've made a PR. Can you please look into this.
