### ISSUE TITLE
Create Product Card 3 Blue

### ISSUE THREAD

**Issue by RavindraP04** [Clueless-Community/seamless-ui#1878]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
![image](https://user-images.githubusercontent.com/98400348/219555490-666f1d0d-0613-441a-bb83-698a171e3634.png)

Follow [figma design](https://www.figma.com/file/qzwugAfEB1GL4FgWXw9R3Z/SeamLess-UI-Dev?node-id=0%3A1&t=qRahoepdI3B98cVA-1) and to make the button use [Button Design System](https://github.com/Clueless-Community/seamless-ui/blob/main/Buttons/buttons.design-system.mdx)
 

After building the component please raise a PR with a screenshot of the component and add the component in `Product Cards/src/product-card-3-blue.html`
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by Aditya-Raghuvanshi** [comment]
i want to work on this issue under JWOC.

**Comment by Saishreekouda** [comment]
I would like to work on this

**Comment by RavindraP04** [comment]
@himanshu1221 Are you still working on it ?

**Comment by himanshu1221** [comment]
> @himanshu1221 Are you still working on it ?

Yes i am working on it i was bit stuck in my exams and will submit it shortly
