### ISSUE TITLE
Create Product Card 4 blue

### ISSUE THREAD

**Issue by RavindraP04** [Clueless-Community/seamless-ui#1889]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 

![image](https://user-images.githubusercontent.com/98400348/219877728-837106ff-1618-451b-bebb-89f4673b8148.png)

Follow [figma design](https://www.figma.com/file/qzwugAfEB1GL4FgWXw9R3Z/SeamLess-UI-Dev?node-id=0%3A1&t=qRahoepdI3B98cVA-1) and to make the button use [Button Design System](https://github.com/Clueless-Community/seamless-ui/blob/main/Buttons/buttons.design-system.mdx)
 
Make the component responsive too.

After building the component please raise a PR with a screenshot of the component and add the component in `Product Cards/src/product-card-4-blue.html`
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by neokd** [comment]
I would like to work on this issue under JWOC

**Comment by neokd** [comment]
okay

**Comment by neokd** [comment]
Now can i work on this issue, Since i have raised a PR already for #1875

**Comment by neokd** [comment]
sure

**Comment by Aditya-Raghuvanshi** [comment]
i want to work on this issue under JWOC.
