### ISSUE TITLE
Create Product card 2 white

### ISSUE THREAD

**Issue by RavindraP04** [Clueless-Community/seamless-ui#1892]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 

![Screenshot_20230218_222439](https://user-images.githubusercontent.com/98400348/219878182-4f14194b-f032-415f-be1e-85a90dc39bd6.png)

Follow [figma design](https://www.figma.com/file/qzwugAfEB1GL4FgWXw9R3Z/SeamLess-UI-Dev?node-id=0%3A1&t=qRahoepdI3B98cVA-1) and to make the button use [Button Design System](https://github.com/Clueless-Community/seamless-ui/blob/main/Buttons/buttons.design-system.mdx)
 
Make the component responsive too.

After building the component please raise a PR with a screenshot of the component and add the component in `Product Cards/src/product-card-2-white.html`
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by Atul-8115** [comment]
I want to work on this issue please assign it to me under jwoc

**Comment by SakshiShah29** [comment]
I would like to work on this issue

**Comment by bcsamrudh** [comment]
@RavindraP04 . I would love to work on this.

**Comment by AshutoshSingh2021** [comment]
I want to work on this issue under JWOC please assign it to me.

**Comment by Zubair-05** [comment]
@RavindraP04 I want to work on this issue. Can you please assign it to me under JWOC.

**Comment by RavindraP04** [comment]
Asiigning @Zubair-05
