### ISSUE TITLE
Create Product card 1 blue

### ISSUE THREAD

**Issue by RavindraP04** [Clueless-Community/seamless-ui#1905]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
![image](https://user-images.githubusercontent.com/98400348/219941980-5ac4c30a-5f05-4b30-9a11-7c9b0250e003.png)

Follow [figma design](https://www.figma.com/file/qzwugAfEB1GL4FgWXw9R3Z/SeamLess-UI-Dev?node-id=0%3A1&t=qRahoepdI3B98cVA-1) and to make the button use [Button Design System](https://github.com/Clueless-Community/seamless-ui/blob/main/Buttons/buttons.design-system.mdx)
 
Make the component responsive too.

After building the component please raise a PR with a screenshot of the component and add the component in `Product Cards/src/product-card-1-blue.html`
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by deepbeatz** [comment]
@RavindraP04 i want to work in this issue under JWOC

**Comment by KrunalGupta02** [comment]
Hi I want to work on this issue under jwoc

**Comment by Rubyseher** [comment]
I am interested to fix this issue , I am participating under JWOC. Can you assign me this issue?

**Comment by KrunalGupta02** [comment]
![image](https://user-images.githubusercontent.com/101408619/220927834-e4751382-860c-4da2-b42e-f3badacda8be.png)

I have made this one
