### ISSUE TITLE
Create Pricing card 0 white

### ISSUE THREAD

**Issue by RavindraP04** [Clueless-Community/seamless-ui#1914]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
![image](https://user-images.githubusercontent.com/98400348/220051854-6565d9bc-0cc7-424b-b956-8e1a3db115fb.png)

Follow [figma design](https://www.figma.com/file/qzwugAfEB1GL4FgWXw9R3Z/SeamLess-UI-Dev?node-id=0%3A1&t=qRahoepdI3B98cVA-1) and to make the button use [Button Design System](https://github.com/Clueless-Community/seamless-ui/blob/main/Buttons/buttons.design-system.mdx)
 
Make the component responsive too.

After building the component please raise a PR with a screenshot of the component and add the component in `Pricing Components/src/pricing-card-0-white.html`
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by SakshiShah29** [comment]
I would like to contribute to this issue

**Comment by SHYALI** [comment]
I want to work on this issue under jwoc
