### ISSUE TITLE
update readme

### ISSUE THREAD

**Issue by Code1705** [Clueless-Community/seamless-ui#1953]
## Can you handle fixing this bug by yourself?

- [ ] YES
- [ ] NO

## Environment details

- Browser: 
- OS: 
- Code Version:

**Comment by PalaVenkiReddy** [comment]
Please assign this issue to me under JWOC

**Comment by RavindraP04** [comment]
@Code1705 Can you please elaborate what do you want to update in readme ?

**Comment by PalaVenkiReddy** [comment]
Yeah sorry bhaiya i understood something wrong, can you please elaborate the bug?

**Comment by Code1705** [comment]
project maintainer rights and some elements to make it look attractive and interesting
