### ISSUE TITLE
Create a Content Card 34 black

### ISSUE THREAD

**Issue by animesh156** [Clueless-Community/seamless-ui#1954]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
![Screenshot (185)](https://user-images.githubusercontent.com/114474707/221010066-272d5396-9f57-4518-a597-00a73df7f8bc.png)

After building the component please raise a PR with a screenshot of the component and add the component in Feature Cards/src/feature-card-34-blue. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by animesh156** [comment]
@RavindraP04 can i work on this one under JWOC?

**Comment by AshutoshSingh2021** [comment]
I want to work on this issue under JWOC please assign it to me.

**Comment by animesh156** [comment]
@AshutoshSingh2021 bro i have created this issue for me u can find others

**Comment by RavindraP04** [comment]
@animesh156 https://github.com/Clueless-Community/seamless-ui/blob/main/Feature%20Cards/src/feature-card-29-black.html
It already exists
