### ISSUE TITLE
Create a Testimonial 7 black

### ISSUE THREAD

**Issue by animesh156** [Clueless-Community/seamless-ui#1956]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
![Screenshot (187)](https://user-images.githubusercontent.com/114474707/221236526-74c2e220-329c-448c-9041-1f090fe78ddd.png)

After building the component please raise a PR with a screenshot of the component and add the component in Testimonials/src/ Testimonial -7 -black.html
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by animesh156** [comment]
@RavindraP04  can i work on this issue under JWOC?

**Comment by RavindraP04** [comment]
@animesh156 https://github.com/Clueless-Community/seamless-ui/blob/main/Testimonials/src/testimonial-8-black.html
It is already made

**Comment by animesh156** [comment]
okay
