### ISSUE TITLE
Create a Store Button Windows black

### ISSUE THREAD

**Issue by animesh156** [Clueless-Community/seamless-ui#1959]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
![Screenshot (191)](https://user-images.githubusercontent.com/114474707/221346221-36e6e943-b540-423c-8c86-d75ae1683a85.png)

After building the component please raise a PR with a screenshot of the component and add the component in `Store Buttons/src/store-button-windows-black.html`
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by animesh156** [comment]
@RavindraP04 can i work on this one under JWOC?

**Comment by bhumi-125** [comment]
i want to work on this under JWOC

**Comment by animesh156** [comment]
@bhumi-125  i have created this one for me u can find other

**Comment by Hritik1503** [comment]
I want to work for on this issue under jwoc , please assign me

**Comment by sarkartanmay393** [comment]
@RavindraP04 Assign it to me, under JWOC.

**Comment by RavindraP04** [comment]
@animesh156 I have updated the path of the file for this component, Please Check

**Comment by animesh156** [comment]
@RavindraP04 okay got it

**Comment by Awesomeasma** [comment]
I would like to work on this issue under JWOC
