### ISSUE TITLE
create a content card

### ISSUE THREAD

**Issue by bhumi-125** [Clueless-Community/seamless-ui#1961]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
![Screenshot_20230223_225003](https://user-images.githubusercontent.com/92088482/221361107-244e9bd0-6675-41b5-b506-186d9e42c25d.png)

After building the component please raise a PR with a screenshot of the component and add the component in `path of the file`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by bhumi-125** [comment]
i want to work on this issue under jwoc

**Comment by Rubyseher** [comment]
I am interested to work on this under JWOC, can u assign me this issue?

**Comment by RavindraP04** [comment]
@bhumi-125 It is already completed https://github.com/Clueless-Community/seamless-ui/blob/main/Content%20Cards/src/content-card-2-white.html
