### ISSUE TITLE
Create a Store Button Windows White

### ISSUE THREAD

**Issue by RavindraP04** [Clueless-Community/seamless-ui#1962]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
![image](https://user-images.githubusercontent.com/98400348/221395791-000cfc77-52d3-4342-a5b2-57d40ffbed41.png)

After building the component please raise a PR with a screenshot of the component and add the component in `Store Buttons/src/store-button-windows-lightmode.html` and rename the file to `store-button-windows-white.html`
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by SHYALI** [comment]
I want to work on this issue under jwoc

**Comment by bhumi-125** [comment]
I want to work on this issue under jwoc

**Comment by Saishreekouda** [comment]
i want to work on this under jwoc

**Comment by Awesomeasma** [comment]
I would like to work on this issue under JWOC
