### ISSUE TITLE
 Create a Store Button Windows Blue

### ISSUE THREAD

**Issue by RavindraP04** [Clueless-Community/seamless-ui#1963]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
![image](https://user-images.githubusercontent.com/98400348/221395881-1a6152ab-2c6c-444e-96d5-777b7a94e259.png)

After building the component please raise a PR with a screenshot of the component and add the component in `Store Buttons/src/store-button-windows-blue.html`.
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by rt-001** [comment]
I would like to work on this.

**Comment by 07jhashubham** [comment]
Even I wanna work @RavindraP04, You can assign 1 to @rt-001 and 1 to me if you want

**Comment by bhumi-125** [comment]
I want to work on this issue under jwoc

**Comment by RavindraP04** [comment]
@07jhashubham Just comment on this #1966 if you want to work on that

**Comment by Kumar-Ankit56** [comment]
@RavindraP04 please assign me under JWOC

**Comment by RavindraP04** [comment]
@Kumar-Ankit56 Just comment on #1966, this one is already assigned

**Comment by Awesomeasma** [comment]
I would like to work on this issue under JWOC. Please assign it to me.

**Comment by RavindraP04** [comment]
@rt-001 Are you still working on it ?

**Comment by Awesomeasma** [comment]
> I would like to work on this issue under JWOC. Please assign it to me.

I would like to work on this under JWOC

**Comment by prafulbbandre** [comment]
@RavindraP04 I would like to work on it.

**Comment by RavindraP04** [comment]
@rt-001 Are you still working on it ?

**Comment by VaibhavTalkhande** [comment]
I want to work on it can you assign me this issue

**Comment by VaibhavTalkhande** [comment]
Is anyone working on it .if not, I would like to work on it

**Comment by prafulbbandre** [comment]
@RavindraP04 i want to work on this.

**Comment by RavindraP04** [comment]
@VaibhavTalkhande Do you want to work on #1995

**Comment by VaibhavTalkhande** [comment]
Yes

**Comment by RavindraP04** [comment]
> @RavindraP04 , yes

@VaibhavTalkhande Comment on the issue and will assign it to you.
