### ISSUE TITLE
 Create a Store Button Amazon Black

### ISSUE THREAD

**Issue by RavindraP04** [Clueless-Community/seamless-ui#1964]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
![image](https://user-images.githubusercontent.com/98400348/221396036-80bddfc2-7203-40e4-8dc3-41b4adc6264e.png)

After building the component please raise a PR with a screenshot of the component and add the component in `Store Buttons/src/store-button-amazon-black.html`.
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by bhumi-125** [comment]
I want to work on this issue under jwoc

**Comment by Saishreekouda** [comment]
i want to work on this under jwoc

**Comment by Zubair-05** [comment]
@RavindraP04 I want to work on this issue. Can you please assign to me under JWOC..

**Comment by Awesomeasma** [comment]
I would like to work on this issue under JWOC. Please assign it to me.

**Comment by SudiptaSaha123** [comment]
I want to work
