### ISSUE TITLE
 Create a Store Button Amazon White

### ISSUE THREAD

**Issue by RavindraP04** [Clueless-Community/seamless-ui#1965]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
![image](https://user-images.githubusercontent.com/98400348/221396113-3ef26d07-6c6f-4103-83d5-4daebdb67ec0.png)

After building the component please raise a PR with a screenshot of the component and add the component in `Store Buttons/src/store-button-amazon-white.html`.
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by RohitChauhan98** [comment]
Hello! I can do it please assign it to me...

**Comment by bhumi-125** [comment]
i want to work on this issue under jwoc

**Comment by KrunalGupta02** [comment]
Hi i want to work under jwoc label

**Comment by Awesomeasma** [comment]
I would like to work on this issue under JWOC. Please assign it to me.

**Comment by RohitChauhan98** [comment]
Hello! I have just forked the project...
Can you please Explain me the work....

**Comment by RohitChauhan98** [comment]
Hey! I have done the work
![image](https://user-images.githubusercontent.com/96790021/222150795-4e3eb1ea-9f58-41e8-aa99-1c3683a03bad.png)

**Comment by RohitChauhan98** [comment]
Can i send PR?
