### ISSUE TITLE
 Create a Store Button Amazon Blue

### ISSUE THREAD

**Issue by RavindraP04** [Clueless-Community/seamless-ui#1966]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
![image](https://user-images.githubusercontent.com/98400348/221396232-ce77dbeb-d362-4f86-9f58-d004720fe0d8.png)

After building the component please raise a PR with a screenshot of the component and add the component in `Store Buttons/src/store-button-amazon-blue.html`.
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by rt-001** [comment]
I would like to work on this.

**Comment by bhumi-125** [comment]
i want to work on this issue under jwoc

**Comment by Awesomeasma** [comment]
I would like to work on this issue under JWOC.

**Comment by neokd** [comment]
I would like to work on this under JWOC
