### ISSUE TITLE
Create Google play button black

### ISSUE THREAD

**Issue by RavindraP04** [Clueless-Community/seamless-ui#1976]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
![image](https://user-images.githubusercontent.com/98400348/221983327-0ef6f7ae-634e-4fb5-9281-707f80c46684.png)

After building the component please raise a PR with a screenshot of the component and add the component in `Store Buttons/src/store-button-google-play-darkmode.html` and rename the file to `store-button-google-play-black.html`
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by VaibhavTalkhande** [comment]
I would like to work on it under JWOC

**Comment by SHYALI** [comment]
I want to work on this issue under jwoc

**Comment by Saishreekouda** [comment]
i would like to work on this under jwoc

**Comment by AshutoshSingh2021** [comment]
I want to work on this issue under JWOC, please assign it to me.
