### ISSUE TITLE
Create Google play button white

### ISSUE THREAD

**Issue by RavindraP04** [Clueless-Community/seamless-ui#1977]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
![image](https://user-images.githubusercontent.com/98400348/222520918-48b2e2b4-91a9-450c-a7ed-e8dbf43efa66.png)

After building the component please raise a PR with a screenshot of the component and add the component in `Store Buttons/src/store-button-google-play-white.html`.
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by VaibhavTalkhande** [comment]
I would like to work on it under JWOC

**Comment by neokd** [comment]
I would like to work on this under jwoc

**Comment by Saishreekouda** [comment]
i would like to work on this under jwoc

**Comment by AshutoshSingh2021** [comment]
I want to work on this issue under JWOC, please assign it to me.

**Comment by Awesomeasma** [comment]
I would like to work on this issue under JWOC.

**Comment by neokd** [comment]
@RavindraP04 This issue is already done by AsuthoshSingh2021 when i was working on it under JWOC.
