### ISSUE TITLE
Create Google play button blue

### ISSUE THREAD

**Issue by RavindraP04** [Clueless-Community/seamless-ui#1978]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
![image](https://user-images.githubusercontent.com/98400348/221983670-885bc0ed-6870-43d4-bdb3-f259e520c059.png)

After building the component please raise a PR with a screenshot of the component and add the component in `Store Buttons/src/store-button-google-play-blue.html`.
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by VaibhavTalkhande** [comment]
Can I work on it under jwoc.

**Comment by VaibhavTalkhande** [comment]
Why don't you add all the four button issue ine one

**Comment by AshutoshSingh2021** [comment]
I want to work on this issue under JWOC, please assign it to me.

**Comment by Awesomeasma** [comment]
I would like to work on this issue under JWOC.
