### ISSUE TITLE
Create Apple store Button Blue

### ISSUE THREAD

**Issue by RavindraP04** [Clueless-Community/seamless-ui#1980]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
![image](https://user-images.githubusercontent.com/98400348/221984489-389b1faf-89a1-4ad7-8e86-d598e4414fb7.png)

After building the component please raise a PR with a screenshot of the component and add the component in `Store Buttons/src/store-button-apple-blue.html.html`.
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by VaibhavTalkhande** [comment]
I would like to work on it under JWOC

**Comment by neokd** [comment]
I would like to work on this under jwoc

**Comment by Saishreekouda** [comment]
i would like to work on this under jwoc

**Comment by AshutoshSingh2021** [comment]
I want to work on this issue under JWOC, please assign it to me.

**Comment by Awesomeasma** [comment]
I would like to work on this issue under JWOC.

**Comment by SakshiShah29** [comment]
I would like to work on this issue

**Comment by Priyamakeshwari** [comment]
I would like to work on this issue

**Comment by Priyamakeshwari** [comment]
I would like to work on this issue under JWOC
