### ISSUE TITLE
Create Apple store Button black

### ISSUE THREAD

**Issue by RavindraP04** [Clueless-Community/seamless-ui#1981]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
![image](https://user-images.githubusercontent.com/98400348/221984024-1edfcd9e-4502-4cdf-a463-492d2f6cd3b5.png)

After building the component please raise a PR with a screenshot of the component and add the component in `Store Buttons/src/store-button-apple-darkmode.html` and rename the file to `store-button-apple-black.html`
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by VaibhavTalkhande** [comment]
I would like to work on it under JWOC

**Comment by neokd** [comment]
I would like to work on this under jwoc

**Comment by Saishreekouda** [comment]
i would like to work on this under jwoc

**Comment by AshutoshSingh2021** [comment]
I want to work on this issue under JWOC, please assign it to me.

**Comment by SHYALI** [comment]
I want to work on this issue under jwoc

**Comment by Awesomeasma** [comment]
I would like to work on this issue under JWOC.

**Comment by SakshiShah29** [comment]
I would like to work on this issue

**Comment by Priyamakeshwari** [comment]
I would like to work under this issue

**Comment by SudiptaSaha123** [comment]
I want to work on this
