### ISSUE TITLE
Update Feature Card Readme 

### ISSUE THREAD

**Issue by RavindraP04** [Clueless-Community/seamless-ui#1984]
Need to improve this component on `Feature Cards/readme.md`

## Improvements required :
Update the Button readme as per newly designed Button components 

We have fully re-made whole `Feature Cards` components as per our new design system, But the `Feature Cards/readme.md` are still of old design system,
so now you have to copy paste the code of each component on play.tailwindcss.com and take screenshot of it, add that screenshot of the component in readme so that when someone clicks on that image, they will be redirected to the code of that particular component, All the images should be of equal aspect ratio like 16:9

**Comment by Priyamakeshwari** [comment]
I would like to work on this issue

**Comment by animesh156** [comment]
@RavindraP04 i want to work on this one under JWOC

**Comment by SHYALI** [comment]
please assign me this issue under JWOC.

**Comment by Priyamakeshwari** [comment]
I'm already working on this issue

**Comment by RavindraP04** [comment]
@Priyamakeshwari it has been over a week, are you still working on it ?

**Comment by Priyamakeshwari** [comment]
Its almost over will make a PR by today

**Comment by Laxmankohar** [comment]
Hey @RavindraP04  bro, I would like to work on this issue under jwoc. Can you assign it to me?

**Comment by VaibhavTalkhande** [comment]
i would like to work on it

**Comment by VaibhavTalkhande** [comment]
![Screenshot (36)](https://user-images.githubusercontent.com/49303222/229337734-69e4eef8-3f86-4e3e-8ebb-97379181303c.png)
This is the first row of readme I have created just take a look at it, so that I can move forward with completing the issue. If there is anything need to do, please let me know.
https://github.com/VaibhavTalkhande/seamless-ui/blob/main/Feature%20Cards/README.md

**Comment by AkshayPratapSingh09** [comment]
Hey Devs I think I would be able to pull this off ! Can U please assign this issue to me?

**Comment by RavindraP04** [comment]
Assigned @AkshayPratapSingh09

**Comment by AkshayPratapSingh09** [comment]
Raised the PR Please review it and merge
