### ISSUE TITLE
Improve Checkbox White

### ISSUE THREAD

**Issue by RavindraP04** [Clueless-Community/seamless-ui#1987]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
![image](https://user-images.githubusercontent.com/98400348/222259668-99c1126e-f9a8-4f3f-aaba-b176c97ac5e5.png)

After building the component please raise a PR with a screenshot of the component and add the component in `Form/src/checkbox-buttons.html` and rename the file to `checkbox-buttons-white.html`

You can also check the design in [figma](https://www.figma.com/file/qzwugAfEB1GL4FgWXw9R3Z/SeamLess-UI-Dev?node-id=0%3A1&t=9lrAGBHDcSPa4kGk-0)
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by Awesomeasma** [comment]
@RavindraP04 
I would like to work on this issue under JWOC.

**Comment by RavindraP04** [comment]
@Awesomeasma Can't Assign Multiple issue at once, So complete the previous one first

**Comment by Awesomeasma** [comment]
> @Awesomeasma Can't Assign Multiple issue at once, So complete the previous one first

okay sir

**Comment by Awesomeasma** [comment]
@RavindraP04 
I have completed my previous task.
Can u please assign this issue to me now ??
