### ISSUE TITLE
Create checkbox Black

### ISSUE THREAD

**Issue by RavindraP04** [Clueless-Community/seamless-ui#1988]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Instead of Black color use slate-900

Here is a reference to the component. 
![image](https://user-images.githubusercontent.com/98400348/224537339-fd8ab3a2-e628-4918-9761-8873ed42fba2.png)

After building the component please raise a PR with a screenshot of the component and add the component in `Form/src/checkbox-buttons-black.html`

You can also check the design in [figma](https://www.figma.com/file/qzwugAfEB1GL4FgWXw9R3Z/SeamLess-UI-Dev?node-id=0%3A1&t=9lrAGBHDcSPa4kGk-0)
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by vk20july** [comment]
I want to work on this issue under JWOC

**Comment by Awesomeasma** [comment]
@RavindraP04 
I would like to work on this issue under JWOC.

**Comment by Saishreekouda** [comment]
i want to work on this issue under jwoc

**Comment by AshutoshSingh2021** [comment]
I want to work on this issue under jwoc, please assign it to me.

**Comment by neokd** [comment]
I would like to work on this under JWOC

**Comment by Saishreekouda** [comment]
@RavindraP04 i already started working on this issue, please reassign this to me

**Comment by RavindraP04** [comment]
@Saishreekouda Are you done with #1979

**Comment by Saishreekouda** [comment]
yes i was done with it

**Comment by Saishreekouda** [comment]
i would like to work on this under jwoc

**Comment by VaibhavTalkhande** [comment]
I would like to work on it under JWOC

**Comment by VaibhavTalkhande** [comment]
Is this issue completed
