### ISSUE TITLE
Create Switch Button Black

### ISSUE THREAD

**Issue by RavindraP04** [Clueless-Community/seamless-ui#1991]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Instead of Black color use slate-900

Here is a reference to the component. 
![image](https://user-images.githubusercontent.com/98400348/222343054-d791b611-8b1c-405a-a73c-a42caa581a9e.png)

After building the component please raise a PR with a screenshot of the component and add the component in `Form/src/switch-buttons-black.html`

You can also check the design in [figma](https://www.figma.com/file/qzwugAfEB1GL4FgWXw9R3Z/SeamLess-UI-Dev?node-id=0%3A1&t=9lrAGBHDcSPa4kGk-0)
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by Awesomeasma** [comment]
@RavindraP04  
I would like to work on this issue under JWOC.

**Comment by KrunalGupta02** [comment]
Hi i would like to work on it under jwoc
