### ISSUE TITLE
Create Email Rounded white

### ISSUE THREAD

**Issue by RavindraP04** [Clueless-Community/seamless-ui#1993]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
small
![image](https://user-images.githubusercontent.com/98400348/222345248-415f89e1-6f54-41e0-ab99-d409f2055a1b.png)
large
![image](https://user-images.githubusercontent.com/98400348/222348092-8b662788-0a89-4b3a-892f-786c1a48d204.png)

After building the component please raise a PR with a screenshot of the component and add the component in `Form/src/email-rounded-white.html`

You can also check the design in [figma](https://www.figma.com/file/qzwugAfEB1GL4FgWXw9R3Z/SeamLess-UI-Dev?node-id=0%3A1&t=9lrAGBHDcSPa4kGk-0)
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by SHYALI** [comment]
I would like to work on this issue under jwoc .
