### ISSUE TITLE
Create Email Rounded black

### ISSUE THREAD

**Issue by RavindraP04** [Clueless-Community/seamless-ui#1994]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Instead of Black color use slate-900

Here is a reference to the component. 
small
![image](https://user-images.githubusercontent.com/98400348/222348564-758a8d0b-ce3a-4342-b34f-57480a844e68.png)

large
![image](https://user-images.githubusercontent.com/98400348/222348592-0ea3e584-a85b-47d5-8ce0-4fbd5c3bd955.png)

After building the component please raise a PR with a screenshot of the component and add the component in `Form/src/email-rounded-black.html`

You can also check the design in [figma](https://www.figma.com/file/qzwugAfEB1GL4FgWXw9R3Z/SeamLess-UI-Dev?node-id=0%3A1&t=9lrAGBHDcSPa4kGk-0)
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by AshutoshSingh2021** [comment]
I want to work on this issue under jwoc, please assign it to me.
