### ISSUE TITLE
Create Choose File Rounded White

### ISSUE THREAD

**Issue by RavindraP04** [Clueless-Community/seamless-ui#1995]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
small
![image](https://user-images.githubusercontent.com/98400348/222349425-525ab063-52b4-4874-a9a0-5e431bf09e84.png)
large
![image](https://user-images.githubusercontent.com/98400348/222349457-b0631696-c2f3-41ba-8479-9185c2dcdd20.png)

After building the component please raise a PR with a screenshot of the component and add the component in `Form/src/choose-file-rounded-white.html`

You can also check the design in [figma](https://www.figma.com/file/qzwugAfEB1GL4FgWXw9R3Z/SeamLess-UI-Dev?node-id=0%3A1&t=9lrAGBHDcSPa4kGk-0)
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by SudiptaSaha123** [comment]
I want to work on this

**Comment by SudiptaSaha123** [comment]
I am unable to make this

**Comment by Awesomeasma** [comment]
@RavindraP04 
I would like to work on this issue under JWOC..

**Comment by AshutoshSingh2021** [comment]
I want to work on this issue under jwoc, please assign it to me.

**Comment by Priyanshu88** [comment]
I would like to work under this issue. Please assign it to me. 
I have created the large one component.

**Comment by VaibhavTalkhande** [comment]
I would like to work on it
