### ISSUE TITLE
Create Choose File Rounded Black

### ISSUE THREAD

**Issue by RavindraP04** [Clueless-Community/seamless-ui#1996]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Instead of Black color use slate-900

Here is a reference to the component. 
small
![image](https://user-images.githubusercontent.com/98400348/222349761-e8844b54-e8c6-46c1-954e-d43d7df7c8e6.png)
large
![image](https://user-images.githubusercontent.com/98400348/222349804-355438cc-f85c-494d-8e93-c76cae5fc940.png)

After building the component please raise a PR with a screenshot of the component and add the component in `Form/src/choose-file-rounded-black.html`

You can also check the design in [figma](https://www.figma.com/file/qzwugAfEB1GL4FgWXw9R3Z/SeamLess-UI-Dev?node-id=0%3A1&t=9lrAGBHDcSPa4kGk-0)
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by SudiptaSaha123** [comment]
I want to work on this

**Comment by AshutoshSingh2021** [comment]
I want to work on this issue under jwoc, please assign it to me.

**Comment by neokd** [comment]
I would like to work on this under JWOC

**Comment by bhumi-125** [comment]
I  want to work on this issue under JWOC .
