### ISSUE TITLE
Create success rounded white

### ISSUE THREAD

**Issue by RavindraP04** [Clueless-Community/seamless-ui#1997]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
small
![image](https://user-images.githubusercontent.com/98400348/222350188-97f50dd5-0a5b-474b-a0fb-e194ac39f05f.png)

large
![image](https://user-images.githubusercontent.com/98400348/222350238-c72b51d4-4b71-4974-a8db-30a14455d1db.png)

After building the component please raise a PR with a screenshot of the component and add the component in `Form/src/success-rounded-white.html`

You can also check the design in [figma](https://www.figma.com/file/qzwugAfEB1GL4FgWXw9R3Z/SeamLess-UI-Dev?node-id=0%3A1&t=9lrAGBHDcSPa4kGk-0)
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by tmsagarofficial** [comment]
I would love to work on this issue under jwoc Pls assign it to me @RavindraP04

**Comment by RavindraP04** [comment]
@tmsagarofficial Please complete #2008 first

**Comment by AshutoshSingh2021** [comment]
I want to work on this issue under jwoc, please assign it to me.

**Comment by Saishreekouda** [comment]
I want to work on this under jwoc

**Comment by bhumi-125** [comment]
I want to work on this issue under JWOC .
