### ISSUE TITLE
Create Success Rounded Black

### ISSUE THREAD

**Issue by RavindraP04** [Clueless-Community/seamless-ui#1998]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Instead of Black color use slate-900

Here is a reference to the component. 
small
![image](https://user-images.githubusercontent.com/98400348/222350580-73152e8e-22dc-4e1c-bac2-a3780578a093.png)

large
![image](https://user-images.githubusercontent.com/98400348/222350625-68a9c43c-2ad9-423c-a73b-a1979285e7c0.png)

After building the component please raise a PR with a screenshot of the component and add the component in `Form/src/success-rounded-black.html`

You can also check the design in [figma](https://www.figma.com/file/qzwugAfEB1GL4FgWXw9R3Z/SeamLess-UI-Dev?node-id=0%3A1&t=9lrAGBHDcSPa4kGk-0)
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by SakshiShah29** [comment]
I would like to work on this issue
