### ISSUE TITLE
Create Error Rounded white

### ISSUE THREAD

**Issue by RavindraP04** [Clueless-Community/seamless-ui#2000]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
small
![image](https://user-images.githubusercontent.com/98400348/222351174-2f8f0541-fd03-4021-8531-418f801f2596.png)

large
![image](https://user-images.githubusercontent.com/98400348/222351218-0081f912-c330-4e42-9a5e-b1585bd5c0c2.png)

After building the component please raise a PR with a screenshot of the component and add the component in `Form/src/error-rounded-white.html`

You can also check the design in [figma](https://www.figma.com/file/qzwugAfEB1GL4FgWXw9R3Z/SeamLess-UI-Dev?node-id=0%3A1&t=9lrAGBHDcSPa4kGk-0)
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by SakshiShah29** [comment]
I would like to work on this issue
