### ISSUE TITLE
Create Search Rounded white

### ISSUE THREAD

**Issue by RavindraP04** [Clueless-Community/seamless-ui#2001]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
small
![image](https://user-images.githubusercontent.com/98400348/222351721-123e7e22-d02b-48ae-894d-f172a66006f0.png)

large
![image](https://user-images.githubusercontent.com/98400348/222351783-c631ee70-2583-4cdc-987f-fa58d546b18c.png)

After building the component please raise a PR with a screenshot of the component and add the component in `Form/src/search-rounded-white.html`

You can also check the design in [figma](https://www.figma.com/file/qzwugAfEB1GL4FgWXw9R3Z/SeamLess-UI-Dev?node-id=0%3A1&t=9lrAGBHDcSPa4kGk-0)
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by SakshiShah29** [comment]
I would like to work on this issue
