### ISSUE TITLE
Create Message Textarea Rounded white

### ISSUE THREAD

**Issue by RavindraP04** [Clueless-Community/seamless-ui#2005]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
![image](https://user-images.githubusercontent.com/98400348/222353271-16fb929f-5a88-4ee5-bd5b-f25285ffa73b.png)

After building the component please raise a PR with a screenshot of the component and add the component in `Form/src/message-textarea-rounded-white.html`

You can also check the design in [figma](https://www.figma.com/file/qzwugAfEB1GL4FgWXw9R3Z/SeamLess-UI-Dev?node-id=0%3A1&t=9lrAGBHDcSPa4kGk-0)
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by Atul-8115** [comment]
I want to contribute in this issue please assign it to me

**Comment by SudiptaSaha123** [comment]
I want to work on this
