### ISSUE TITLE
Create Message Textarea Rounded Black

### ISSUE THREAD

**Issue by RavindraP04** [Clueless-Community/seamless-ui#2006]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Instead of Black color use slate-900

Here is a reference to the component. 
![image](https://user-images.githubusercontent.com/98400348/222353584-2205b632-41c9-48b8-bb3d-74d051b99636.png)

After building the component please raise a PR with a screenshot of the component and add the component in `Form/src/message-textarea-rounded-black.html`

You can also check the design in [figma](https://www.figma.com/file/qzwugAfEB1GL4FgWXw9R3Z/SeamLess-UI-Dev?node-id=0%3A1&t=9lrAGBHDcSPa4kGk-0)
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by Atul-8115** [comment]
I want to contribute in this issue please assign it to me

**Comment by animesh156** [comment]
@RavindraP04 can i work on this one under JWOC
