### ISSUE TITLE
Create Select White

### ISSUE THREAD

**Issue by RavindraP04** [Clueless-Community/seamless-ui#2007]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
small
![image](https://user-images.githubusercontent.com/98400348/222353899-f1c60804-f3b5-4ef3-8fb2-00ab895ce8de.png)
large
![image](https://user-images.githubusercontent.com/98400348/222353954-526c1a88-d0eb-4ca8-8bda-ab97c26e2619.png)

After building the component please raise a PR with a screenshot of the component and add the component in `Form/src/select-white.html`

You can also check the design in [figma](https://www.figma.com/file/qzwugAfEB1GL4FgWXw9R3Z/SeamLess-UI-Dev?node-id=0%3A1&t=9lrAGBHDcSPa4kGk-0)
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by Atul-8115** [comment]
I want to contribute in this issue please assign it to me

**Comment by AshutoshSingh2021** [comment]
I want to work on this issue under jwoc, please assign it to me.

**Comment by Saishreekouda** [comment]
I would like to work on this under jwoc

**Comment by Saishreekouda** [comment]
I want to work on this under jwoc

**Comment by navjot09** [comment]
I would like to contribute to this issue.

**Comment by neokd** [comment]
I would like to work on this under JWOC

**Comment by RavindraP04** [comment]
Assigned @navjot09

**Comment by Awesomeasma** [comment]
I would like to work on this under JWOC.
