### ISSUE TITLE
Create Select Black

### ISSUE THREAD

**Issue by RavindraP04** [Clueless-Community/seamless-ui#2008]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Instead of Black color use slate-900

Here is a reference to the component. 
small
![image](https://user-images.githubusercontent.com/98400348/222354685-c99642f1-2813-4432-b74d-dbc00962c519.png)
large
![image](https://user-images.githubusercontent.com/98400348/222354721-85c2338c-f0f5-4e23-bc5e-c14408e07a4e.png)

After building the component please raise a PR with a screenshot of the component and add the component in `Form/src/select-black.html`

You can also check the design in [figma](https://www.figma.com/file/qzwugAfEB1GL4FgWXw9R3Z/SeamLess-UI-Dev?node-id=0%3A1&t=9lrAGBHDcSPa4kGk-0)
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by tmsagarofficial** [comment]
I would love to work on this issue under jwoc Pls assign it to me @RavindraP04

**Comment by neokd** [comment]
I would like to work on this under JWOC

**Comment by SHYALI** [comment]
please assign me this issue under JWOC.

**Comment by Awesomeasma** [comment]
I would like to work on this issue under JWOC.

**Comment by AshutoshSingh2021** [comment]
I want to work on this issue under jwoc, please assign it to me.
