### ISSUE TITLE
Create Select Rounded White

### ISSUE THREAD

**Issue by RavindraP04** [Clueless-Community/seamless-ui#2009]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
small
![image](https://user-images.githubusercontent.com/98400348/222355081-23a579e9-0664-4dc6-8e58-242fea8c95c8.png)
large
![image](https://user-images.githubusercontent.com/98400348/222355165-ee868162-8b25-4325-b53e-bc9be40ac120.png)

After building the component please raise a PR with a screenshot of the component and add the component in `Form/src/select-rounded-white.html`

You can also check the design in [figma](https://www.figma.com/file/qzwugAfEB1GL4FgWXw9R3Z/SeamLess-UI-Dev?node-id=0%3A1&t=9lrAGBHDcSPa4kGk-0)
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by VaibhavTalkhande** [comment]
Assign me this issue under JWOC

**Comment by VaibhavTalkhande** [comment]
Done

**Comment by RavindraP04** [comment]
@VaibhavTalkhande Firstly, give padding right after the dropdown arrow,
see like this 
![image](https://user-images.githubusercontent.com/98400348/222413178-0f106fab-fa77-4a35-999e-692e3f60b5d5.png)

**Comment by Atul-8115** [comment]
I want to contribute in this issue please assign it to me

**Comment by VaibhavTalkhande** [comment]
Done just sending pr
