### ISSUE TITLE
Create Select Rounded Black

### ISSUE THREAD

**Issue by RavindraP04** [Clueless-Community/seamless-ui#2010]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Instead of Black color use slate-900

Here is a reference to the component. 
small
![image](https://user-images.githubusercontent.com/98400348/222355520-a30c8765-a48d-435b-b09c-dd22c7981b4c.png)
large
![image](https://user-images.githubusercontent.com/98400348/222355548-e066404d-2f94-44ee-8e49-712bfc0fd0b8.png)

After building the component please raise a PR with a screenshot of the component and add the component in `Form/src/select-rounded-black.html`

You can also check the design in [figma](https://www.figma.com/file/qzwugAfEB1GL4FgWXw9R3Z/SeamLess-UI-Dev?node-id=0%3A1&t=9lrAGBHDcSPa4kGk-0)
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by VaibhavTalkhande** [comment]
I want to work on it under JWOC

**Comment by VaibhavTalkhande** [comment]
![Screenshot (20)](https://user-images.githubusercontent.com/49303222/222433288-d4e773b2-9de6-45c5-a133-3d462dbcc28d.png)

**Comment by RavindraP04** [comment]
@VaibhavTalkhande As per JWOC Rule, can't assign more than one issue at a time

**Comment by Atul-8115** [comment]
I want to contribute in this issue please assign it to me

**Comment by VaibhavTalkhande** [comment]
@RavindraP04 can I work on it now

**Comment by Saishreekouda** [comment]
I would like to work on this

**Comment by neokd** [comment]
I would like to work on this under JWOC

**Comment by Awesomeasma** [comment]
I would like on this issue under JWOC.

**Comment by Atul-8115** [comment]
@RavindraP04 Please assign this issue to me I have commented previously.

**Comment by SHYALI** [comment]
please assign me this issue .

**Comment by RavindraP04** [comment]
Assigned @VaibhavTalkhande

**Comment by anshikavashistha** [comment]
Please assign me this issue
