### ISSUE TITLE
Create a large form black

### ISSUE THREAD

**Issue by animesh156** [Clueless-Community/seamless-ui#2017]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
![Screenshot (206)](https://user-images.githubusercontent.com/114474707/222481366-13fb6e12-9dec-4b39-9727-439dc2bdc4e1.png)

After building the component please raise a PR with a screenshot of the component and add the component in Forms/src/large-form-black.html 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by animesh156** [comment]
@RavindraP04 can i work on this one under JWOC

**Comment by RavindraP04** [comment]
@animesh156 I have already raised the issues for these separately, Just comment and I will assign you
