### ISSUE TITLE
Improve Pricing Cards Readme

### ISSUE THREAD

**Issue by RavindraP04** [Clueless-Community/seamless-ui#2042]
Path of the file `Pricing Cards/readme.md`

You need to copy paste each Pricing Card component code separately in tailwind playground.

Wrap all of them in a div and then add a class='flex justify-center items-center h-screen'.

Take a screenshot of that. (Make sure to have a proper aspect ratio. 16:9 will be good) 

And then add those pictures in the src in the readme.md.

**Comment by Kumar-Ankit56** [comment]
@RavindraP04 assign me please

**Comment by Laxmankohar** [comment]
@RavindraP04 , I would like to work on this issue under JWOC. Can you please assign it to me?
