### ISSUE TITLE
Update readme of Product Cards 

### ISSUE THREAD

**Issue by RavindraP04** [Clueless-Community/seamless-ui#2050]
Path of the file `Product Cards/readme.md`

You need to copy paste each Product Card component code separately in [tailwind playground](https://play.tailwindcss.com)

Wrap all of them in a div and then add a class='flex justify-center items-center h-screen'.

Take a screenshot of that. (Make sure to have a proper aspect ratio. 16:9[Horizontal] 9:16[vertical] will be good) 

And then add those pictures in the src in the readme.md.

**Comment by Laxmankohar** [comment]
@RavindraP04 bro , I would  like to work on this issue under JWOC. Can you please assign it to me?

**Comment by RavindraP04** [comment]
Assigned @Laxmankohar

**Comment by RavindraP04** [comment]
@Laxmankohar check this, It might help https://www.loom.com/share/d48a8251142a47e4b9001341d5545c90

**Comment by Laxmankohar** [comment]
![image](https://user-images.githubusercontent.com/73365025/224541624-690277d1-8983-4c23-ac5a-f14b3a04d520.png)


@RavindraP04  bro, please have a look and confirm.

**Comment by Laxmankohar** [comment]
@RavindraP04 bro, confirm it sothat i can make a pr.

**Comment by RavindraP04** [comment]
@Laxmankohar there are total 12 components so update all
make 4 rows and 3 columns and there should not be blank spaces in the cells as it is in the product card 1 and 2 of above image in the right side 
make separate rows for horizontal components  and  vertical components

**Comment by Laxmankohar** [comment]
![image](https://user-images.githubusercontent.com/73365025/224564483-498abfc5-57af-443d-a59d-116eadb30104.png)
