### ISSUE TITLE
Create Collapser with View More and Shrink

### ISSUE THREAD

**Issue by RavindraP04** [Clueless-Community/seamless-ui#2051]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
![ezgif-4-e29cd3fee6](https://user-images.githubusercontent.com/98400348/223082188-77475799-d6f2-4a7a-a213-56f8e1b8a6fa.gif)

After building the component please raise a PR with a screenshot of the component and add the component in `Others/collapser-2.html`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by vk20july** [comment]
I want to work on this issue under jwoc

**Comment by Aditya-Raghuvanshi** [comment]
I want to work on this issue under JWOC.

**Comment by vk20july** [comment]
need to make the exact button or just have to make a button with collapse functionality

**Comment by pooranjoyb** [comment]
I want to work on this issue under JWOC'23 @RavindraP04

**Comment by Awesomeasma** [comment]
I would like to work on this under JWOC

**Comment by RavindraP04** [comment]
Assigned @Aditya-Raghuvanshi

**Comment by VaibhavTalkhande** [comment]
i would like to work on it @RavindraP04
