### ISSUE TITLE
Update Accordion Readme 

### ISSUE THREAD

**Issue by RavindraP04** [Clueless-Community/seamless-ui#2053]
Need to improve this component on `Accordion/readme.md`

## Improvements required :
Update accordion 3 in the readme.md file
  
## Any external reference?
You need to copy paste each component code separately in [tailwind playground](https://play.tailwindcss.com/)

Wrap it in a div and then add a class='flex justify-center items-center h-screen mx-10'.

Take a screenshot of that. (Make sure to have a proper aspect ratio. 16:9 will be good)

And then add those pictures in the src in the readme.md.
  
You can checkout [this](https://github.com/Clueless-Community/seamless-ui/blob/main/Accordion/README.md) one for better understanding.

**Comment by Laxmankohar** [comment]
Hey @RavindraP04 , I would like to work on this issue under jWOC. can you please assign it to me

**Comment by Babunshil** [comment]
Hi @RavindraP04 , i want to work on this issue under JWOC. can you please assign it to me

**Comment by SakshiShah29** [comment]
I would like to work on this issue

**Comment by bhumi-125** [comment]
I would like to work on this issue under jwoc

**Comment by Laxmankohar** [comment]
@RavindraP04 bro, please check it and confirm


![image](https://user-images.githubusercontent.com/73365025/223614673-0c81b0b1-517d-491f-b072-a7db0c679ce3.png)
![image](https://user-images.githubusercontent.com/73365025/223614543-ac6199dc-93da-41c5-a690-385aedcfc99b.png)

**Comment by RavindraP04** [comment]
@Laxmankohar Keep only 3 colums and 2 rows, so shift accordion-3 to 2nd Row

**Comment by Laxmankohar** [comment]
![image](https://user-images.githubusercontent.com/73365025/223754961-4eef5073-52cc-4915-91cf-c06d98c9e052.png)


@RavindraP04  is it ok?

**Comment by RavindraP04** [comment]
@Laxmankohar Perfect!

**Comment by Laxmankohar** [comment]
ok, now i am going to make pr.

**Comment by Laxmankohar** [comment]
> ok, now i am going to make pr.

done..

**Comment by Laxmankohar** [comment]
> > ok, now i am going to make pr.
> 
> done..

@RavindraP04  bro, i am done with the.. could you please check it.
