### ISSUE TITLE
Add badges in readme

### ISSUE THREAD

**Issue by khushimarothi** [Clueless-Community/seamless-ui#2063]
## What is the motivation for adding/enhancing this feature?
I want to add some cool badges in readme.'
reference img:
![Screenshot (38)](https://user-images.githubusercontent.com/85816852/224222200-f590fd27-f473-4dab-9780-a3cacea4dda1.png)

## Can you complete this feature request by yourself?

- [x] YES

## Additional information

Please assign under JWOC

**Comment by RavindraP04** [comment]
Assigned @khushimarothi
