### ISSUE TITLE
Update Avatar readme 

### ISSUE THREAD

**Issue by RavindraP04** [Clueless-Community/seamless-ui#2067]
Need to improve this component on `Avatar/README.md`

## Improvements required :
On clicking the image in the readme its redirecting to the wrong component code so either swap the images to their corresponding component link or vice versa
  
You can checkout [this](https://github.com/Clueless-Community/seamless-ui/blob/main/Avatar/README.md) one for better understanding.

**Comment by SakshiShah29** [comment]
I would like to work on this issue.

**Comment by animesh156** [comment]
can i work on this one under JWOC?

**Comment by SakshiShah29** [comment]
Hey @RavindraP04. I looked into the issue but I found that the images are redirecting the correct code file upon clicking.
