### ISSUE TITLE
Improve Avatar Group

### ISSUE THREAD

**Issue by RavindraP04** [Clueless-Community/seamless-ui#2068]
Need to improve this component on `Avatar/src/avatar-group.html`

## Improvements required :
Make the width fit of the new followers section
## Any reference image?
![image](https://user-images.githubusercontent.com/98400348/224538893-c9356503-5880-496a-a3c6-1b3c88e4b8e5.png)
  

You can checkout [this](https://github.com/Clueless-Community/seamless-ui/blob/main/Avatar/src/avatar-group.html) one for better understanding.

**Comment by SakshiShah29** [comment]
I would like to work on this issue
