### ISSUE TITLE
Improve Badges Readme

### ISSUE THREAD

**Issue by RavindraP04** [Clueless-Community/seamless-ui#2069]
Need to improve this component on `Badges/README.md`

## Improvements required :
Update the images in the readme so that there is no black space in the cell like it is now in the badge 1 image, all the cells should be properly fill and for this you need to take the screenshot of the component in a constant aspect ratio

## Any reference image?
![image](https://user-images.githubusercontent.com/98400348/224539434-68d21ce1-5dc7-4157-adf0-0f55f82d84ce.png)
  
You can checkout [this](https://github.com/Clueless-Community/seamless-ui/blob/main/Badges/README.md) one for better understanding.

**Comment by SakshiShah29** [comment]
I would like to work on this issue

**Comment by Nabhya024** [comment]
I would like to work on this issue
