### ISSUE TITLE
Improve Breadcrumb

### ISSUE THREAD

**Issue by RavindraP04** [Clueless-Community/seamless-ui#2071]
Need to improve this component on `Breadcrumb/src/Breadcrumb.html`

## Improvements required :
Make working Breadcrumb i.e. when the user clicks on any menu[Dashboard, Components, Breadcrumbs], the bg color of that particular menu should change to blue-600 and text white and only one menu can remain active at a time, By active I mean only one option in the breadcrumb should have bg-blue-600 and text-white when it is clicked and others should be in their default state

## Any reference image?
![image](https://user-images.githubusercontent.com/98400348/224540300-eada41c9-977d-4391-81c8-132a26d18deb.png)
  
You can checkout [this](https://github.com/Clueless-Community/seamless-ui/blob/main/Breadcrumb/src/Breadcumb.html) one for better understanding.

**Comment by Awesomeasma** [comment]
@RavindraP04 
I would like to work on this under JWOC
