### ISSUE TITLE
Improve Testimonial 1 black

### ISSUE THREAD

**Issue by RavindraP04** [Clueless-Community/seamless-ui#2073]
Need to improve this component on `Testimonials/src/Testimonial-1-black.html`

## Improvements required :
THe image is not rendering in the component so replace the link of the image of the user, you can get the image from the [figma](https://www.figma.com/file/qzwugAfEB1GL4FgWXw9R3Z/SeamLess-UI-Dev?node-id=0%3A1&t=BiMFbTm2G3EeAZEk-0)

## Any reference image?
![image](https://user-images.githubusercontent.com/98400348/224542809-c431cf73-c086-4527-a774-aa995d54d28f.png)
  
You can checkout [this]() one for better understanding.

**Comment by SHYALI** [comment]
I want to work on this issue under JWOC

**Comment by Awesomeasma** [comment]
I would like to work on this under JWOC

**Comment by Laxmankohar** [comment]
Hey @RavindraP04 , I would like to work on this issue under jwoc. can you assign it to me?
