### ISSUE TITLE
Improve Testimonial 1 Blue

### ISSUE THREAD

**Issue by RavindraP04** [Clueless-Community/seamless-ui#2074]
Need to improve this component on `Testimonials/src/Testimonial-1-blue.html`

## Improvements required :
The image is not rendering in the component so replace the link of the image of the user, you can get the image from the [figma](https://www.figma.com/file/qzwugAfEB1GL4FgWXw9R3Z/SeamLess-UI-Dev?node-id=0%3A1&t=BiMFbTm2G3EeAZEk-0)

## Any reference image?
![image](https://user-images.githubusercontent.com/98400348/224542998-3a9d3ad9-642c-4a77-99f8-43b8f21f28a2.png)

You can checkout [this]() one for better understanding.

**Comment by Laxmankohar** [comment]
@RavindraP04 bro, i want to work on this issue under jwoc. Can you assign it to me?

**Comment by charu1603** [comment]
I would like to contribute on this issue

**Comment by Awesomeasma** [comment]
I would like to work on this under JWOC

**Comment by Saishreekouda** [comment]
I would like to work on this issue

**Comment by Laxmankohar** [comment]
![image](https://user-images.githubusercontent.com/73365025/224997661-33dbba5a-3853-42bc-8afb-b0715402270e.png)

@RavindraP04 bro, Is it ok?
