### ISSUE TITLE
Improve Testimonial 1 white

### ISSUE THREAD

**Issue by RavindraP04** [Clueless-Community/seamless-ui#2075]
Need to improve this component on `Testimonials/src/Testimonial-1-white.html`

## Improvements required :
THe image is not rendering in the component so replace the link of the image of the user, you can get the image from the [figma](https://www.figma.com/file/qzwugAfEB1GL4FgWXw9R3Z/SeamLess-UI-Dev?node-id=0%3A1&t=BiMFbTm2G3EeAZEk-0)

## Any reference image?
![image](https://user-images.githubusercontent.com/98400348/224543048-c4cd65b6-23ed-4733-a63f-86e76e02f0f7.png)
  
You can checkout [this](https://github.com/Clueless-Community/seamless-ui/blob/main/Testimonials/src/testimonial-1-white.html) one for better understanding.

**Comment by Awesomeasma** [comment]
I would like to work on this under JWOC

**Comment by Naveen-7000** [comment]
@RavindraP04  i would like to work on this issue could you please assign it to me . I will optimise the image and fix the issue.

**Comment by RavindraP04** [comment]
@Naveen-7000

**Comment by Naveen-7000** [comment]
@RavindraP04 I have raised a PR please look through it and give feedback if any changes are required.

**Comment by Naveen-7000** [comment]
@RavindraP04  need feedback
