### ISSUE TITLE
[UI Bug] - Website theme selector is missing left padding

### ISSUE THREAD

**Issue by AbirSantra** [Clueless-Community/seamless-ui#2178]
## Current behavior

Hi, currently in the live version of the website, the theme selector has no left padding which I believe is not intended. Also, the selected 'check mark' icon is overlapping the text. See attached screenshot below:
<br/>
![image](https://user-images.githubusercontent.com/78201921/234061527-8b2b4e9f-f93c-421a-a97f-8877479f7df4.png)

## Expected behavior

I believe there should be sufficient left padding on the theme selector so that the menu looks uniform.

## Steps to reproduce the issue

Open the live website on a desktop browser. Go to Docs page. Click on the theme selector.

## Can you handle fixing this bug by yourself?

- [X] YES
- [ ] NO

## Environment details

- Browser: Brave Browser
- OS: Windows 11
- Code Version: website-prod branch

## Additional information

![image](https://user-images.githubusercontent.com/78201921/234060440-54bd8815-a884-407f-9665-444d6d2d95c4.png)

**Comment by ArslanYM** [comment]
Would love to work on this..

**Comment by nitin-pandita** [comment]
@AbirSantra  Can you please share the file that needs to be updated I can't find it. Thank You

**Comment by ArslanYM** [comment]
@AbirSantra The bug seems to occur because of some other reasons. 
It's working  fine rn
![works](https://user-images.githubusercontent.com/104521101/234754000-8fb469d9-3b8a-40b8-98a5-70ed715e653f.png)

**Comment by nitin-pandita** [comment]
> @AbirSantra The bug seems to occur because of some other reasons. It's working fine rn ![works](https://user-images.githubusercontent.com/104521101/234754000-8fb469d9-3b8a-40b8-98a5-70ed715e653f.png)

No bro its still the same

**Comment by Lakhaninawaz** [comment]
i see this issue in run chrome issue show but i use edge browser it's working properly.

so it's browser depedencies problem.

**Comment by ArslanYM** [comment]
@AbirSantra This error doesnt exist of mozilla and chrome browser. I have noticed this on brave for now

**Comment by Rajdip019** [comment]
It's fixed now. So Closing the issue.
