### ISSUE TITLE
Improve Content

### ISSUE THREAD

**Issue by ArslanYM** [Clueless-Community/seamless-ui#2184]
I noticed a bunch of hints whenever links are provided in the documentation. i.e. : (opens in a new tab)

## Improvements required :
There is no need for those hints and they just make the docs look unprofessional 

## Example:
![why](https://user-images.githubusercontent.com/104521101/234754510-f4d91e29-74ae-4c21-873d-d091b98ddc1f.png)

**Comment by nitin-pandita** [comment]
@ArslanYM  Can you please share a full screen shot

**Comment by ArslanYM** [comment]
![here](https://user-images.githubusercontent.com/104521101/234830596-f98e40ca-abe0-4661-8d49-1c67cd4cbdef.png)
@nitin-pandita  Here you go nitin

**Comment by Rajdip019** [comment]
This one is required as we are using tailwind CSS in the whole UI library. @nitin-pandita
