### ISSUE TITLE
Incorrect Link text - "Tailwind Git" in Tutorial.md 

### ISSUE THREAD

**Issue by Santhoshmani1** [Clueless-Community/seamless-ui#2190]
# Issue 
In the ***Tutorial.md File***, The link text to the Tailwind CSS repository is incorrectly written as Tailwind Git. 

## change required 
 The link text should be changed from **Tailwind Git** to **Tailwind CSS repository** 

## Image 
  

> @#![IMG_20230430_125655](https://user-images.githubusercontent.com/119673958/235341177-cabfda4e-5bcb-47b8-a6ae-e646e4d8f8d7.jpg)

- I would like to work on this issue if any of the member permits and assign me the issue

**Comment by Rajdip019** [comment]
It's fixed now so closing the issue.
