### ISSUE TITLE
Responsive problem

### ISSUE THREAD

**Issue by Lakhaninawaz** [Clueless-Community/seamless-ui#2192]
## Current behavior
scroll x axis in small size mobile device. 

## Expected behavior
don't scroll in small size. 

## Steps to reproduce the issue
change or add media query in css file.
add only scrolling in particular div.

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ ] NO

## screenshot

![Screenshot_20230430-140255_Chrome](https://user-images.githubusercontent.com/85409388/235345758-1c62ce8a-63de-4d55-ae76-6aa8357d2122.jpg)

**Comment by Rajdip019** [comment]
@RavindraP04 is fixing them for Version 1

**Comment by Lakhaninawaz** [comment]
How can i contribute with this project?

**Comment by Rajdip019** [comment]
We will be raising some issues in next 3 - 4 days. Check for them. @Lakhaninawaz

**Comment by Lakhaninawaz** [comment]
Ok i am waiting!
