### ISSUE TITLE
[WEBSITE] - Add Mobile Navbar in website

### ISSUE THREAD

**Issue by RavindraP04** [Clueless-Community/seamless-ui#2231]
# Add working Hamburger menu in Navbar for the Mobile version of the website 

## Instructions 
- You can get the code of the website in `website-dev` branch 
- After making changes, Push the changes to `website-dev` branch 
- You will find the code of all the components [here](https://github.com/Clueless-Community/seamless-ui/blob/website-dev/components/Navbar.tsx)
- For the mobile screen change the navbar and add Hamburger Menu Button Like this 👇

### Currently This is how it looks in mobile 
<img align="left" width="350" src="https://user-images.githubusercontent.com/98400348/236843503-b5a69f58-d362-419f-9eaa-8717e6774713.png" />

<img align="right" width="350" src="https://user-images.githubusercontent.com/98400348/236843141-68cdff68-7e9f-4e5f-8a21-8454ba2d4af6.png" />

**Comment by mani200307** [comment]
I would like to work on this, Could you assign me this issue?

**Comment by mani200307** [comment]
@RavindraP04 I would like to work on this, Could you assign me this issue?

**Comment by pooranjoyb** [comment]
Would like to take this opportunity to create an animated Hamburger Menu. Would be glad if you'd assign me this issue. @RavindraP04
