### ISSUE TITLE
[WEBSITE] - Fix image size in Web component

### ISSUE THREAD

**Issue by RavindraP04** [Clueless-Community/seamless-ui#2233]
# Fix image size on mobile screen (360px)

## Instructions 
- You can get the code of the website in `website-dev` branch 
- After making changes, Push the changes to `website-dev` branch 
- You will find the code of this components [here](https://github.com/Clueless-Community/seamless-ui/blob/website-dev/components/Web.tsx)
- For the mobile screen change the size of image in the card at 360px 👇

### Currently This is how it looks in mobile 
<img align="left" width="350" src="https://user-images.githubusercontent.com/98400348/236858291-ee0c5dd9-0a21-4171-90a8-ac8ab8c008c1.png" />

<img align="right" width="350" src="https://user-images.githubusercontent.com/98400348/236858104-27b0f3ed-bfc6-470d-bf39-c0f388b2e815.png" />

**Comment by codescalper** [comment]
Hey, I would love to work on this :) 
could you assign it to me ?

**Comment by RavindraP04** [comment]
Hey @codescalper, Any update ?

**Comment by codescalper** [comment]
![image.png](https://github.com/Clueless-Community/seamless-ui/assets/92156721/807b2be4-10b4-40ef-b09a-92860133c725)


I have setup the project locally just figuring it out just need a day beacuse tomorrow is my exam i know reason is quite silly but, assuring you will complete it by tomorrow night :)

**Comment by RavindraP04** [comment]
@codescalper Ok, No issue

**Comment by codescalper** [comment]
@RavindraP04 needed some help 
`<img src='/web3.png' className='w-full md:w-[270px]' draggable={false} />
<div className='bg-white rounded-b-xl w-full md:w-[270px] '>` will this work ?

i tried using multiple solution but didn' work aslo just one question the solution will be applied on just img tag?
original : `<img src='/web3.png' className='md:w-[270px]' draggable={false} />`

**Comment by codescalper** [comment]
Hey @RavindraP04 , will this work?

https://github.com/Clueless-Community/seamless-ui/assets/92156721/0a1acaf6-9f50-48e7-a959-659c1078c14b

**Comment by RavindraP04** [comment]
Looks Good! Great Work @codescalper
