### ISSUE TITLE
[WEBSITE] - Fix Footer Responsiveness

### ISSUE THREAD

**Issue by RavindraP04** [Clueless-Community/seamless-ui#2239]
# Fix Product Section mobile screen (360px)
- Give some vertical gaps between the menu as shown in right side image
- Change the social handle icon color
- Make it Responsive for Tab devices

## Instructions 
- You can get the code of the website in `website-dev` branch 
- After making changes, Push the changes to `website-dev` branch 
- You will find the code of this components [here](https://github.com/Clueless-Community/seamless-ui/blob/website-dev/components/Footer.tsx)

### Currently This is how it looks in mobile 
<img align="left" width="350" src="https://github.com/Clueless-Community/seamless-ui/assets/98400348/dea7a1b5-6d76-4b24-b48f-76fb603dbcda" />

<img align="right" width="350" src="https://github.com/Clueless-Community/seamless-ui/assets/98400348/5f3046ab-b1c0-4f18-b0f7-33fbe5d0a15c" />

### Make it like this 👉

---

![image](https://github.com/Clueless-Community/seamless-ui/assets/98400348/6a74cf01-5c91-478d-a217-b0a5f4f0a5e6)

**Comment by abhinav2712** [comment]
@RavindraP04  Assign me this issue, I can fix this

**Comment by RavindraP04** [comment]
Assigned @abhinav2712

**Comment by Umesh7Dixit** [comment]
RavindraP04 please assign me this issue i can make this

**Comment by RavindraP04** [comment]
@abhinav2712 Any update ?

**Comment by AmitDeka** [comment]
Can you assign @RavindraP04

**Comment by AmitDeka** [comment]
@RavindraP04 I am working on it , I will push the code by the end of this week.

**Comment by RavindraP04** [comment]
> @RavindraP04 I am working on it , I will push the code by the end of this week.

@AmitDeka Ok, No Issue

**Comment by Dev-anshika98** [comment]
@RavindraP04 , Can you please assign this to me . I can do it

**Comment by RavindraP04** [comment]
Assigned @Dev-anshika98

**Comment by bhavy03** [comment]
@RavindraP04 , I would like to work on this issue
