### ISSUE TITLE
Spelling Error on Site

### ISSUE THREAD

**Issue by LoneStanding** [Clueless-Community/seamless-ui#2255]
## Current behavior

A spelling mistake is there of Bootstrap on the current deployed Website.

![2023-06-24 11_58_20-@This_IS_Avik - Discord](https://github.com/Clueless-Community/seamless-ui/assets/92737430/467e0f96-0e97-4e1e-9728-d585fe5d0fed)

## Expected behavior

The spelling should be changed to **Bootstrap**

![2023-06-24 11_58_20-@This_IS_Avik - Discord Edited](https://github.com/Clueless-Community/seamless-ui/assets/92737430/275cde56-a2b4-4341-afa5-030ebf2a8a4a)

## Source 
The image for this can be found in the `website-dev` branch [https://github.com/Clueless-Community/seamless-ui/blob/website-dev/public/Group%20271.png](url) and [https://github.com/Clueless-Community/seamless-ui/blob/website-dev/public/Group%20ui.png](url)

## Can you handle fixing this bug by yourself?

- [x] YES
- [ ] NO

## Environment details

- Browser:  Chrome Version 114.0.5735.134 (Official Build) (64-bit)
- OS:  Microsoft Windows 11 Home Single Language
- Code Version:  ec5d2c10a2cab305e10dc9da544e695dea3807d9

**Comment by Rajeevjewar** [comment]
Hello, I also look this issue in website if this is not assign to someone other then please assign it to me because I want to work on it.

**Comment by Dev-anshika98** [comment]
Sir @LoneStanding can u please assign this to me, I want to work on this

**Comment by bhavy03** [comment]
Sir @LoneStanding would you please assign this issue to me as I am just getting started with open source and it would be helpful if you assign it to me

**Comment by Rohxn16** [comment]
I wanna work on this issue.

**Comment by Adidem23** [comment]
Please Assign this issue to me @LoneStanding
