### ISSUE TITLE
Overflow X at 1024px

### ISSUE THREAD

**Issue by Mehaksharma6** [Clueless-Community/seamless-ui#2276]
## Current behavior

Screen Overflow X is happening at 1024 px and below because of the maintainer curved line

![image](https://github.com/Clueless-Community/seamless-ui/assets/133729421/6612c0ca-59d9-4eb2-bb49-4c109cf74abc)

### For larger screen size
![image](https://github.com/Clueless-Community/seamless-ui/assets/133729421/45178069-b43b-450d-ade9-2da6a7c8a99f)

Line is hidden between the image of maintainers and meet the maintainers text from screen size md to lg

![image](https://github.com/Clueless-Community/seamless-ui/assets/133729421/1ecae90d-162e-406f-bafd-33d5d961a08f)

**Comment by Mehaksharma6** [comment]
Please assign this issue to me

**Comment by RavindraP04** [comment]
Go ahead @Mehaksharma6
