### ISSUE TITLE
Bug in Visit Clueless Button

### ISSUE THREAD

**Issue by Antanukumar** [Clueless-Community/seamless-ui#2288]
## Current behavior

The `Visit Clueless` button in the bottom of the home page above the footer is behaving weirdly, the button is working even if it is clicked approx 20px upper side or in the down side, 

## Expected behavior

The button should redirect to Clueless website when only clicked on the button and not anywhere else

## Steps to reproduce the issue

Just hover over the top and bottom side of the button but not on the button, you will see the cursor pointer gets kicked in and if you click at this point, it redirects to the Clueless website 
![image](https://github.com/Clueless-Community/seamless-ui/assets/106733685/adceb401-d558-4a15-8e67-974a7674078e)

## Can you handle fixing this bug by yourself?

- [X] YES

**Comment by RavindraP04** [comment]
Go ahead @Antanukumar
