### ISSUE TITLE
Typo error in CONTRIBUTING.md

### ISSUE THREAD

**Issue by manavb2214** [Clueless-Community/seamless-ui#2302]
I found a typo error in the provided CONTRIBUTING.md file:

'componet' should be changed to 'component'.

The line  -  "Build the UI componet using `HTML` and `Tailwind CSS`."  should be changed to: -

"Build the UI component using `HTML` and `Tailwind CSS`."

**Comment by RavindraP04** [comment]
Thanks for noticing but I guess it was fixed in #2304

**Comment by manavb2214** [comment]
Okk!!! Thanks 😄
