### ISSUE TITLE
Create a Navbar-19

### ISSUE THREAD

**Issue by Rajdip019** [Clueless-Community/seamless-ui#598]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
![navbar 19](https://user-images.githubusercontent.com/91758830/198709104-f5c1ece4-d8b8-4755-89fa-b7a4c881b48e.png)

After building the component please raise a PR with a screenshot of the component and add the component in `Navbar/navbar-19.html`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by Mayureshkaulwar** [comment]
Assign to me

**Comment by issue31** [comment]
Please assign this issue to me.

**Comment by issue31** [comment]
Hey @Rajdip019, please merge the pull request #651  for this issue. I apologize for the delay in submitting the required code to solve this issue.
