### ISSUE TITLE
Create Desktop_filter_style_2

### ISSUE THREAD

**Issue by AKACHI-4** [Clueless-Community/seamless-ui#650]
Hey, 
I want to create a Desktop_filter named as filter_style_4 in [Figma](https://www.figma.com/file/0eqV7t3UKKM14UeqCSfOZb/Essential-UI---Figma-Ui-Kit-(Community)?node-id=688%3A4081) using the following sources : 
For Component - [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.
For Icons - [Hero Icons](https://heroicons.com/)

### Reference Image
![Capture](https://user-images.githubusercontent.com/99159580/199530265-7ada7fe5-cc10-4111-b423-332572f17fdd.PNG)

Kindly assign it to me. 

Thanks ❤

**Comment by Rajdip019** [comment]
Go ahead @AKACHI-4
