### ISSUE TITLE
Improve rating

### ISSUE THREAD

**Issue by Rajdip019** [Clueless-Community/seamless-ui#655]
Need to improve this component on `\Rating\src\rating-1.html`

## Improvements required :
Need to make 3 versions of this. 
`sm` - `w-5 and h-5`
`md` - `w-7 h-7`
`lg` - `w-9  h-9`

## Any reference image?
No
  
## Any external reference?

Check out this `button` component to get a understanding how to make the file. [Button component](https://github.com/Clueless-Community/seamless-ui/blob/main/Buttons/src/Primary/text-button.html)

**Comment by 1ananya3** [comment]
I want to work on this. Please assign me

**Comment by Rajdip019** [comment]
You are already assigned to an issue. @1ananya3

**Comment by Hirenachhaada** [comment]
Do i have to make three more HTML file in record section and add these version in the class or something else is to be done

**Comment by Rajdip019** [comment]
Yes. make 3 different one. Do you like to work on it. @Hirenachhaada

**Comment by Hirenachhaada** [comment]
Sir please confirm 3 different one means 3 div itself in rating1 file
I would like to work on it

**Comment by itz-deepak** [comment]
please assign this to me

**Comment by DarK-VEnOM-16** [comment]
@Rajdip019  I want to work on this issue.
Please assign this issue to me

**Comment by Rajdip019** [comment]
> Sir please confirm 3 different one means 3 div itself in rating1 file
> I would like to work on it
> 

Check the rating-2.html file in the same folder. You need to make the structure exactly the same.

**Comment by Hirenachhaada** [comment]
Sir please assign the issue

**Comment by Rajdip019** [comment]
GO ahead @Hirenachhaada

**Comment by Hirenachhaada** [comment]
![image](https://user-images.githubusercontent.com/95188259/205583417-4efb7a67-8e69-4747-adfd-b05662d08e69.png)
is it correct sir @Rajdip019

**Comment by Rajdip019** [comment]
This is perfect just add comments on the different div like small, medium, large and make a PR. @Hirenachhaada

**Comment by Hirenachhaada** [comment]
ok sir

**Comment by Hirenachhaada** [comment]
@Rajdip019 sir, please merge the PR

**Comment by Rajdip019** [comment]
Merged! Great work @Hirenachhaada
