### ISSUE TITLE
Improve rating 2

### ISSUE THREAD

**Issue by Rajdip019** [Clueless-Community/seamless-ui#656]
Need to improve this component on `\Rating\src\rating-2.html`

## Improvements required :
Need to make 3 versions of this. 
`sm` - `w-5 and h-5`
`md` - `w-7 h-7`
`lg` - `w-9  h-9`

And also need to change the text size according to that.

## Any reference image?
No
  
## Any external reference?

Check out this `button` component to get a understanding how to make the file. [Button component](https://github.com/Clueless-Community/seamless-ui/blob/main/Buttons/src/Primary/text-button.html)

**Comment by Swap-nil-2003** [comment]
@Rajdip019 may I work on this issue?

**Comment by Rajdip019** [comment]
Yes go ahead. @Swap-nil-2003

**Comment by Swap-nil-2003** [comment]
PR for issue in #664

**Comment by Rajdip019** [comment]
This is finished. Thanks for the contribution.

**Comment by Swap-nil-2003** [comment]
Cheers!! @Rajdip019
