### ISSUE TITLE
Make design system for Badges

### ISSUE THREAD

**Issue by Rajdip019** [Clueless-Community/seamless-ui#657]
Make and awesome design system for `Badges` Component.

See the [Badges](https://github.com/Clueless-Community/seamless-ui/tree/main/Badges/src) and make one.

Refer to : [Button Design System for any reference](https://github.com/Clueless-Community/seamless-ui/blob/main/Buttons/buttons.design-system.mdx) or ask me in any confusion.

Tip : 
You can use [Tailwind Playground](https://play.tailwindcss.com/)

**Comment by pranavajith** [comment]
@Rajdip019 I'd like to take up this issue..
Also could you give it the intermediate label as well? It seems to be missing.

**Comment by pranavajith** [comment]
Can I start out with #558 first? So that I have a good transition into tailwind?

**Comment by itz-deepak** [comment]
@Rajdip019 plz assign this issue to me

**Comment by Rajdip019** [comment]
Sure go ahead @itz-deepak

**Comment by itz-deepak** [comment]
I made this badges that can be used on icons
Is it good
![image](https://user-images.githubusercontent.com/83635276/205641947-ba121183-95d3-4fba-8281-eac1e2410df4.png)

**Comment by Rajdip019** [comment]
You don't need to make badges. You need to make the design system for the badges which are already built. Refer to the description of the issue.

**Comment by itz-deepak** [comment]
Still confused
Do I have to make a file for badge design like the reference file of button design?

**Comment by Rajdip019** [comment]
No you need to make a design system basically write a readme. Which developers can follow to make the same type of components. And will follow the same set of rules. @itz-deepak
