### ISSUE TITLE
Make design system for Alerts

### ISSUE THREAD

**Issue by Rajdip019** [Clueless-Community/seamless-ui#658]
Make and awesome design system for `Alerts` Component.

See the [Alerts](https://github.com/Clueless-Community/seamless-ui/tree/main/Alerts/src) and make one.

Refer to : [Button Design System for any reference](https://github.com/Clueless-Community/seamless-ui/blob/main/Buttons/buttons.design-system.mdx) or ask me in any confusion.

Tip : 
You can use [Tailwind Playground](https://play.tailwindcss.com/)

**Comment by AmitDeka** [comment]
Can you assign me?

**Comment by Rajdip019** [comment]
Sure go ahead @AmitDeka

**Comment by AmitDeka** [comment]
Can I contact you on LinkedIn for any confusion ?

**Comment by Rajdip019** [comment]
You can just ask your queries on ClueLess Discord Server or CodePeak discord Server. @AmitDeka

**Comment by AmitDeka** [comment]
@Rajdip019  assign this issue to someone else

**Comment by Rajdip019** [comment]
@srilakshmiv123 you can now work on this issue.

**Comment by Rajdip019** [comment]
@srilakshmiv123 are you working on this?

**Comment by ankushj0801** [comment]
Can I work on this issue? @Rajdip019

**Comment by Rajdip019** [comment]
Sure @ankushj0801

**Comment by aradhya-10** [comment]
Can I work on this issue? @Rajdip019 
Unless someone else is done with it.

**Comment by Rajdip019** [comment]
Do it. @aradhya-10

**Comment by Rajdip019** [comment]
It's already done. @aradhya-10
