### ISSUE TITLE
Fix avatar-status.html

### ISSUE THREAD

**Issue by Rajdip019** [Clueless-Community/seamless-ui#667]
One need to fix the Avatar design and make the avatars look like the Avatars in the page.

The height and width will be `h-20 w-20` and use the images used in [this one](https://github.com/Clueless-Community/seamless-ui/tree/main/Avatar/src/avatar-group.html).

For any queries just tag me and comment down below or use our discord server for fast replies.

**Comment by Rajdip019** [comment]
Go ahead. @shivamkgpian

**Comment by shivamkgpian** [comment]
![image](https://user-images.githubusercontent.com/83865497/205619588-d49691bb-1ba4-496c-b65e-c3ccd377c5e3.png)

Can you please confirm @Rajdip019, is this ok?

**Comment by Rajdip019** [comment]
Looks amazing make a PR for this. @shivamkgpian

**Comment by RavindraP04** [comment]
@Rajdip019 the first icon is drop down icon for checking the user status so it should be small in size, Right ?

**Comment by RavindraP04** [comment]
I have raised a PR for this, Do Checkout. @Rajdip019

**Comment by Rajdip019** [comment]
This issue is closed.
