### ISSUE TITLE
Fix avatar-text.html

### ISSUE THREAD

**Issue by Rajdip019** [Clueless-Community/seamless-ui#668]
One need to fix the Avatar design and make the avatars look like the Avatars in the page.

The height and width will be `h-20 w-20` and use the images used in [this one](https://github.com/Clueless-Community/seamless-ui/tree/main/Avatar/src/avatar-group.html).

For any queries just tag me and comment down below or use our discord server for fast replies. And make the text size according to that.

**Comment by imakshatgupta** [comment]
I have fixed it

**Comment by imakshatgupta** [comment]
But not able to push to github

**Comment by Hirenachhaada** [comment]
![image](https://user-images.githubusercontent.com/95188259/205591843-fd4bb19e-0c85-42a1-a261-f7e0f957b166.png)
is this the thing we are required to do

**Comment by Rajdip019** [comment]
Merged this one, but make sure to not raise a PR until you are assigned to that issue. @RavindraP04
