### ISSUE TITLE
Make design system for Breadcrumbs

### ISSUE THREAD

**Issue by Rajdip019** [Clueless-Community/seamless-ui#674]
Make and awesome design system for `Breadcrumbs` Component.

See the [Breadcrumbs](https://github.com/Clueless-Community/seamless-ui/blob/main/Breadcrumb/src/Breadcumb.html) and make one.

Refer to : [Button Design System for any reference](https://github.com/Clueless-Community/seamless-ui/blob/main/Buttons/buttons.design-system.mdx) or ask me in any confusion.

Tip : 
You can use [Tailwind Playground](https://play.tailwindcss.com/)

**Comment by Kumar-Ankit56** [comment]
@Rajdip019 please assign me I would love to work on the issue.

**Comment by RavindraP04** [comment]
@Rajdip019  **How does this look ?**
![image](https://user-images.githubusercontent.com/98400348/205659219-d2d4cc7d-32e7-4ef4-a9b2-9fc0c406a7fb.png)

**Comment by RavindraP04** [comment]
Made Few Changes. How is this one ? @Rajdip019 
On Hover it changes white shadow to a little dark shade.
![Screenshot_20221205_213717](https://user-images.githubusercontent.com/98400348/205685163-f629ace0-d231-4dee-9ad0-f46df8ce0c83.png)

**Comment by Rajdip019** [comment]
You need to make a design system for the breadcrumbs. But the first one looks good you can raise an issue @RavindraP04 that create breadcrumb 2. And then you can make a PR for this.

**Comment by Rajdip019** [comment]
@Kumar-Ankit56 you can go ahead.

**Comment by Kumar-Ankit56** [comment]
> @Kumar-Ankit56 you can go ahead.

Thanks

**Comment by RavindraP04** [comment]
> You need to make a design system for the breadcrumbs. But the first one looks good you can raise an issue @RavindraP04 that create breadcrumb 2. And then you can make a PR for this.

@Rajdip019 Can you please elaborate, what do you mean by Design System ? I am unable to understand.

**Comment by RavindraP04** [comment]
> You need to make a design system for the breadcrumbs. But the first one looks good you can raise an issue @RavindraP04 that create breadcrumb 2. And then you can make a PR for this.

@Rajdip019 
Ok, Now I understood that by Design System you meant to create mdx file like you mentioned for the button, 
Btw, In the new issue I need to make a new file breadcrumb-2.html and then raise the PR for that, Right ?

**Comment by RavindraP04** [comment]
> You need to make a design system for the breadcrumbs. But the first one looks good you can raise an issue @RavindraP04 that create breadcrumb 2. And then you can make a PR for this.

@Rajdip019 I have raised the issue an also PR #677 
I have created new file `Breadcrumb/src/Breadcrumb-2.html` and have added the code in that.
Do, Checkout.
