### ISSUE TITLE
Create a Rounded Primary Button

### ISSUE THREAD

**Issue by Rajdip019** [Clueless-Community/seamless-ui#678]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
You need to follow the design system of the button ➡️ [Button Design system](https://github.com/Clueless-Community/seamless-ui/blob/main/Buttons/buttons.design-system.mdx)

Make the rounded version of this [Primary Button](https://github.com/Clueless-Community/seamless-ui/blob/main/Buttons/src/Primary/text-button.html)

After building the component please raise a PR with a screenshot of the component and add the component in `Button/src/Primary/text-button-rounded.html`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by N-KATHYAYAN** [comment]
May I work on it ?

**Comment by pranavjainjs** [comment]
I'd like to work on it. Please assign the task to me.

**Comment by Rajdip019** [comment]
Go ahead @N-KATHYAYAN

**Comment by N-KATHYAYAN** [comment]
is this fine ?
<img width="1053" alt="Screenshot 2022-12-06 at 9 27 24 PM" src="https://user-images.githubusercontent.com/113281305/205960995-3c11d003-7c4d-444a-9e00-8c6a80b2de05.png">

**Comment by nik132-eng** [comment]
If this problem isn't resolved, I'd like to get involved. please assign me this issue.

**Comment by Rajdip019** [comment]
Hey, @N-KATHYAYAN do you want to pair up with @nik132-eng to solve this one?

**Comment by Rajdip019** [comment]
Sure.

**Comment by nik132-eng** [comment]
I didn't use Tailwind css before can i take little amount of time for learn?

**Comment by nik132-eng** [comment]
Is this Right? 

![image](https://user-images.githubusercontent.com/77881638/206117178-ca835edd-ceec-468a-bdc8-ecbb2d61fdfa.png)

Followed this guideline.

![image](https://user-images.githubusercontent.com/77881638/206117368-36e4fb8e-6e38-4a86-9ea1-bc78ffdebbe3.png)

**Comment by Rajdip019** [comment]
Yeah these seems good.
