### ISSUE TITLE
Create a text icon rear button rounded

### ISSUE THREAD

**Issue by Rajdip019** [Clueless-Community/seamless-ui#679]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
You need to follow the design system of the button ➡️ [Button Design system](https://github.com/Clueless-Community/seamless-ui/blob/main/Buttons/buttons.design-system.mdx)

Make the rounded version of this [Primary Button Text Rear](https://github.com/Clueless-Community/seamless-ui/blob/main/Buttons/src/Primary/text-icon-rear-button.html)

After building the component please raise a PR with a screenshot of the component and add the component in `Button/src/Primary/text-icon-rear-button-rounded.html`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by itz-deepak** [comment]
assign this to me @Rajdip019

**Comment by Rajdip019** [comment]
Sure go ahead. @itz-deepak

**Comment by itz-deepak** [comment]
I have made the rounded version
Is it good
![image](https://user-images.githubusercontent.com/83635276/205844334-d9491fee-c16b-4abd-8abb-6ad0d00bc87b.png)

**Comment by Rajdip019** [comment]
It looks awesome. @itz-deepak
