### ISSUE TITLE
Create a rounded text-icon-rear-button.html

### ISSUE THREAD

**Issue by Rajdip019** [Clueless-Community/seamless-ui#680]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
You need to follow the design system of the button ➡️ [Button Design system](https://github.com/Clueless-Community/seamless-ui/blob/main/Buttons/buttons.design-system.mdx)

Make the normal version of this [Secondary Button](https://github.com/Clueless-Community/seamless-ui/blob/main/Buttons/src/Secondary/text-icon-rear-button.html)

After building the component please raise a PR with a screenshot of the component and add the component in `Button/src/Secondary/text-icon-rear-button.html`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by pranavjainjs** [comment]
I'd like to work on this issue.

**Comment by Rajdip019** [comment]
Sure go ahead. @pranavjainjs

**Comment by pranavjainjs** [comment]
![Untitled](https://user-images.githubusercontent.com/95164530/205987970-b0265cb0-60c9-4830-bc38-2f59a028a104.png)

I came up with this design. Let me know if you need any modifications.

**Comment by Rajdip019** [comment]
This looks good but you don't need to come up with any design. Just go here `Button/src/Secondary/text-icon-rear-button.html` and make a rounded version of it. 

Make the rouded-full and that will be okay I guess. @pranavjainjs

**Comment by pranavjainjs** [comment]
I have completed the task and made a pull request.
