### ISSUE TITLE
Time-Line Component

### ISSUE THREAD

**Issue by Kumar-Ankit56** [Clueless-Community/seamless-ui#685]
## What is the motivation for adding/enhancing this feature?
This is will fully pledge UI build on the HTML and Tailwind as we have seen many developer used this component to show their progress journey track. So I thought to add this feature to your repo

## Additional information
Please refer to this image this is something final thing will look like.

![Screenshot (44)](https://user-images.githubusercontent.com/73521123/205887291-7f909a94-016a-4a20-96b3-196450fad377.png)

**Comment by RavindraP04** [comment]
@Kumar-Ankit56 if you are not working on this, then I would like to work on this feature.

**Comment by Kumar-Ankit56** [comment]
> @Kumar-Ankit56 if you are not working on this, then I would like to work on this feature.

sorry to say buddy I'm on it.
You can try some different design of tailwind

**Comment by RavindraP04** [comment]
> > @Kumar-Ankit56 if you are not working on this, then I would like to work on this feature.
> 
> sorry to say buddy I'm on it. You can try some different design of timeline

Ok, No problem.

**Comment by Rajdip019** [comment]
Work on it. @Kumar-Ankit56  and add make a new folder called `others` and inside that just make a file called timeline-component.html and push the code. @Kumar-Ankit56

**Comment by Kumar-Ankit56** [comment]
> Work on it. @Kumar-Ankit56 and add make a new folder called `others` and inside that just make a file called timeline-component.html and push the code. @Kumar-Ankit56

sure
