### ISSUE TITLE
Create a text-button-rounded.html Secondary

### ISSUE THREAD

**Issue by Rajdip019** [Clueless-Community/seamless-ui#686]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
You need to follow the design system of the button ➡️ [Button Design system](https://github.com/Clueless-Community/seamless-ui/blob/main/Buttons/buttons.design-system.mdx)

Make the normal version of this [Secondary Button text rounded](https://github.com/Clueless-Community/seamless-ui/blob/main/Buttons/src/Secondary/text-button.html)

After building the component please raise a PR with a screenshot of the component and add the component in `Button/src/Secondary/text-button-rounded.html`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by Rajdip019** [comment]
Sure go ahead. @RavindraP04

**Comment by RavindraP04** [comment]
![Screenshot_20221206_170610](https://user-images.githubusercontent.com/98400348/205901366-66ee935c-20c6-4b05-ba13-b57799a67b72.png)

Is it ok ? @Rajdip019

**Comment by RavindraP04** [comment]
Hey, @Rajdip019
In the Design System Documentation, I think there is some error, So I'm confused.
![Screenshot_20221206_171117](https://user-images.githubusercontent.com/98400348/205903167-0574a845-df8c-490f-8943-1ead7bc1692c.png)

In the secondary button section `Border Color` code should be `border-blue-600` but its written `bg-blue-600` also it should be written secondary but its written primary

Also I suppose the requirement is just
 `border-blue-600`
`text-blue-600`
On Hover:- `bg-blue-600` & `text-white`
![Screenshot_20221206_172643](https://user-images.githubusercontent.com/98400348/205905687-287f3a55-8dba-4e5b-8074-d8b5f5ec3554.png)

Right ?

**Comment by RavindraP04** [comment]
If all this is correct, then I will make a PR for button design system(for correction) and also for this rounded button issue.
Do let me know @Rajdip019

**Comment by Rajdip019** [comment]
Yeah need to fix that you can raise another issue for that and I will assign you. @RavindraP04

**Comment by RavindraP04** [comment]
> Yeah need to fix that you can raise another issue for that and I will assign you. @RavindraP04

Ok
then I'm making PR for this one.
