### ISSUE TITLE
Create a Toggle Button

### ISSUE THREAD

**Issue by 1ananya3** [Clueless-Community/seamless-ui#692]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

After building the component please raise a PR with a screenshot of the component and add the component in `path of the file`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by 1ananya3** [comment]
Assign this to me @Rajdip019

**Comment by Rajdip019** [comment]
Can you show a picture of the toggle button you want to build? @1ananya3

**Comment by 1ananya3** [comment]
Yeah sure. 
![Screenshot (39)](https://user-images.githubusercontent.com/94430989/206112381-2c327d41-a946-4f62-b290-33ea26e7da63.png)

**Comment by nandita27iitp** [comment]
Please assign this issue to me
