### ISSUE TITLE
Improve nav 22

### ISSUE THREAD

**Issue by Rajdip019** [Clueless-Community/seamless-ui#694]
Need to improve this component on `\Navbar\src\navbar-22.html`

## Improvements required :

Make the required changes according to the [Navbar Design System](https://github.com/Clueless-Community/seamless-ui/blob/main/Navbar/navbar.design-system.mdx) 

The Logo, name and the other design.
  
## Any external reference?
  
You can checkout [this](https://github.com/Clueless-Community/seamless-ui/blob/main/Navbar/src/navbar-0.html) one for better understanding.

**Comment by Tushar98644** [comment]
would like to work on it

**Comment by Rajdip019** [comment]
You are already assigned to an issue.

**Comment by Rajdip019** [comment]
Your previous PR is merged now you can work on this. @nik132-eng
