### ISSUE TITLE
Improve Nav 21

### ISSUE THREAD

**Issue by Rajdip019** [Clueless-Community/seamless-ui#695]
Need to improve this component on `\Navbar\src\navbar-21.html`

## Improvements required :

Make the required changes according to the [Navbar Design System](https://github.com/Clueless-Community/seamless-ui/blob/main/Navbar/navbar.design-system.mdx) 

The Logo, name and the other design.
  
## Any external reference?
  
You can checkout [this](https://github.com/Clueless-Community/seamless-ui/blob/main/Navbar/src/navbar-0.html) one for better understanding.

**Comment by 1ananya3** [comment]
I have done my previous issue. Can you please assign it to me.

**Comment by Rajdip019** [comment]
Sure @1ananya3

**Comment by SusannaJoseph49** [comment]
can u please assign it to me?

**Comment by nandita27iitp** [comment]
Please assign this to me

**Comment by ankushj0801** [comment]
Please assign this issue to me.

**Comment by ankushj0801** [comment]
Please assign me I don't think anyone is working on it. @Rajdip019

**Comment by Rajdip019** [comment]
Sure @ankushj0801 work on it.

**Comment by RavindraP04** [comment]
for reference, you need to make it like this,
Use the input from [form Group ](https://github.com/Clueless-Community/seamless-ui/blob/main/Form%20groups/src/search-filter-category.html) in SeamLess UI and same for button use [this](https://github.com/Clueless-Community/seamless-ui/blob/main/Buttons/src/Primary/text-button-rounded.html)
![Screenshot_20221212_145438](https://user-images.githubusercontent.com/98400348/207011815-698bcf58-9e5d-4bd1-a33f-77334e14a31b.png)
