### ISSUE TITLE
Make a icon-read button for Secondary

### ISSUE THREAD

**Issue by Rajdip019** [Clueless-Community/seamless-ui#698]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
You need to follow the design system of the button ➡️ [Button Design system](https://github.com/Clueless-Community/seamless-ui/blob/main/Buttons/buttons.design-system.mdx)

Make the normal version of this [Secondary Button](https://github.com/Clueless-Community/seamless-ui/blob/main/Buttons/src/Secondary/text-icon-rear-button-rounded.html)

After building the component please raise a PR with a screenshot of the component and add the component in `Button/src/Secondary/text-icon-rear-button.html`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by pranavjainjs** [comment]
I'd like to work on this issue.

**Comment by Rajdip019** [comment]
Sure.

**Comment by pranavjainjs** [comment]
I have made a PR regarding the same.
