### ISSUE TITLE
Create a advance Rating Component

### ISSUE THREAD

**Issue by nik132-eng** [Clueless-Community/seamless-ui#709]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
![image](https://user-images.githubusercontent.com/77881638/206383579-d6b94193-452c-4178-b771-ccade8012866.png)

After building the component please raise a PR with a screenshot of the component and add the component in `seamless-ui/Rating/src`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by nik132-eng** [comment]
Can I work in this?

**Comment by Rajdip019** [comment]
Yeah sure this looks amazing go for `rating-4.html` @nik132-eng
