### ISSUE TITLE
Create a Dark-Headed-Table

### ISSUE THREAD

**Issue by nik132-eng** [Clueless-Community/seamless-ui#712]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
![image](https://user-images.githubusercontent.com/77881638/206399447-de623de1-b6e7-421c-b46d-e8f3e537ed25.png)

After building the component please raise a PR with a screenshot of the component and add the component in `seamless-ui/Tables/src/primary-dark-head-table.html. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by Rajdip019** [comment]
I guess this component is not required. As this is just the same one with a dark heading. @nik132-eng  So closing this.
