### ISSUE TITLE
Create a Hoverable table 

### ISSUE THREAD

**Issue by nik132-eng** [Clueless-Community/seamless-ui#713]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
![image](https://user-images.githubusercontent.com/77881638/206401333-27eee5b0-6347-4857-9454-19e3f66393e9.png)

After building the component please raise a PR with a screenshot of the component and add the component in `seamless-ui/Table/src/hoverable-table.html`. 
  
Hover color: '' background = blue-600 and text = white ''

If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by nik132-eng** [comment]
please assign it to me.

**Comment by Rajdip019** [comment]
The hover effect could be better like. Maybe all text can be white and and a little transition maybe there. @nik132-eng

**Comment by nik132-eng** [comment]
okk Got this
