### ISSUE TITLE
Cool Overlay Image effect.

### ISSUE THREAD

**Issue by Kumar-Ankit56** [Clueless-Community/seamless-ui#721]
## What is the motivation for adding/enhancing this feature?
This is will fully pledge UI build on the HTML and Tailwind as we have seen many developer used this image in the project but they don't wnat to reveal the text in starting phase on content when user hover on it. He get the whole the details of Image.

 
Here is a reference to the component. 
#### Add image here
1st state
![Screenshot (58)](https://user-images.githubusercontent.com/73521123/206522102-e2bb5046-a9a0-4eae-98c9-c21cbece920c.png)

while hover on it image will scale and show the related text 
![Screenshot (59)](https://user-images.githubusercontent.com/73521123/206522162-6f6a6145-6954-48c6-83e1-a7b877cf0410.png)

This is just sample design. Final project will be improved one.

**Comment by devika-singh** [comment]
@Kumar-Ankit56  pls assign me this issue

**Comment by Kumar-Ankit56** [comment]
> @Kumar-Ankit56 pls assign me this issue

Sorry to say buddy I'm on it.

**Comment by Rajdip019** [comment]
This looks amazing but just one thing. See the feature card and button design system and use them to make the design proper of this component and always use a white background. @Kumar-Ankit56

**Comment by Kumar-Ankit56** [comment]
> This looks amazing but just one thing. See the feature card and button design system and use them to make the design proper of this component and always use a white background. @Kumar-Ankit56

sure
