### ISSUE TITLE
Team Section Component

### ISSUE THREAD

**Issue by Kumar-Ankit56** [Clueless-Community/seamless-ui#724]
## What is the motivation for adding/enhancing this feature?
This is will fully pledge UI build on the HTML and Tailwind as we have seen many developers used this image of their team member to with their role in the project. Here Team section is with amazing hover effect.

 
Here is a reference to the component. 
#### Add image here
1st state
![Screenshot (63)](https://user-images.githubusercontent.com/73521123/206563591-8ef8dfad-f166-4e73-9f9e-b6abc82b8350.png)

while hover on its image width will increase and show their name and designation will have rotate effect 
![Screenshot (62)](https://user-images.githubusercontent.com/73521123/206563832-131731db-acce-4e2f-b900-f8d3b3e34e18.png)

This is just sample design. Final project will be improved one.

**Comment by Kumar-Ankit56** [comment]
@Rajdip019 please have a look

**Comment by Rajdip019** [comment]
Make the transition smoother and on hover use a black overlay over the image. @Kumar-Ankit56

**Comment by Kumar-Ankit56** [comment]
> Make the transition smoother and on hover use a black overlay over the image. @Kumar-Ankit56

It is just will cover it up. 
@Rajdip019 please assign me.

**Comment by Rajdip019** [comment]
sure. @Kumar-Ankit56

**Comment by Kumar-Ankit56** [comment]
> sure. @Kumar-Ankit56

Level please

**Comment by Kumar-Ankit56** [comment]
@Rajdip019 all done for this issue, Should I create a new folder with name Team Card Component.  Something else.

**Comment by Rajdip019** [comment]
Name it `Team` and make a new folder in that `src` then make a file `team-01.html`  and add the code. @Kumar-Ankit56
