### ISSUE TITLE
Cool overlay MovieCard Component

### ISSUE THREAD

**Issue by Kumar-Ankit56** [Clueless-Community/seamless-ui#740]
## What is the motivation for adding/enhancing this feature?
This is will fully pledge UI build on the HTML and Tailwind as If you are developer and know about movie API, so you have tried a card to display fetch movie API card. If you're looking for designing the card from scratch, then must use this overlay cool movie card.

 
Here is a reference to the component. 
#### Add image here
1st state
![Screenshot (66)](https://user-images.githubusercontent.com/73521123/206837762-530dbf6e-afed-4521-b4ec-7aeeb45d55a6.png)

while hover on it image will scale and show the related text 
![Screenshot (67)](https://user-images.githubusercontent.com/73521123/206837775-5c9367a2-f7b9-467d-9f0c-ef0bc93dcb7a.png)

This is just sample design. Final project will be improved one.

**Comment by Rajdip019** [comment]
Looks amazing add it into `Others` folder as well.  @Kumar-Ankit56

**Comment by Kumar-Ankit56** [comment]
@Rajdip019 I have a doubt as I'm not able to access Leader from clueless website.
Even I have Login into page.

**Comment by Rajdip019** [comment]
Leader? you can find the leaderboard on codepeak's website. @Kumar-Ankit56

**Comment by Rajdip019** [comment]
ClueLess X Codepeak top contributor list will be out at the end. @Kumar-Ankit56
