### ISSUE TITLE
Create a Multi-level dropdown 

### ISSUE THREAD

**Issue by nik132-eng** [Clueless-Community/seamless-ui#766]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
![image](https://user-images.githubusercontent.com/77881638/207040810-369016ea-5acd-4e6c-b4e1-68f9dc53ba53.png)

After building the component please raise a PR with a screenshot of the component and add the component in `seamless-ui/src/dropdown-3.html`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by Rajdip019** [comment]
Sure. @nik132-eng

**Comment by RavindraP04** [comment]
@Rajdip019 Can you assign this to me ? I have solved it already.

**Comment by Rajdip019** [comment]
Sure go ahead @RavindraP04 and also help @nik132-eng it would be a great learning experience for him as well.

**Comment by RavindraP04** [comment]
> Sure go ahead @RavindraP04 and also help @nik132-eng it would be a great learning experience for him as well.

Ok

**Comment by RavindraP04** [comment]
@nik132-eng Chekout [this](https://github.com/Clueless-Community/seamless-ui/pull/776#issuecomment-1352779564)
