### ISSUE TITLE
Create a Search input

### ISSUE THREAD

**Issue by nik132-eng** [Clueless-Community/seamless-ui#767]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
![image](https://user-images.githubusercontent.com/77881638/207043362-038e7a94-5324-44ea-b6d0-0972c1e4cc35.png)

After building the component please raise a PR with a screenshot of the component and add the component in `seamless-ui/inputs/src/search.html`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by nik132-eng** [comment]
can you please assign this to me?

**Comment by Rajdip019** [comment]
Search input is already there. @nik132-eng
