### ISSUE TITLE
Create a Validation in input

### ISSUE THREAD

**Issue by nik132-eng** [Clueless-Community/seamless-ui#768]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
![image](https://user-images.githubusercontent.com/77881638/207044006-dc4db2db-3948-4dc5-9ab9-25c9802d1899.png)

After building the component please raise a PR with a screenshot of the component and add the component in `seamless-ui/inputs/src/validation.html`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by Rajdip019** [comment]
Sure make one @nik132-eng
