### ISSUE TITLE
Create a Gradient monochrome

### ISSUE THREAD

**Issue by nik132-eng** [Clueless-Community/seamless-ui#769]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
![image](https://user-images.githubusercontent.com/77881638/207045154-e0c4b7f3-2796-4265-8bb1-71c7cceb0918.png)

After building the component please raise a PR with a screenshot of the component and add the component in `seamless-ui/Buttons/src/gradient-buttons.html`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by nik132-eng** [comment]
please assign it to me.

**Comment by Rajdip019** [comment]
Make these.  But the folder structure should be `Buttons/src/Gradient/gradient-1.html`
