### ISSUE TITLE
Create a Social buttons 

### ISSUE THREAD

**Issue by nik132-eng** [Clueless-Community/seamless-ui#770]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
![image](https://user-images.githubusercontent.com/77881638/207045695-ee935ffe-55df-47f1-a855-b2bb2dd7fbae.png)

After building the component please raise a PR with a screenshot of the component and add the component in `seamless-ui/Buttons/src/social-buttons.html`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by nik132-eng** [comment]
please assign it to me

**Comment by Rajdip019** [comment]
Looks great man but first finish all the previous PR. @nik132-eng
