### ISSUE TITLE
Create a Payment buttons

### ISSUE THREAD

**Issue by nik132-eng** [Clueless-Community/seamless-ui#771]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
![image](https://user-images.githubusercontent.com/77881638/207046132-9491e4ab-b156-41a4-a5ae-3a1cf3801fdd.png)

After building the component please raise a PR with a screenshot of the component and add the component in `seamless-ui/Buttons/src/payment-buttons.html`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by nik132-eng** [comment]
can you please assign it to me?

**Comment by Rajdip019** [comment]
I guess these buttons are directly copied from Flowbite. Make sure the change the design otherwise these PR will be marked as invalid and closed. @nik132-eng

**Comment by nik132-eng** [comment]
I am making changes in all PR surely doing with this also.

**Comment by Rajdip019** [comment]
Okay make changes and share a screenshot @nik132-eng

**Comment by nik132-eng** [comment]
![Screenshot_2022-12-13-02-32-01-361_com android chrome](https://user-images.githubusercontent.com/77881638/207153827-3290c7e9-6b80-4bdd-9392-78dc69369c2c.jpg)

Don't know but chrome internet is not working now in laptop.

**Comment by Rajdip019** [comment]
Looks great make a PR for this. @nik132-eng
