### ISSUE TITLE
Cool Movie Overlay part-2

### ISSUE THREAD

**Issue by Kumar-Ankit56** [Clueless-Community/seamless-ui#778]
## What is the motivation for adding/enhancing this feature?
This is will fully pledge UI build on the HTML and Tailwind as If you are developer and know about movie API, so you have tried a card to display fetch movie API card. If you're looking for designing the card from scratch, then must use this overlay cool movie card.

 
Here is a reference to the component. 
#### Add image here
1st state
![Screenshot (80)](https://user-images.githubusercontent.com/73521123/207129016-43cf6e7e-27bf-4392-b9e6-ef4268163ba4.png)

while hover on it image will scale and show the related text 
![Screenshot (79)](https://user-images.githubusercontent.com/73521123/207129048-42a32360-36b7-4988-aaa1-fa577eba409f.png)

This is just sample design. Final project will be improved one.

https://play.tailwindcss.com/cKdvfmvA3f?layout=preview

Check and suggest the improvement or should I open the Prs for this issue

**Comment by Rajdip019** [comment]
Make one and it to others folder as well. @Kumar-Ankit56
