### ISSUE TITLE
Create a timeline 

### ISSUE THREAD

**Issue by nik132-eng** [Clueless-Community/seamless-ui#799]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
![image](https://user-images.githubusercontent.com/77881638/207281192-88b4d8f7-1588-4939-9563-ab21d980daa7.png)

I have to create timeline folder first. 

After building the component please raise a PR with a screenshot of the component and add the component in `seamless-ui/Timeline/timeline-1.html`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by nik132-eng** [comment]
please assign it to me

**Comment by Rajdip019** [comment]
This is already created. So closing this issue. @nik132-eng
