### ISSUE TITLE
Create a Video component for adding video files

### ISSUE THREAD

**Issue by nik132-eng** [Clueless-Community/seamless-ui#801]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 

After building the component please raise a PR with a screenshot of the component and add the component in `seamless-ui/Video/src/video-1.html`.
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by Rajdip019** [comment]
Do you have a picture of that. @nik132-eng  for reference?

**Comment by Rajdip019** [comment]
Can you share some screenshots how you are thinking to build this. @nik132-eng

**Comment by nik132-eng** [comment]
![image](https://user-images.githubusercontent.com/77881638/207652100-5b2873ad-c343-431e-b949-76d81476ef60.png)

**Comment by Rajdip019** [comment]
We have a video component in the content card you can fix that and make that a video component. @nik132-eng
