### ISSUE TITLE
Make design system for Pricing Components

### ISSUE THREAD

**Issue by itz-deepak** [Clueless-Community/seamless-ui#809]
Make and awesome design system for `Pricing` Component.

See the [Pricing Components](https://github.com/Clueless-Community/seamless-ui/tree/main/Pricing%20Components/src) and make one.

Refer to : [Button Design System for any reference](https://github.com/Clueless-Community/seamless-ui/blob/main/Buttons/buttons.design-system.mdx) or ask me in any confusion.

Tip :
You can use [Tailwind Playground](https://play.tailwindcss.com/)

**Comment by itz-deepak** [comment]
Assign this to me Already created solution for this issue

**Comment by Rajdip019** [comment]
Same for this as well. But I am giving points as this a valid issue and we will work on this in future.
