### ISSUE TITLE
Make design system for Store Buttons

### ISSUE THREAD

**Issue by itz-deepak** [Clueless-Community/seamless-ui#811]
Make and awesome design system for `Store Buttons` Component.

See the [Store Buttons](https://github.com/Clueless-Community/seamless-ui/tree/main/Store%20Buttons/src) and make one.

Refer to : [Button Design System for any reference](https://github.com/Clueless-Community/seamless-ui/blob/main/Buttons/buttons.design-system.mdx)

Tip :
You can use [Tailwind Playground](https://play.tailwindcss.com/)

**Comment by Rajdip019** [comment]
Hey for now I am closing this issue. What you can do is raise and issue to fix the Store buttons and work it. @itz-deepak 

Then according to that we can make a design system. Make sure to show me once what you have done and after checking you can make the design system and make all the other buttons as well. @itz-deepak 

For better communication you can use the discord that would be better I guess.
