### ISSUE TITLE
Make design system for Dropdown

### ISSUE THREAD

**Issue by itz-deepak** [Clueless-Community/seamless-ui#812]
Make and awesome design system for `Dropdown` Component.

See the [Dropdown](https://github.com/Clueless-Community/seamless-ui/tree/main/Dropdown/src) and make one.

Refer to : [Button Design System for any reference](https://github.com/Clueless-Community/seamless-ui/blob/main/Buttons/buttons.design-system.mdx) 

Tip :
You can use [Tailwind Playground](https://play.tailwindcss.com/)

**Comment by itz-deepak** [comment]
Assign this to me

**Comment by Rajdip019** [comment]
We will be removing the dropdown for now so don't need this.
