### ISSUE TITLE
Make design system for Book Appointment

### ISSUE THREAD

**Issue by itz-deepak** [Clueless-Community/seamless-ui#813]
Make and awesome design system for `Book Appointment` Component.

See the [Book Appointment](https://github.com/Clueless-Community/seamless-ui/tree/main/Book%20appointment%20component/src) and make one.

Refer to : [Button Design System for any reference](https://github.com/Clueless-Community/seamless-ui/blob/main/Buttons/buttons.design-system.mdx) 

Tip :
You can use [Tailwind Playground](https://play.tailwindcss.com/)

**Comment by itz-deepak** [comment]
Assign this to me

**Comment by Rajdip019** [comment]
Same for this as well. But I am giving points as this a valid issue and we will work on this in future. @itz-deepak
