### ISSUE TITLE
Make design system for Form Groups

### ISSUE THREAD

**Issue by itz-deepak** [Clueless-Community/seamless-ui#815]
Make and awesome design system for `Form Groups` Component.

See the [Form Groups](https://github.com/Clueless-Community/seamless-ui/tree/main/Form%20groups/src) and make one.

Refer to : [Button Design System for any reference](https://github.com/Clueless-Community/seamless-ui/blob/main/Buttons/buttons.design-system.mdx) 

Tip :
You can use [Tailwind Playground](https://play.tailwindcss.com/)

**Comment by Rajdip019** [comment]
Same for this as well. But I am giving points as this a valid issue and we will work on this in future.
