### ISSUE TITLE
Make design system for Rating

### ISSUE THREAD

**Issue by itz-deepak** [Clueless-Community/seamless-ui#816]
Make and awesome design system for `Rating` Component.

See the [Rating](https://github.com/Clueless-Community/seamless-ui/tree/main/Rating/src) and make one.

Refer to : [Button Design System for any reference](https://github.com/Clueless-Community/seamless-ui/blob/main/Buttons/buttons.design-system.mdx) 

Tip :
You can use [Tailwind Playground](https://play.tailwindcss.com/)

**Comment by hritikbhattacharya** [comment]
what we have to do in this?

**Comment by hritikbhattacharya** [comment]
if you explain little bit it will be better.
assign it to me @itz-deepak

**Comment by Rajdip019** [comment]
Hey @itz-deepak can you explain @hritikbhattacharya more about this.

**Comment by itz-deepak** [comment]
> if you explain little bit it will be better. assign it to me @itz-deepak

For these type of issue we have to create a `.mdx` file under which a system will be made that need to be followed while making the components
In this we can include some screenshot of component, some general style guidelines  (color, padding, margin, radius) or any other property that is used generally. Also include example  code and referece to components used (like : buttons and icons )
