### ISSUE TITLE
Make design system for Testimonials

### ISSUE THREAD

**Issue by itz-deepak** [Clueless-Community/seamless-ui#817]
Make and awesome design system for `Testimonials` Component.

See the [Testimonials](https://github.com/Clueless-Community/seamless-ui/tree/main/Testimonials/src) and make one.

Refer to : [Button Design System for any reference](https://github.com/Clueless-Community/seamless-ui/blob/main/Buttons/buttons.design-system.mdx) 

Tip :
You can use [Tailwind Playground](https://play.tailwindcss.com/)

**Comment by itz-deepak** [comment]
Assign this to me

**Comment by Rajdip019** [comment]
Same here for now we need to fix the testimonial part first. @itz-deepak
