### ISSUE TITLE
Make design system for Widgets

### ISSUE THREAD

**Issue by itz-deepak** [Clueless-Community/seamless-ui#821]
Make and awesome design system for `Widgets` Component.

See the [Widgets](https://github.com/Clueless-Community/seamless-ui/tree/main/Widgets/src) and make one.

Refer to : [Button Design System for any reference](https://github.com/Clueless-Community/seamless-ui/blob/main/Buttons/buttons.design-system.mdx) 

Tip :
You can use [Tailwind Playground](https://play.tailwindcss.com/)

**Comment by itz-deepak** [comment]
Assign this to me

**Comment by Rajdip019** [comment]
Same for this as well. But I am giving points as this a valid issue and we will work on this in future.
