### ISSUE TITLE
Make design system for Product Cards

### ISSUE THREAD

**Issue by itz-deepak** [Clueless-Community/seamless-ui#822]
Make and awesome design system for `Product Cards` Component.

See the [Product Cards](https://github.com/Clueless-Community/seamless-ui/tree/main/Product%20Cards/src) and make one.

Refer to : [Button Design System for any reference](https://github.com/Clueless-Community/seamless-ui/blob/main/Buttons/buttons.design-system.mdx) 

Tip :
You can use [Tailwind Playground](https://play.tailwindcss.com/)

**Comment by nik132-eng** [comment]
![image](https://user-images.githubusercontent.com/77881638/207510144-da3daf2f-8375-486d-9b46-fcb0dedd934e.png)

can i work on this?

**Comment by itz-deepak** [comment]
Assign this to me Already created solution for this issue
