### ISSUE TITLE
Add Feedback form feedback-1.html

### ISSUE THREAD

**Issue by G0V1NDK** [Clueless-Community/seamless-ui#829]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
![image](https://user-images.githubusercontent.com/83280091/207309928-45ea30e7-d148-4d92-b01b-327c3cc72d36.png)

After building the component please raise a PR with a screenshot of the component and add the component in `seamless-ui/Feedback/src/feedback-1.html`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by G0V1NDK** [comment]
@Rajdip019 please assign me this issue.

**Comment by Rajdip019** [comment]
You need to make this with our design system. @G0V1NDK

**Comment by G0V1NDK** [comment]
@Rajdip019 Done the required changes. So can I make a PR?

![image](https://user-images.githubusercontent.com/83280091/207532426-7b8e373e-7a59-49b0-a6ab-08af886f547c.png)

**Comment by Rajdip019** [comment]
Looks nice make PR and I will review it. @G0V1NDK
