### ISSUE TITLE
Create a spinner folder

### ISSUE THREAD

**Issue by nik132-eng** [Clueless-Community/seamless-ui#845]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
![image](https://user-images.githubusercontent.com/77881638/207512702-de7e0125-e988-44c2-b245-0d5a46ccce78.png)

I can add more spinners to different issues if you give me permission.

After building the component please raise a PR with a screenshot of the component and add the component in `seamless-ui/Spinner/src/spiner-1.html`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by Rajdip019** [comment]
Does the spinner work? Then make them blue.

**Comment by nik132-eng** [comment]
https://play.tailwindcss.com/8a789cCTvI

![image](https://user-images.githubusercontent.com/77881638/207658926-3ab04de4-4820-4847-af6e-c67f5011a4d3.png)

can i add this code?

**Comment by Rajdip019** [comment]
Sure looks good, make a PR and add it to the others folder for now. `spinner-01.html`
