### ISSUE TITLE
Remove Duplicate Navbar 22

### ISSUE THREAD

**Issue by RavindraP04** [Clueless-Community/seamless-ui#889]
Need to remove this component `Navbar/src/navbar-22.html` because `Navbar 22` is duplicate of  **_Navbar 0_** and also navbar 22 does not follow Navbar Design System. 

Here is [Navbar 0](https://github.com/Clueless-Community/seamless-ui/blob/main/Navbar/src/navbar-0.html)
Here is [Navbar 22](https://github.com/Clueless-Community/seamless-ui/blob/main/Navbar/src/navbar-22.html)

![Screenshot_20221214_191842](https://user-images.githubusercontent.com/98400348/207613278-fd3dfd61-4f90-4022-b6fc-b00ffdaeb14b.png)

**Comment by RavindraP04** [comment]
@Rajdip019 Either Remove it or else I will raise the PR

**Comment by Rajdip019** [comment]
I will be removing it. @RavindraP04

**Comment by RavindraP04** [comment]
> I will be removing it. @RavindraP04

Ok, and can you please tell me, why have you not merged footer 6, 7, 8 ?

**Comment by Rajdip019** [comment]
That was a mistake sorry for the inconvenience.
