### ISSUE TITLE
Remove Duplicate Navabr 25

### ISSUE THREAD

**Issue by RavindraP04** [Clueless-Community/seamless-ui#890]
Need to remove this component `Navbar/src/navbar-25.html` or  `Navbar/src/navbar-23.html`  because **_Navbar 25_** is identical to **_Navbar 23_** and also both the navbar are not mentioned in Figma file.

Also Navbar 25 is enclosed under _header_ tag instead fo _nav_ tag
![Screenshot_20221214_192635](https://user-images.githubusercontent.com/98400348/207615522-aa016bd1-608f-4646-ac0d-b621b3e3a020.png)

**Comment by RavindraP04** [comment]
@Rajdip019 What should I do with this one ?

**Comment by RavindraP04** [comment]
Also, **_Nav 02_** and _**Nav 26**_ are also somewhat similar & nav 26 does not follows the navbar design system in terms of padding
![image](https://user-images.githubusercontent.com/98400348/207616875-f15dcc4d-af2d-49c1-b956-5c9bae952935.png)

**Comment by Rajdip019** [comment]
We can have both one with a elevated design and one with normal one. What do you say? @RavindraP04

**Comment by RavindraP04** [comment]
Yup, No issue.


> We can have both one with a elevated design and one with normal one. What do you say? @RavindraP04

**Comment by Rajdip019** [comment]
No this is ok. Closing the issue.
