### ISSUE TITLE
Duplicate Navbar 02 & 26

### ISSUE THREAD

**Issue by RavindraP04** [Clueless-Community/seamless-ui#891]
##  **_Nav 02_** and _**Nav 26**_ are also somewhat similar & nav 26 does not follows the navbar design system in terms of padding
![image](https://user-images.githubusercontent.com/98400348/207616875-f15dcc4d-af2d-49c1-b956-5c9bae952935.png)

**Comment by RavindraP04** [comment]
@Rajdip019 So, What should I do ? Just improve the padding of nav 26 or remove it ?

**Comment by Rajdip019** [comment]
Improve it. One is dark mode another one is white.

**Comment by RavindraP04** [comment]
no, improvements required, padding is correct, so closed it.
