### ISSUE TITLE
Remove Duplicate Feature Card

### ISSUE THREAD

**Issue by RavindraP04** [Clueless-Community/seamless-ui#901]
Remove `Feature Cards/src/feature-card-19.html` because it is duplicate of `feature card 1`

## Remove [Feature Card 19](https://github.com/Clueless-Community/seamless-ui/blob/main/Feature%20Cards/src/feature-card-19.html)

![Screenshot_20221215_180252](https://user-images.githubusercontent.com/98400348/207860424-f982b958-8c50-497d-b7f6-bcb06364ad6e.png)

## Original [Feature Card 1](https://github.com/Clueless-Community/seamless-ui/blob/main/Feature%20Cards/src/feature-card-01.html)
![image](https://user-images.githubusercontent.com/98400348/207860367-2547412d-dee4-4989-887a-89083bf5c36a.png)

**Comment by RavindraP04** [comment]
@Rajdip019 Please review and remove feature card 19

**Comment by Rajdip019** [comment]
Sure. I will do that.
