### ISSUE TITLE
Add and Improve these Feature Card

### ISSUE THREAD

**Issue by RavindraP04** [Clueless-Community/seamless-ui#904]
##  Need to Add 2 missing feature cards and Improve font size and responsiveness 4 feature cards(7, 11, 14, 15)
![Add these Feature Cards](https://user-images.githubusercontent.com/98400348/207863662-ccfaaad5-b577-4d21-b3f4-73e8bc21c929.png)

**Comment by RavindraP04** [comment]
@Rajdip019 Please assign this to me

**Comment by Rajdip019** [comment]
Only 11 need to be done right?
