### ISSUE TITLE
Add Group List component

### ISSUE THREAD

**Issue by G0V1NDK** [Clueless-Community/seamless-ui#916]
One need to make this component using `HTML` and `Tailwind CSS`. I would suggest to use [Tailwind Playgrounds](https://play.tailwindcss.com/) to make things faster and quicker.

Here is a reference to the component. 
![image](https://user-images.githubusercontent.com/83280091/207910683-4f00603e-83f7-4bb8-9f8d-8c4df2bdbbf3.png)

After building the component please raise a PR with a screenshot of the component and add the component in ` seamless-ui/Group List/src/group_list_1.html`. 
  
If you need to use any icon please use it from [Hero Icons](https://heroicons.com/)

Good luck.

**Comment by G0V1NDK** [comment]
@Rajdip019 Please assign me this issue.

**Comment by Rajdip019** [comment]
We don't need new components right now. focus on improving present components. @G0V1NDK

**Comment by G0V1NDK** [comment]
Ok, I will look for it.
