### ISSUE TITLE
Improve avatar-text.html

### ISSUE THREAD

**Issue by nik132-eng** [Clueless-Community/seamless-ui#917]
Need to improve this component on `\Avtar\src\avatar-text.html`

## Improvements required :
add more avtar with size difference

## Any reference image?
![image](https://user-images.githubusercontent.com/77881638/207915295-aefa4c70-fee5-4efe-9c90-8b02d95f0aeb.png)
  
## Any external reference?
  
You can checkout [this]() one for better understanding.

**Comment by Rajdip019** [comment]
Yeah do that. @nik132-eng
