### ISSUE TITLE
Improve avatar-status.html

### ISSUE THREAD

**Issue by nik132-eng** [Clueless-Community/seamless-ui#918]
Need to improve this component on `\Avatar\src\avatar-status.html`

## Improvements required :
add numbers of messages 

## Any reference image?
  
![image](https://user-images.githubusercontent.com/77881638/207918169-70c474f8-569a-4955-80b6-7d38e118bf1a.png)

## Any external reference?
  
You can checkout [this]() one for better understanding.

**Comment by Rajdip019** [comment]
No need to do this as of now.
