### ISSUE TITLE
Improve feature card Readme

### ISSUE THREAD

**Issue by nik132-eng** [Clueless-Community/seamless-ui#919]
Need to improve this component on `\Feature Cards\README.md`

## Improvements required :
settle up readme file like button

## Any reference image?
  
![image](https://user-images.githubusercontent.com/77881638/207918585-bfec5fe1-e500-4647-a462-a4582a0de2be.png)

## Any external reference?
  
You can checkout [this]() one for better understanding.

**Comment by Rajdip019** [comment]
Yeah go for it.
