### ISSUE TITLE
Cool Food Card 

### ISSUE THREAD

**Issue by Kumar-Ankit56** [Clueless-Community/seamless-ui#928]
## What is the motivation for adding/enhancing this feature?
This is will fully pledge UI build on the HTML and Tailwind as If you are developer and know about
Food API, so you have tried a card to display fetch food API card. If you're looking for designing the card from scratch, then must use this overlay cool food card.

 
Here is a reference to the component. 
#### Add image here
1st state
![Screenshot (83)](https://user-images.githubusercontent.com/73521123/207952649-3f3ac632-a6ac-4b4a-b144-1fc2132afccf.png)

This is just sample design. Final project will be improved one.

https://play.tailwindcss.com/5N39B46mZu?layout=preview

Check and suggest the improvement or should I open the Prs for this issue

**Comment by Rajdip019** [comment]
This looks good. Add it to the `Others` folder for now.

**Comment by Rajdip019** [comment]
Hey, @Kumar-Ankit56 we don't need new components right now focus on improving present components or writing docs making README's
