### ISSUE TITLE
Merge Book Appointments and Contact

### ISSUE THREAD

**Issue by RavindraP04** [Clueless-Community/seamless-ui#938]
### Compare these both with the figma design below 👇 you will find that contact section has all the component listed in figma design except 1 which is inside Book appointment section & Book appointment section also has 1 duplicate section which is present in Contact section too.

![image](https://user-images.githubusercontent.com/98400348/208072822-be0baf9e-e233-4cf6-84df-1e7df9ecac6d.png)

# Solution:- Either Move Contac-3.html to Book Appointment section OR Merge Both considering that there is no Book appointment section in figma.

**Comment by RavindraP04** [comment]
## I would suggest just to move the contact-3.html to Book Appointment section because It is not meant to be in contact section
What do you say ? @Rajdip019

**Comment by Rajdip019** [comment]
Merge all of them with Contact and remove the Appointment section. That will be good. If you are removing that then remove the whole folder. @RavindraP04

**Comment by RavindraP04** [comment]
@Rajdip019  I have moved both the component of Book Appointment to Contact and Deleted Book Appointment

**Comment by Rajdip019** [comment]
Great work man! @RavindraP04
