### ISSUE TITLE
Improve avatar-status.html

### ISSUE THREAD

**Issue by G0V1NDK** [Clueless-Community/seamless-ui#939]
Need to improve this component on `Avatar/src/avatar-status.html`

## Improvements required :
The username should be displayed in front of the avatar.

![image](https://user-images.githubusercontent.com/83280091/208084991-efcd249e-decb-4660-93ef-5b17b288b8bd.png)

@Rajdip019 What do you think about this?

**Comment by Rajdip019** [comment]
I guess the normal one looks good. @G0V1NDK Closing this issue.
