### ISSUE TITLE
Create a travel-card

### ISSUE THREAD

**Issue by Dibyendu303** [Clueless-Community/seamless-ui#955]
One need to make this component using `HTML` and `Tailwind CSS`. 

Here is a reference to the component. 
![Screenshot (2070)](https://user-images.githubusercontent.com/66685553/208175850-20af4cfa-c6d0-468e-a24d-7fb29076bdf0.png)

**Comment by Dibyendu303** [comment]
@Rajdip019 . Can we add a travel card like this ?

**Comment by Rajdip019** [comment]
For now we are not accepting any outside component focus more on inuring the cards maintaining the standard
