### ISSUE TITLE
Remove duplicate tables in table folder

### ISSUE THREAD

**Issue by Dibyendu303** [Clueless-Community/seamless-ui#956]
In the table folder, [primary-table-dark.html](https://github.com/Clueless-Community/seamless-ui/blob/main/Tables/src/primary-table-dark.html) and [primary_table_dark.html](https://github.com/Clueless-Community/seamless-ui/blob/main/Tables/src/primary_table_dark.html) are the same tables.

Similarly, [primary-table-light.html](https://github.com/Clueless-Community/seamless-ui/blob/main/Tables/src/primary-table-light.html) and [table_primary.html](https://github.com/Clueless-Community/seamless-ui/blob/main/Tables/src/table_primary.html) are the same tables.

**Comment by Rajdip019** [comment]
yeah both are same I guess. You can remove normal on eI guess.

**Comment by Dibyendu303** [comment]
@Rajdip019 Sorry, I didn't understand what you said. Can you explain the last line.

**Comment by Rajdip019** [comment]
We only need the `primary-table-light.html` and `primary-table-dark.html` others you can delete. @Dibyendu303
