### ISSUE TITLE
Improve primary-table-dark

### ISSUE THREAD

**Issue by Dibyendu303** [Clueless-Community/seamless-ui#957]
Need to improve this component: primary-table-dark

## Improvements required :
The last column is not visible when viewed on mobile screens. So, make it responsive.

## Any reference image?
![Screenshot (2075)](https://user-images.githubusercontent.com/66685553/208178362-1a5982f5-03be-4875-9f54-592e2102c1b6.png)

**Comment by Dibyendu303** [comment]
Please assign me @Rajdip019

**Comment by Rajdip019** [comment]
What changes are you thinking?

**Comment by Dibyendu303** [comment]
I tried reducing the padding-x of the columns on small screens and I think that will work. @Rajdip019

**Comment by Rajdip019** [comment]
Okay sure that will work. @Dibyendu303
