### ISSUE TITLE
Improve primary-table-light

### ISSUE THREAD

**Issue by Dibyendu303** [Clueless-Community/seamless-ui#958]
Need to improve this component: primary-table-light

## Improvements required :
The last column is not visible when viewed on mobile screens. So, make it responsive.

## Any reference image?
![Screenshot (2076)](https://user-images.githubusercontent.com/66685553/208178555-15af083a-247d-4410-abb7-2e2c3f05e3ed.png)

**Comment by Dibyendu303** [comment]
Please assign me @Rajdip019

**Comment by Rajdip019** [comment]
Can you elaborate a bit exactly what you want to change. @Dibyendu303
