### ISSUE TITLE
Remove 5 duplicate cards from Filters

### ISSUE THREAD

**Issue by RavindraP04** [Clueless-Community/seamless-ui#979]
Need to remove 6 common cards from `Filters/src/desktop which are already present in  `Filters/src/mobile`

![Screenshot_20221217_140759](https://user-images.githubusercontent.com/98400348/208233671-6496d0d3-392b-43e1-9b4a-594140bb989b.png)
\

**Comment by RavindraP04** [comment]
@Rajdip019  Please assign this to me

**Comment by Rajdip019** [comment]
Sure.
