### ISSUE TITLE
Create Filter component

### ISSUE THREAD

**Issue by RavindraP04** [Clueless-Community/seamless-ui#980]
Add this component to `FIlter/desktop` and `Filters/mobile` respesctively
![Screenshot_20221217_141213](https://user-images.githubusercontent.com/98400348/208233804-608179a5-0b9f-4baf-b83b-840c5feaf4e5.png)
![Screenshot_20221217_141223](https://user-images.githubusercontent.com/98400348/208233803-1adb23d6-c28e-4ce0-98d9-38d53dceedae.png)

**Comment by RavindraP04** [comment]
@Rajdip019 Please assign this to me

**Comment by Rajdip019** [comment]
Sure go ahead @RavindraP04 check there are already filters built in Filter folder

**Comment by Rajdip019** [comment]
All of them are done? @RavindraP04

**Comment by RavindraP04** [comment]
> All of them are done? @RavindraP04

No, @Rajdip019 
Sorry to say but, I'm busy with end sem exams also I was just waiting for Dibyendu to improve the component which will be used in this component, Now that its done, I will surely make all the PR by tomorrow EOD.
