### ISSUE TITLE
Add Missing button 

### ISSUE THREAD

**Issue by RavindraP04** [Clueless-Community/seamless-ui#981]
Add Missing Store Buttons and Icon Button

![image](https://user-images.githubusercontent.com/98400348/208233977-2c7596be-4192-4445-9e30-0ec45369c917.png)

**Comment by RavindraP04** [comment]
@Rajdip019 Please assign this to me

**Comment by ankushj0801** [comment]
Please assign this issue to me. @Rajdip019

**Comment by Dibyendu303** [comment]
@RavindraP04 Store buttons are already present

**Comment by Rajdip019** [comment]
Yeah store buttons are already there just need to improve them. @Dibyendu303
